---
title: "Privacy Policy"
---

## Cookies and consent

When you first visit the site, you are asked to accept or reject cookies. Your preferences are saved in a cookie so they persist across visits. You can change your preferences at any time using the "Cookie Preferences" link in the footer of each page.

By default, functionality and analytics cookies are enabled. Advertising and targeting cookies are disabled.

## Analytics

This site uses [Google Analytics](https://marketingplatform.google.com/about/analytics/) to collect anonymous usage data, including pages visited, time spent on each page, browser version and type, country of visitor and referring websites. This data helps us understand how the site is used so we can improve its content and structure. Analytics cookies are only set after you accept cookies via the consent banner.

The information collected is aggregated and anonymous. It does not identify individual visitors. IP addresses are anonymized. For information on how Google Analytics processes and stores data, please refer to the following policies on Google’s website for more information:

- [Google’s main privacy policy](http://www.google.com/intl/en/policies/privacy/)
- [Cookies & Google Analytics on Websites](https://support.google.com/analytics/answer/11397207)
- [Opt out of Google Analytics Cookies](https://tools.google.com/dlpage/gaoptout)

## What do we do with this information?

We use this information to improve our sites and services. This information may also be used for statistical purposes. We may share de-identified aggregate or summary information regarding site visitation and use publicly or with volunteers, partners or third parties, including but not limited to funding entities. We may use publicly available data of the external online services in programmatic analysis and evaluation.

## Opting out

You can decline all non-essential cookies via the consent banner or the "Cookie Preferences" link in the footer. You can also opt out of Google Analytics entirely by installing the [Google Analytics Opt-out Browser Add-on](https://tools.google.com/dlpage/gaoptout).

## What about third party links on our websites?

Our websites provide links to third party sites as a service to visitors. We are not responsible for the privacy practices, security measures or data collection practices of third party sites or for their content. The choice to access these sites is at the visitor’s own risk.

## Limitations
Your privacy is very important to us. However, due to the existing legal and technical environment (e.g., third party interception of information), we cannot ensure that your personally identifiable information will not be disclosed to third parties in ways not described in this policy. We may disclose information when we believe such disclosure is necessary to comply with the law; enforce our agreements, or protect the rights, property or safety of our users or others.

## Who should be contacted regarding this Privacy Policy?
For questions or comments about this Privacy Policy, please contact hello@openscapes.org.
