---
title: "When To "Cloud""
subtitle: "Is in-cloud access and analysis for you?" 
date: last-modified
author: "NASA Openscapes Team"
citation_url: https://nasa-openscapes.github.io/earthdata-cloud-cookbook/when-to-cloud.html
slug: index
---


Cloud adoption often has a steep learning curve and can feel overwhelming. There are times when using the cloud is effective and times when the download model is more appropriate. Here we aim to help you decide what's best for your use case.

### What does it mean to be in The Cloud?

At a basic level, "The Cloud" is somewhere that isn't your computer. We all interact with data and services and that live in "The Cloud" in our daily lives. When we store photos in iCloud or Google accounts instead of on our cell phones, we are using cloud storage. When we watch movies and tv shows on streaming services like Netflix or Hulu, we are using the cloud. In these cases, we are interacting with "the cloud" without knowing it, though we, the user, are not in "the cloud".

If you use services like computing and storage, provided by a cloud service provider (Amazon Web Services, Microsoft Azure, Google Cloud Platform, etc.), then you are in "the cloud". Remember, "the cloud" is somewhere that isn't your computer. The storage location is elsewhere and the machines and processing is elsewhere. 

The following guidance is specific to NASA Earthdata and the particular cloud it is stored in, Amazon Web Services (AWS). While some services provided by NASA data archives are cloud-based and you interact with, **the guidance below refers to using compute and storage services provided by AWS that allow a user to work closely, or in the same cloud, as the data.**

### Questions to ask yourself
Source: [Data strategies for Future Us](https://nsidc.github.io/data_strategies_for_future_us/data_strategies_slides#/when-to-cloud) by Andy Barrett
- What is the data volume?
- How long will it take to download?
- Can you store all that data (cost and space)?
- Do you have the computing power for processing?
- Does your team need a common computing environment?
- Do you need to share data at each step or just an end product?
- Is the action I want to take an existing service? (i.e. subsetting a dataset)


### To Cloud...

_list example cases here: identify and describe what makes cloud usage more benficial for the team/workflow_

### Not To Cloud...

_list examples cases here: identify and describe what makes the non-option more beneficial for the team/workflow_
 
 - a bit of discussion + examples for each question
  - concrete examples accomapnying each question
  - "I have a TB of storage on my laptop...." storage scenarios
  - see this from Ryan Abernathy: <https://medium.com/pangeo/closed-platforms-vs-open-architectures-for-cloud-native-earth-system-analytics-1ad88708ebb6>
  - include a question on actions that are already services (subsetting, etc.)


- include workflow type figures and discuss
  - link to any relevant tutorials that demo these workflows
  - how can you "cloud"?
  - what's already available (services that assist)

### Challenges
It is important to be aware of the drawbacks and challenges associated with working in the cloud. Common feedback from early cloud adopters are summarized here:

- feedback from Champions/workshop participants
- (see Alexis ESIP poster, AGU poster), link to it? Translate it here? Into a better figure?
- (this could be its own section on website?)

### Considerations
We are now accustomed to living in a highly digital world, separated from physical reminders of the technology we use. No longer do we access documents from a row of filing cabinets, we now store them in cloud-based archives (e.g. Google Docs). We run code on high-performance computing clusters, removed from the whirring and warmth generated by servers that live away from our desks. The following are considerations for using powerful cloud-based resources:

- separation from physical signs of compute power (using resources/energy)
- physical location of "the cloud", whose land is it on?
- testing/playing locally before migrating workflow to the cloud
- working remotely (not WFH, but computer is remote)
- environmental impacts of large server farms 