---
title: Workshops & Hackathons
---

We develop tutorials for teaching events that each have their own e-book. The following is a list of past workshops or hackathons we have hosted with links to their respective e-books. Tutorials are developed to teach open science and Cloud workflows for specific audiences. They are a snapshot in time as workflows with NASA Earthdata Cloud emerge and evolve. We will be updating [How-To Guides](../how-tos/index.qmd) as more stable ("source") instruction as we develop and learn from the teachings below.

## PACE Data Hackweeks

- [**https://pacehackweek.github.io/pace-2025**](https://pacehackweek.github.io/pace-2025/)
- [**https://pacehackweek.github.io/pace-2024**](https://pacehackweek.github.io/pace-2024/)

The NASA Plankton, Aerosol, Cloud, ocean Ecosystem (PACE) Hackweek is a social coding sprint held early August in-person at the [University of Maryland Baltimore County](https://umbc.edu/), and fiscally supported by the [Ocean Carbon & Biogeochemistry](https://www.us-ocb.org/) program. The workshop utilizes the [CryoCloud JupyterHub](https://book.cryointhecloud.com/intro.html), which is maintained through a partnership between organizers from the NASA Cryosphere community and the International Interactive Computing Collaboration (2i2c) team. Around 50 participants attend this free event; US based participants receive full travel support, and OCB provides stipends to offset international travel expenses. Each day is divided into science lectures, coding tutorials, and group project work. Every evening includes a social event: a Bob Ross Paint Night, a “fireside chat” with NASA Program Managers, a Chesapeake Bay blue crab feast at Patapsco State Park, Nerd Nite ("talent" show), and Trivia (with awards provided by OCB!). We have hacked on many interesting science questions: detecting anomalies in PACE hyperspectral remote sensing reflectance signals, studying relationships between aerosol and surface ocean properties impacted by wildfires and smoke plumes, and studying biological and physical characteristics of a Gulf Stream eddy using both PACE and SWOT data. Links to slides, notebooks, project repositories, and recordings are available on the event websites!

## 2024 SWOT Data Access Workshop

[**https://podaac.github.io/2024-SWOT-Hydro-Workshop/**](https://podaac.github.io/2024-SWOT-Hydro-Workshop/)

The Surface Water and Ocean Topography (SWOT) satellite, a joint NASA-CNES venture, provides unprecedented measurements of surface water extents and elevations for hydrologic science and applications. This workshop focuses on the SWOT Hydrology datasets including river and lake vector data in shapefiles, and raster, pixel cloud, and pixel vector data in netCDF. In this pre-meeting workshop hosted by the Physical Oceanography Distributed Active Archive Center (PO.DAAC) for the AGU Chapman: Remote Sensing of the Water Cycle Conference, participants are introduced to SWOT and the various ways to access and utilize its data products, including via cloud computing, local download, and data transformation tools.

## 2024 Champions Cohort

**<https://nasa-openscapes.github.io/news/2024-07-24-2024-nasa-champions-cohort>**

The 2024 NASA Champions cohort focused on data strategies for when to use cloud, coding strategies for parallelization, & first examples of big science in the Cloud. From April-May 2024, the NASA Mentors who span 11 Distributed Active Archive Centers (DAACs) co-led the third Champions Cohort with the NASA Openscapes project team, this year focusing on, teaching lessons they adapted for geospatial and cloud analysis. The Cohort included 9 international research teams from academia and government that were curious about working with NASA Earthdata in the Cloud. Many teams were interested in using data from multiple DAACs. User cloud adaption takes time, given the new conceptual mindsets and technical skillsets it requires. During the ten weeks we worked together, NASA Mentors refined and extended previous lessons to focus on thinking through and planning the transition to using the Cloud for science research and applications, and initial experiments using the Cloud through our 2i2c JupyterHub. The news page above links to Mentor lessons, YouTube clips, and what the teams achieved!

## 2023 Cloud Workshop at AGU

[**https://nasa-openscapes.github.io/2023-Cloud-Workshop-AGU**](https://nasa-openscapes.github.io/2023-Cloud-Workshop-AGU)

In this workshop, NASA Openscapes Mentors from NASA’s Earth Observing System Data and Information System (EOSDIS) DAACs (data centers) will teach the foundations of an open science mindset and apply these concepts to work in the cloud with NASA Earthdata. Participants will take part in hands-on tutorials using a JupyterHub managed by 2i2c in AWS. Participants will leave with a better understanding of how to leverage data and services from NASA Earthdata Cloud within their work across a variety of disciplines and data types, as well as how to apply the concepts of open science as a daily practice. The workshop will encourage discussion and reflection on how Earth science is evolving. Tutorials will be taught in Python. The target audience is anyone interested in using NASA Earth Science data within the AWS cloud. Previous experience in the AWS cloud is not necessary. Experience using Python is recommended but not required.

## 2023 VITALS Workshop at AGU

[**https://nasa.github.io/VITALS**](https://nasa.github.io/VITALS)

The International Space Station is a critical asset for the Earth science community – both for advancing critical science and applications priorities, and as a platform for technology demonstrations/pathfinders. These benefits have been particularly significant in recent years, with the installation and operation of instruments such as ECOSTRESS, a multispectral thermal instrument, and EMIT, a visible to short wave infrared imaging spectrometer with best-in-class signal to noise - both acquiring data at field-scale (<70-m). With both sensors mounted on the ISS, there is an unprecedented opportunity to demonstrate the compounded benefits of working with both datasets. In this workshop we highlight the power of these tools when used together, through the use of open source tools and services, cloud compute resources to effectively combine data from ECOSTRESS and EMIT to perform scientific analyses and apply data to real world issues.

This workshop is hosted by [NASA Land Processes Distributed Activate Archive Center (LP DAAC)](https://lpdaac.usgs.gov/) and [NASA Jet Propulsion Laboratory (JPL)](https://www.jpl.nasa.gov/) with support from the [NASA Openscapes](https://nasa-openscapes.github.io/) project. Hands-on exercises will be executed from a Jupyter Hub on the Openscapes 2i2c cloud instance.


## 2023 GEDI / ICESat-2 Workshop

[**https://nasa-openscapes.github.io/2023-ssc/**](https://nasa-openscapes.github.io/2023-ssc/){.uri}

The goal of this workshop, as part of the [2023 Space and Sustainability Colloquium](https://espacioysostenibilidad.com/en/#), is to demonstrate how to find, access, and work with GEDI and ICESat-2 data from the Earthdata Cloud. Participants will learn how to search for and download data from NASA’s Earthdata Search Client, a graphical user interface (GUI) for search, discovery, and download application for also EOSDIS data assets. Participants will learn how to perform in-cloud data search, access, and processing routines where no data download is required, and data analysis can take place next to the data in the cloud.

## 2023 Champions Cohort

**<https://nasa-openscapes.github.io/news/2023-08-01-nasa-champions>**

The 2023 NASA Openscapes Champions Cohort had exciting progress for research teams using NASA Earthdata in the Cloud. From April-June 2023, the NASA Openscapes project team co-led the second Champions Cohort with NASA Mentors who spanned 7 Distributed Active Archive Centers (DAACs). The Cohort included 7 research teams from academia and government that were curious about working with NASA Earthdata in the Cloud. Cloud migration takes time, so in the ten weeks we worked together, the focus was on planning the transition, identifying resources, and initial experiments using the Cloud through our 2i2c JupyterHub. All of this work is underpinned by Openscapes and NASA’s commitment to Open science practices. The news page above links to Mentor lessons and what the teams achieved!

## 2022 ECOSTRESS Cloud Workshop

[**https://nasa-openscapes.github.io/2022-ECOSTRESS-Cloud-Workshop/**](https://nasa-openscapes.github.io/2022-ECOSTRESS-Cloud-Workshop/){.uri}

The goal of the workshop is expose ECOSTRESS data users to ECOSTRESS version 2 (v2) data products in the cloud. Learning objectives focus on how to find and access ECOSTRESS v2 data from Earthdata Cloud either by downloading or accessing the data on the cloud. The LP DAAC is the NASA archive for ECOSTRESS data products. ECOSTRESS v2 data products will hosted in the NASA Earthdata Cloud, hosted in AWS.

## 2022 SWOT Ocean Cloud Workshop

[**https://podaac.github.io/2022-SWOT-Ocean-Cloud-Workshop/**](https://podaac.github.io/2022-SWOT-Ocean-Cloud-Workshop/){.uri}

The goal of the workshop is to get ready for Surface Water and Ocean Topography ([SWOT](https://swot.jpl.nasa.gov/)) and enable the (oceanography) science team to be ready for processing and handling the large volumes of SWOT SSH data in the cloud. Learning objectives focus on how to access the [simulated SWOT L2 SSH data](https://podaac.jpl.nasa.gov/announcements/2022-01-31-Release-simulated-SWOT-SSH-version1-datasets) from Earthdata Cloud either by downloading or accessing the data on the cloud. PO.DAAC is the NASA archive for the SWOT mission, and once launched will be making data available via the NASA Earthdata Cloud, hosted in AWS.

## 2022 Champions Cohort

**<https://nasa-openscapes.github.io/news/2022-05-12-nasa-2022-champions>**

The 2022 Champions Cohort focused on shifting from downloading data to Cloud access. In Spring 2022 we led our first NASA Openscapes Champions Cohort for 10 research teams that work with NASA EarthData. This cohort is funded by NASA and part of our NASA Openscapes Framework project. For this Cohort, we co-led the cohort with the NASA DAAC mentors and we focused on shifting toward Open science, collaborative, reproducible practices to support research teams as they transition from the download model to the Cloud. We also actively experimented with cloud data access through the Openscapes 2i2c-hosted JupyterHub. The news page above links to Mentor lessons and what the teams achieved!


## 2021 Cloud AGU Workshop

[**https://nasa-openscapes.github.io/2021-Cloud-Workshop-AGU**](https://nasa-openscapes.github.io/2021-Cloud-Workshop-AGU){.uri}

The **2021 Cloud Workshop at AGU: Enabling Analysis in the Cloud Using NASA Earth Science Data** is a virtual half-day collaborative open science learning experience aimed at exploring, learning, and promoting effective cloud-based science and applications workflows using NASA Earthdata Cloud data, tools, and services (among others), in support of Earth science data processing and analysis in the era of big data.

## 2021 Cloud Hackathon

[**https://nasa-openscapes.github.io/2021-Cloud-Hackathon**](https://nasa-openscapes.github.io/2021-Cloud-Hackathon){.uri}

The **Cloud Hackathon: Transitioning Earthdata Workflows to the Cloud** is a virtual 5-day (4 hours per day) collaborative open science learning experience aimed at exploring, creating, and promoting effective cloud-based science and applications workflows using NASA Earthdata Cloud data, tools, and services (among others), in support of Earth science data processing and analysis in the era of big data. Its goals are to:

1.  **Introduce** Earth science data users to NASA Earthdata cloud-based data products, tools and services in order to increase awareness and support transition to cloud-based science and applications workflows.

2.  **Enable** science and applications workflows in the cloud that leverage NASA Earth Observations and capabilities (services) from within the NASA Earthdata Cloud, hosted in Amazon Web Services (AWS) cloud, thus increasing NASA Earthdata data utility and meaningfulness for science and applications use cases.

3.  **Foster community engagement** utilizing Earthdata cloud tools and services in support of open science and open data.
