---
title: Leading Workshops
---

This section, under development, will include information for workshop prep, setup, and hosting.

------------------------------------------------------------------------

## Using the Openscapes 2i2c Hub in a workshop

- Check with Luis that the Hub image has the packages you need
- Reach out to 2i2c _a month in advance_ via email `support at 2i2c.freshdesk.com` 
  (examples below) to tell them about the workshop date, start and end times, 
  \# of participants, anticipated level of resources to be used, access 
  method, and if appropriate, a desired password.

We divide types of workshops into two different categories, with different
access patterns:

### Workshop Hub Access via GitHub Teams

If you are hosting a smaller workshop with learners  
with GitHub and who require longer-term access to the Hub after the workshop, 
follow the instructions to [add participants to the 2i2c Hub](add-folks-to-2i2c-github-teams.qmd) 
via a GitHub Team. Then send an email to `support at 2i2c.freshdesk.com`.

::: {.callout-tip collapse="true"}
## Example email to 2i2c for a workshop with GitHub authentication

Hello,

I wanted to reach out to the support desk to let you know that Openscapes will have a workshop using Python 2i2c instances for about 50 attendees.

Title: Data Access Workshop for NASA’s SWOT Satellite\
Date: February 13, 2024\
Duration/Time: half day, 9:00 am-12:30 pm HST (Honolulu, HI).\
Expected Usage: 3.7 GB per person (\~50 people)
The URL of the hub that will be used for the event: https://openscapes.2i2c.cloud/
Access Method: GitHub Team

Thank you!

Cassie
:::

### Workshop Hub Access via Shared Password

If you are hosting a workshop that has a large number of particpants, especially
if they are not all comfortable with GitHub and particpants do not require
access to the Hub when the workshop is complete, use the "shared password" 
access. This access method allows the instructors to share a single password
with learners at the start of the workshop which they can use to log on the the 
Hub.

::: {.callout-tip collapse="true"}
## Example email to 2i2c for a workshop with shared password authentication

Hello,

The LP DAAC and Openscapes have an upcoming event where we are planning to use 
the Openscapes Hub. Here’s the main information:

The GitHub handle or name of the community representative: [github username], email@somedomain.com
The date when the event will start: July 7, 2024
The date when the event will end: July ​7, 2024
What hours of the day will participants be active? 1:00pm - 5pm EEST (Athens, Greece).
Number of attendees: ~40
Resources per user: 14.8GB RAM / up to 3.7 CPU
The URL of the hub that will be used for the event: https://workshop.openscapes.2i2c.cloud/
Access method: shared password
Password choice: [YouChooseAPassword]

Thank you!

Erik
:::

Tell your learners that they will be able to access the Hub using the shared
password for one week following the workshop, after which the password will
be changed and the their home directories inside the Hub will be removed.

One week after the workshop, send another email to `support at 2i2c.freshdesk.com`
and request that the password be reset and users' home directories from the
workshop be removed.
