<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.0.14">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>EarthData Cloud Cookbook – on-prem_cloud</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
span.underline{text-decoration: underline;}
div.column{display: inline-block; vertical-align: top; width: 50%;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="../in-development/index.html" rel="next">
<link href="../tutorials/index.html" rel="prev">
<script src="../site_libs/quarto-html/quarto.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-dark.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="../site_libs/bootstrap/bootstrap-dark.min.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.6/require.min.js" integrity="sha512-c3Nl8+7g4LMSTdrm621y7kf9v3SDPnhxLNhcjFJbKECVnmZHTdo+IRO05sNLTH/D3vA6u1X32ehoLC7WFVdheg==" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js" integrity="sha512-bLT0Qm9VnAYZDflyKcBaQ2gg0hSYNQrJ8RilYldYQ1FxQYoCLtUjuuRuZo+fjqhx/qtq/1itJ0C2ejDxltZVFg==" crossorigin="anonymous"></script>
<script type="application/javascript">define('jquery', [],function() {return window.jQuery;})</script>


<link rel="stylesheet" href="../styles.css">
</head>

<body class="nav-sidebar docked">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
    <div class="container-fluid d-flex justify-content-between">
      <h1 class="quarto-secondary-nav-title">(Untitled)</h1>
      <button type="button" class="quarto-btn-toggle btn" aria-label="Show secondary navigation">
        <i class="bi bi-chevron-right"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse sidebar-navigation docked overflow-auto">
    <div class="pt-lg-2 mt-2 text-center sidebar-header sidebar-header-stacked">
      <a href="../" class="sidebar-logo-link">
      <img src="../images/nasa-openscapes.png" alt="" class="sidebar-logo py-0 d-lg-inline d-none">
      </a>
    <div class="sidebar-title mb-0 py-0">
      <a href="../">NASA Earthdata Cloud Cookbook</a> 
        <div class="sidebar-tools-main tools-wide">
    <a href="https://nasa-openscapes.github.io" title="NASA-Openscapes website" class="sidebar-tool px-1"><i class="bi bi-globe"></i></a>
    <a href="https://github.com/nasa-openscapes/earthdata-cloud-cookbook" title="Earthdata Cloud Cookbook repo" class="sidebar-tool px-1"><i class="bi bi-github"></i></a>
  <a href="" class="quarto-color-scheme-toggle sidebar-tool" onclick="window.quartoToggleColorScheme(); return false;" title="Toggle dark mode"><i class="bi"></i></a>
</div>
    </div>
      </div>
      <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
      </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../index.html" class="sidebar-item-text sidebar-link">Welcome</a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../our-cookbook.html" class="sidebar-item-text sidebar-link">Our Cookbook</a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../cheatsheet.html" class="sidebar-item-text sidebar-link">Workflow Cheatsheets</a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
    <div class="sidebar-item-container"> 
        <a href="../how-tos/index.html" class="sidebar-item-text sidebar-link">How To's</a>
      <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="false">
        <i class="bi bi-chevron-right ms-2"></i>
      </a>
    </div>
    <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 ">  
        <li class="sidebar-item sidebar-item-section">
    <div class="sidebar-item-container"> 
        <a href="../how-tos/find-data/index.html" class="sidebar-item-text sidebar-link">Find Data</a>
      <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" aria-expanded="false">
        <i class="bi bi-chevron-right ms-2"></i>
      </a>
    </div>
    <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth2 ">  
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../how-tos/earthdata_search.html" class="sidebar-item-text sidebar-link">Earthdata Search</a>
  </div>
</li>
    </ul>
  </li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../how-tos/authentication.html" class="sidebar-item-text sidebar-link">Authentication</a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../how-tos/transform.html" class="sidebar-item-text sidebar-link">Transform</a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
    <div class="sidebar-item-container"> 
        <a href="../how-tos/access/index.html" class="sidebar-item-text sidebar-link">Access - Cloud Workflow</a>
      <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" aria-expanded="false">
        <i class="bi bi-chevron-right ms-2"></i>
      </a>
    </div>
    <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth2 ">  
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../how-tos/access/Earthdata_Cloud__Single_File__HTTPS_Access_COG_Example.html" class="sidebar-item-text sidebar-link">COG HTTPS</a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../how-tos/access/Earthdata_Cloud__Single_File__Direct_S3_Access_COG_Example.html" class="sidebar-item-text sidebar-link">COG Direct S3</a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../how-tos/access/Multi-File_Direct_S3_Access_COG_Example.html" class="sidebar-item-text sidebar-link">COG Direct S3 - Multi-file</a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../how-tos/access/Earthdata_Cloud__Single_File__Direct_S3_Access_NetCDF4_Example.html" class="sidebar-item-text sidebar-link">NetCDF4/HDF5 Direct S3</a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../how-tos/access/Multi-File_Direct_S3_Access_NetCDF_Example.html" class="sidebar-item-text sidebar-link">NetCDF4/HDF5 Direct S3 - Multi-file</a>
  </div>
</li>
    </ul>
  </li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../how-tos/download.html" class="sidebar-item-text sidebar-link">Download</a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../how-tos/tech-setup.html" class="sidebar-item-text sidebar-link">Tech Setup (AWS)</a>
  </div>
</li>
    </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
    <div class="sidebar-item-container"> 
        <a href="../tutorials/index.html" class="sidebar-item-text sidebar-link">Tutorials</a>
      <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" aria-expanded="true">
        <i class="bi bi-chevron-right ms-2"></i>
      </a>
    </div>
    <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 show">  
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../tutorials/04_On-Prem_Cloud.html" class="sidebar-item-text sidebar-link active">Pairing Cloud and non-Cloud Data</a>
  </div>
</li>
    </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
    <div class="sidebar-item-container"> 
        <a href="../in-development/index.html" class="sidebar-item-text sidebar-link">In Development</a>
      <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" aria-expanded="false">
        <i class="bi bi-chevron-right ms-2"></i>
      </a>
    </div>
    <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth1 ">  
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../examples/earthdata-access-demo.html" class="sidebar-item-text sidebar-link">Earthdata Access (Python Library)</a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../examples/NSIDC/ICESat2-CMR-OnPrem-vs-Cloud.html" class="sidebar-item-text sidebar-link">Search &amp; Download NSIDC Cloud</a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../examples/NSIDC/ICESat2-CMR-AWS-S3.html" class="sidebar-item-text sidebar-link">Access NSIDC Cloud w/ CMR</a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../examples/Transform-workflow.html" class="sidebar-item-text sidebar-link">Direct Access &amp; Harmony Workflow</a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../examples/USGS_Landsat/Landsat_C2_Search_Access.html" class="sidebar-item-text sidebar-link">Search &amp; Access USGS Landsat Cloud</a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../how-tos/access/Earthdata_Cloud__Data_Access_OPeNDAP_Example.html" class="sidebar-item-text sidebar-link">OPeNDAP</a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../examples/ORNL/Data_Access__Direct_S3_Access__ORNL_DAYMET.html" class="sidebar-item-text sidebar-link">Direct S3 Data Access: NetCDF - Daymet v4 Daily TMAX Example</a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../external/cof-zarr-reformat.html" class="sidebar-item-text sidebar-link">COF Zarr Access via Reformat</a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../external/zarr-eosdis-store.html" class="sidebar-item-text sidebar-link">Zarr Example</a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
    <div class="sidebar-item-container"> 
        <a href="../examples/index.html" class="sidebar-item-text sidebar-link">Kerchunk Examples</a>
      <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" aria-expanded="false">
        <i class="bi bi-chevron-right ms-2"></i>
      </a>
    </div>
    <ul id="quarto-sidebar-section-6" class="collapse list-unstyled sidebar-section depth2 ">  
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../examples/GESDISC/GESDISC_MERRA2_tavg1_2d_flx_Nx__Kerchunk.html" class="sidebar-item-text sidebar-link">GES DISC - MERRA2</a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../examples/LPDAAC/LPDAAC_ECOSTRESS_LSTE__Kerchunk.html" class="sidebar-item-text sidebar-link">LP DAAC ECOSTRESS</a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../examples/PODAAC/PODAAC_ECCO_SSH__Kerchunk.html" class="sidebar-item-text sidebar-link">PO.DAAC ECCO SSH</a>
  </div>
</li>
    </ul>
  </li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../in-development/matlab.html" class="sidebar-item-text sidebar-link">Matlab &amp; AWS</a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../in-development/earthdata-python-r-handoff.html" class="sidebar-item-text sidebar-link"><code>earthdata</code>: Python-R Handoff</a>
  </div>
</li>
    </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
    <div class="sidebar-item-container"> 
        <a href="../contributing/index.html" class="sidebar-item-text sidebar-link">Contributing</a>
      <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-7" aria-expanded="false">
        <i class="bi bi-chevron-right ms-2"></i>
      </a>
    </div>
    <ul id="quarto-sidebar-section-7" class="collapse list-unstyled sidebar-section depth1 ">  
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../contributing/onboarding.html" class="sidebar-item-text sidebar-link">Onboarding Mentors</a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../contributing/setup.html" class="sidebar-item-text sidebar-link">Cookbook Setup</a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../contributing/workflow.html" class="sidebar-item-text sidebar-link">Workflow</a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../contributing/resources.html" class="sidebar-item-text sidebar-link">Resources</a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../contributing/quarto-website-tutorial.html" class="sidebar-item-text sidebar-link">Quarto Tutorial</a>
  </div>
</li>
    </ul>
  </li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../troubleshooting.html" class="sidebar-item-text sidebar-link">Troubleshooting</a>
  </div>
</li>
    </ul>
    </div>
</nav>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#pairing-cloud-and-non-cloud-data" id="toc-pairing-cloud-and-non-cloud-data" class="nav-link active" data-scroll-target="#pairing-cloud-and-non-cloud-data">Pairing Cloud and non-Cloud Data</a>
  <ul class="collapse">
  <li><a href="#accessing-and-harmonizing-data-located-within-and-outside-of-the-nasa-earthdata-cloud" id="toc-accessing-and-harmonizing-data-located-within-and-outside-of-the-nasa-earthdata-cloud" class="nav-link" data-scroll-target="#accessing-and-harmonizing-data-located-within-and-outside-of-the-nasa-earthdata-cloud">Accessing and harmonizing data located within and outside of the NASA Earthdata Cloud</a></li>
  <li><a href="#summary" id="toc-summary" class="nav-link" data-scroll-target="#summary">Summary</a></li>
  <li><a href="#requirements" id="toc-requirements" class="nav-link" data-scroll-target="#requirements">Requirements</a></li>
  <li><a href="#learning-objectives" id="toc-learning-objectives" class="nav-link" data-scroll-target="#learning-objectives">Learning Objectives</a></li>
  <li><a href="#import-packages" id="toc-import-packages" class="nav-link" data-scroll-target="#import-packages">Import packages</a></li>
  <li><a href="#specify-data-time-range-and-area-of-interest" id="toc-specify-data-time-range-and-area-of-interest" class="nav-link" data-scroll-target="#specify-data-time-range-and-area-of-interest">Specify data, time range, and area of interest</a></li>
  <li><a href="#search-and-download-icesat-2-atl07-files" id="toc-search-and-download-icesat-2-atl07-files" class="nav-link" data-scroll-target="#search-and-download-icesat-2-atl07-files">Search and download ICESat-2 ATL07 files</a>
  <ul class="collapse">
  <li><a href="#download-atl07-files" id="toc-download-atl07-files" class="nav-link" data-scroll-target="#download-atl07-files">Download ATL07 files</a></li>
  </ul></li>
  <li><a href="#determine-the-ghrsst-modis-l2-granules-returned-from-our-time-and-area-of-interest" id="toc-determine-the-ghrsst-modis-l2-granules-returned-from-our-time-and-area-of-interest" class="nav-link" data-scroll-target="#determine-the-ghrsst-modis-l2-granules-returned-from-our-time-and-area-of-interest">Determine the GHRSST MODIS L2 granules returned from our time and area of interest</a></li>
  <li><a href="#load-data-into-xarray-via-s3-direct-access" id="toc-load-data-into-xarray-via-s3-direct-access" class="nav-link" data-scroll-target="#load-data-into-xarray-via-s3-direct-access">Load data into xarray via S3 direct access</a>
  <ul class="collapse">
  <li><a href="#get-s3-credentials" id="toc-get-s3-credentials" class="nav-link" data-scroll-target="#get-s3-credentials">Get S3 credentials</a></li>
  <li><a href="#open-a-s3-file" id="toc-open-a-s3-file" class="nav-link" data-scroll-target="#open-a-s3-file">Open a s3 file</a></li>
  <li><a href="#plot-modis-and-icesat-2-data-on-a-map" id="toc-plot-modis-and-icesat-2-data-on-a-map" class="nav-link" data-scroll-target="#plot-modis-and-icesat-2-data-on-a-map">Plot MODIS and ICESat-2 data on a map</a></li>
  <li><a href="#extract-sst-coincident-with-icesat-2-track" id="toc-extract-sst-coincident-with-icesat-2-track" class="nav-link" data-scroll-target="#extract-sst-coincident-with-icesat-2-track">Extract SST coincident with ICESat-2 track</a></li>
  <li><a href="#plot-sst-and-height-along-track" id="toc-plot-sst-and-height-along-track" class="nav-link" data-scroll-target="#plot-sst-and-height-along-track">Plot SST and Height along track</a></li>
  </ul></li>
  </ul></li>
  </ul>
<div class="toc-actions"><div><i class="bi bi-github"></i></div><div class="action-links"><p><a href="https://github.dev/nasa-openscapes/earthdata-cloud-cookbook/blob/main/tutorials/04_On-Prem_Cloud.ipynb" class="toc-action">Edit this page</a></p><p><a href="https://github.com/nasa-openscapes/earthdata-cloud-cookbook/issues/new" class="toc-action">Report an issue</a></p></div></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">



<section id="pairing-cloud-and-non-cloud-data" class="level1">
<h1>Pairing Cloud and non-Cloud Data</h1>
<section id="accessing-and-harmonizing-data-located-within-and-outside-of-the-nasa-earthdata-cloud" class="level2">
<h2 class="anchored" data-anchor-id="accessing-and-harmonizing-data-located-within-and-outside-of-the-nasa-earthdata-cloud">Accessing and harmonizing data located within and outside of the NASA Earthdata Cloud</h2>
</section>
<section id="summary" class="level2">
<h2 class="anchored" data-anchor-id="summary">Summary</h2>
<hr>
<p>This tutorial will combine several workflow steps and components from the previous days, demonstrating the process of using the geolocation of data available outside of the Earthdata Cloud to then access coincident variables of cloud-accessible data. This may be a common use case as NASA Earthdata continues to migrate to the cloud, producing a “hybrid” data archive across Amazon Web Services (AWS) and original on-premise data storage systems. Additionally, you may also want to combine field measurements with remote sensing data available on the Earthdata Cloud.</p>
<p>This specific example explores the pairing of the ICESat-2 <a href="https://nsidc.org/data/atl07">ATL07 Sea Ice Height</a> data product, currently (as of November 2021) available publicly via direct download at the NSIDC DAAC, along with Sea Surface Temperature (SST) from the GHRSST MODIS L2 dataset (<a href="https://cmr.earthdata.nasa.gov/search/concepts/C1693233348-PODAAC.html">MODIS_A-JPL-L2P-v2019.0</a>) available from PO.DAAC on the Earthdata Cloud.</p>
<p>The use case we’re looking at today centers over an area north of Greenland for a single day in June, where a melt pond was observed using the <a href="https://openaltimetry.org/data/icesat2/?start_date=2019-06-22&amp;annoId=180">NASA OpenAltimetry</a> application. Melt ponds are an important feature of Arctic sea ice dynamics, leading to an decrease in sea ice albedo and other changes in heat balance. Many NASA Earthdata datasets produce variables including sea ice albedo, sea surface temperature, air temperature, and sea ice height, which can be used to better understand these dynamics.</p>
</section>
<section id="requirements" class="level2">
<h2 class="anchored" data-anchor-id="requirements">Requirements</h2>
<hr>
<ul>
<li><p>AWS instance running in us-west 2</p></li>
<li><p>Earthdata Login</p></li>
<li><p>.netrc file</p></li>
</ul>
</section>
<section id="learning-objectives" class="level2">
<h2 class="anchored" data-anchor-id="learning-objectives">Learning Objectives</h2>
<hr>
<ol type="1">
<li>Search for data programmatically using the Common Metadata Repository (CMR), determining granule (file) coverage across two datasets over an area of interest.</li>
<li>Download data from an on-premise storage system to our cloud environment.</li>
<li>Read in 1-dimensional trajectory data (ICESat-2 ATL07) into <code>xarray</code> and perform attribute conversions.</li>
<li>Select and read in sea surface temperature (SST) data (MODIS_A-JPL-L2P-v2019.0) from the Earthdata Cloud into <code>xarray</code>.</li>
<li>Extract, resample, and plot coincident SST data based on ICESat-2 geolocation.</li>
</ol>
<hr>
</section>
<section id="import-packages" class="level2">
<h2 class="anchored" data-anchor-id="import-packages">Import packages</h2>
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> os</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> pathlib <span class="im">import</span> Path</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> pprint <span class="im">import</span> pprint</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Access via download</span></span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> requests</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Access AWS S3</span></span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> s3fs</span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a><span class="co"># Read and work with datasets</span></span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> xarray <span class="im">as</span> xr</span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> h5py</span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-16"><a href="#cb1-16" aria-hidden="true" tabindex="-1"></a><span class="co"># For plotting</span></span>
<span id="cb1-17"><a href="#cb1-17" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> matplotlib.pyplot <span class="im">as</span> plt</span>
<span id="cb1-18"><a href="#cb1-18" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> cartopy.crs <span class="im">as</span> ccrs</span>
<span id="cb1-19"><a href="#cb1-19" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> shapely.geometry <span class="im">import</span> box</span>
<span id="cb1-20"><a href="#cb1-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-21"><a href="#cb1-21" aria-hidden="true" tabindex="-1"></a><span class="co"># For resampling</span></span>
<span id="cb1-22"><a href="#cb1-22" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pyresample</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</section>
<section id="specify-data-time-range-and-area-of-interest" class="level2">
<h2 class="anchored" data-anchor-id="specify-data-time-range-and-area-of-interest">Specify data, time range, and area of interest</h2>
<p>We are going to focus on getting data for an area north of Greenland for a single day in June.</p>
<p>These <code>bounding_box</code> and <code>temporal</code> variables will be used for data search, subset, and access below.</p>
<p>The same search and access steps for both datasets can be performed via <a href="https://search.earthdata.nasa.gov/search?sb%5B0%5D=-62.8%2C81.7%2C-53.4%2C83&amp;qt=2019-06-22T00%3A00%3A00.000Z%2C2019-06-22T23%3A59%3A59.999Z&amp;m=79.82854077875072!-70.03537326243078!3!0!0!0%2C2">Earthdata Search</a> using the same spatial and temporal filtering options. See the <a href="https://nasa-openscapes.github.io/2021-Cloud-Workshop-AGU/tutorials/01_Earthdata_Search.html">Earthdata Search tutorial</a> for more information on how to use Earthdata Search to discover and access data from the Earthdata Cloud.</p>
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Bounding Box spatial parameter in decimal degree 'W,S,E,N' format.</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>bounding_box <span class="op">=</span> <span class="st">'-62.8,81.7,-56.4,83'</span></span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Each date in yyyy-MM-ddTHH:mm:ssZ format; date range in start,end format</span></span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a>temporal <span class="op">=</span> <span class="st">'2019-06-22T00:00:00Z,2019-06-22T23:59:59Z'</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>See the <a href="https://nasa-openscapes.github.io/2021-Cloud-Hackathon/tutorials/01_Data_Discovery_CMR.html">Data Discovery with CMR tutorial</a> for more details on how to navigate the NASA Common Metadata Repository (CMR) Application Programming Interface, or API. For some background, the CMR catalogs all data for NASA’s Earth Observing System Data and Information System (EOSDIS). The CMR API allows applications (software, services, etc) to send information to each other. A helpful analogy is a waiter in a restaurant. The waiter takes your drink or food order that you select from the menu, often translated into short-hand, to the bar or kitchen, and then returns (hopefully) with what you ordered when it is ready.</p>
<p>The CMR API accepts search terms such as collection name, keywords, datetime range, and location, queries the CMR database and returns the results.</p>
<p>For this tutorial, we have already identified the unique identifier, or <code>concept_id</code> for each dataset:</p>
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>modis_concept_id <span class="op">=</span> <span class="st">'C1940473819-POCLOUD'</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>icesat2_concept_id <span class="op">=</span> <span class="st">'C2003771980-NSIDC_ECS'</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>This <a href="https://search.earthdata.nasa.gov/projects?projectId=6596763247">Earthdata Search Project</a> also provides the same data access links that we will identify in the following steps for each dataset (note that you will need an Earthdata Login account to access this project).</p>
</section>
<section id="search-and-download-icesat-2-atl07-files" class="level2">
<h2 class="anchored" data-anchor-id="search-and-download-icesat-2-atl07-files">Search and download ICESat-2 ATL07 files</h2>
<p>Perform a granule search over our time and area of interest. How many granules are returned?</p>
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>granule_url <span class="op">=</span> <span class="st">'https://cmr.earthdata.nasa.gov/search/granules'</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell" data-execution_count="5">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>response <span class="op">=</span> requests.get(granule_url,</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>                       params<span class="op">=</span>{</span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>                           <span class="st">'concept_id'</span>: icesat2_concept_id,</span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a>                           <span class="st">'temporal'</span>: temporal,</span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a>                           <span class="st">'bounding_box'</span>: bounding_box,</span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a>                           <span class="st">'page_size'</span>: <span class="dv">200</span>,</span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a>                       },</span>
<span id="cb5-8"><a href="#cb5-8" aria-hidden="true" tabindex="-1"></a>                       headers<span class="op">=</span>{</span>
<span id="cb5-9"><a href="#cb5-9" aria-hidden="true" tabindex="-1"></a>                           <span class="st">'Accept'</span>: <span class="st">'application/json'</span></span>
<span id="cb5-10"><a href="#cb5-10" aria-hidden="true" tabindex="-1"></a>                       }</span>
<span id="cb5-11"><a href="#cb5-11" aria-hidden="true" tabindex="-1"></a>                      )</span>
<span id="cb5-12"><a href="#cb5-12" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(response.headers[<span class="st">'CMR-Hits'</span>])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>2</code></pre>
</div>
</div>
<p>Print the file names, size, and links:</p>
<div class="cell" data-execution_count="6">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>granules <span class="op">=</span> response.json()[<span class="st">'feed'</span>][<span class="st">'entry'</span>]</span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> granule <span class="kw">in</span> granules:</span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="ss">f'</span><span class="sc">{</span>granule[<span class="st">"producer_granule_id"</span>]<span class="sc">}</span><span class="ss"> </span><span class="sc">{</span>granule[<span class="st">"granule_size"</span>]<span class="sc">}</span><span class="ss"> </span><span class="sc">{</span>granule[<span class="st">"links"</span>][<span class="dv">0</span>][<span class="st">"href"</span>]<span class="sc">}</span><span class="ss">'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>ATL07-01_20190622055317_12980301_004_01.h5 237.0905504227 https://n5eil01u.ecs.nsidc.org/DP9/ATLAS/ATL07.004/2019.06.22/ATL07-01_20190622055317_12980301_004_01.h5
ATL07-01_20190622200154_13070301_004_01.h5 230.9151573181 https://n5eil01u.ecs.nsidc.org/DP9/ATLAS/ATL07.004/2019.06.22/ATL07-01_20190622200154_13070301_004_01.h5</code></pre>
</div>
</div>
<section id="download-atl07-files" class="level3">
<h3 class="anchored" data-anchor-id="download-atl07-files">Download ATL07 files</h3>
<p>Although several services are supported for ICESat-2 data, we are demonstrating direct access through the “on-prem” file system at NSIDC for simplicity.</p>
<p>Some of these services include: - <a href="https://icepyx.readthedocs.io/en/latest/">icepyx</a> - From the icepyx documentation: “icepyx is both a software library and a community composed of ICESat-2 data users, developers, and the scientific community. We are working together to develop a shared library of resources - including existing resources, new code, tutorials, and use-cases/examples - that simplify the process of querying, obtaining, analyzing, and manipulating ICESat-2 datasets to enable scientific discovery.” - <a href="https://nsidc.org/support/how/how-do-i-programmatically-request-data-services#API">NSIDC DAAC Data Access and Service API</a> - The API provided by the NSIDC DAAC allows you to access data programmatically using specific temporal and spatial filters. The same subsetting, reformatting, and reprojection services available on select data sets through NASA Earthdata Search can also be applied using this API. - <a href="https://github.com/nsidc/NSIDC-Data-Tutorials/tree/main/notebooks/iceflow">IceFlow</a> - The IceFlow python library simplifies accessing and combining data from several of NASA’s cryospheric altimetry missions, including ICESat/GLAS, Operation IceBridge, and ICESat-2. In particular, IceFlow harmonizes the various file formats and georeferencing parameters across several of the missions’ data sets, allowing you to analyze data across the multi-decadal time series.</p>
<p>We’ve found 2 granules. We’ll download the first one and write it to a file with the same name as the <code>producer_granule_id</code>.</p>
<p>We need the url for the granule as well. This is href links we printed out above.</p>
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>icesat_id <span class="op">=</span> granules[<span class="dv">0</span>][<span class="st">'producer_granule_id'</span>]</span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>icesat_url <span class="op">=</span> granules[<span class="dv">0</span>][<span class="st">'links'</span>][<span class="dv">0</span>][<span class="st">'href'</span>]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>To retrieve the granule data, we use the <code>requests.get()</code> method, which will utilize the .netrc file on the backend to authenticate the request against Earthdata Login.</p>
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>r <span class="op">=</span> requests.get(icesat_url)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>The response returned by requests has the same structure as all the other responses: a header and contents. The header information has information about the response, including the size of the data we downloaded in bytes.</p>
<div class="cell" data-execution_count="9">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> k, v <span class="kw">in</span> r.headers.items():</span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="ss">f'</span><span class="sc">{</span>k<span class="sc">}</span><span class="ss">: </span><span class="sc">{</span>v<span class="sc">}</span><span class="ss">'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Date: Sun, 12 Dec 2021 01:52:31 GMT
Server: Apache
Vary: User-Agent
Content-Disposition: attachment
Content-Length: 248607461
Keep-Alive: timeout=15, max=100
Connection: Keep-Alive</code></pre>
</div>
</div>
<p>The contents needs to be saved to a file. To keep the directory clean, we will create a <code>downloads</code> directory to store the file. We can use a shell command to do this or use the <code>makedirs</code> method from the <code>os</code> package.</p>
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>os.makedirs(<span class="st">"downloads"</span>, exist_ok<span class="op">=</span><span class="va">True</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>You should see a <code>downloads</code> directory in the file browser.</p>
<p>To write the data to a file, we use <code>open</code> to open a file. We need to specify that the file is open for writing by using the <em>write-mode</em> <code>w</code>. We also need to specify that we want to write bytes by setting the <em>binary-mode</em> <code>b</code>. This is important because the response contents are bytes. The default mode for <code>open</code> is <code>text-mode</code>. So make sure you use <code>b</code>.</p>
<p>We’ll use the <code>with</code> statement <em>context-manager</em> to open the file, write the contents of the response, and then close the file. Once the data in <code>r.content</code> is written sucessfully to the file, or if there is an error, the file is closed by the <em>context-manager</em>.</p>
<p>We also need to prepend the <code>downloads</code> path to the filename. We do this using <code>Path</code> from the <code>pathlib</code> package in the standard library.</p>
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>outfile <span class="op">=</span> Path(<span class="st">'downloads'</span>, icesat_id)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span> <span class="kw">not</span> outfile.exists():</span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>    <span class="cf">with</span> <span class="bu">open</span>(outfile, <span class="st">'wb'</span>) <span class="im">as</span> f:</span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a>        f.write(r.content)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p><code>ATL07-01_20190622055317_12980301_004_01.h5</code> is an HDF5 file. <code>xarray</code> can open this but you need to tell it which group to read the data from. In this case we read the sea ice segment height data for ground-track 1 left-beam. You can explore the variable hierarchy in <a href="https://search.earthdata.nasa.gov/projects?p=C2003771980-NSIDC_ECS!C2003771980-NSIDC_ECS&amp;pg%5B1%5D%5Ba%5D=2027648674!NSIDC_ECS&amp;pg%5B1%5D%5Bv%5D=t&amp;pg%5B1%5D%5Bid%5D=ATL07-01_20190622055317_12980301_004_01.h5&amp;pg%5B1%5D%5Bgsk%5D=-start_date&amp;pg%5B1%5D%5Bm%5D=esi0&amp;q=atl07&amp;tl=1637194666!3!!&amp;m=13.8515625!-43.8046875!2!1!0!0%2C2">Earthdata Search</a>, by selecting the Customize option under Download Data.</p>
<p>This code block performs the following operations: - Extracts the <code>height_segment_height</code> variable from the heights group, along with the dimension variables contained in the higher level <code>sea_ice_segments</code> group, - Convert attributes from bytestrings to strings, - Drops the HDF attribute DIMENSION_LIST, - Sets _FillValue to NaN</p>
<div class="cell" data-execution_count="13">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>variable_names <span class="op">=</span> [</span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>    <span class="st">'/gt1l/sea_ice_segments/latitude'</span>,</span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a>    <span class="st">'/gt1l/sea_ice_segments/longitude'</span>,</span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a>    <span class="st">'/gt1l/sea_ice_segments/delta_time'</span>,</span>
<span id="cb16-5"><a href="#cb16-5" aria-hidden="true" tabindex="-1"></a>    <span class="st">'/gt1l/sea_ice_segments/heights/height_segment_height'</span></span>
<span id="cb16-6"><a href="#cb16-6" aria-hidden="true" tabindex="-1"></a>    ]</span>
<span id="cb16-7"><a href="#cb16-7" aria-hidden="true" tabindex="-1"></a><span class="cf">with</span> h5py.File(outfile, <span class="st">'r'</span>) <span class="im">as</span> h5:</span>
<span id="cb16-8"><a href="#cb16-8" aria-hidden="true" tabindex="-1"></a>    data_vars <span class="op">=</span> {}</span>
<span id="cb16-9"><a href="#cb16-9" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> varname <span class="kw">in</span> variable_names:</span>
<span id="cb16-10"><a href="#cb16-10" aria-hidden="true" tabindex="-1"></a>        var <span class="op">=</span> h5[varname]</span>
<span id="cb16-11"><a href="#cb16-11" aria-hidden="true" tabindex="-1"></a>        name <span class="op">=</span> varname.split(<span class="st">'/'</span>)[<span class="op">-</span><span class="dv">1</span>]</span>
<span id="cb16-12"><a href="#cb16-12" aria-hidden="true" tabindex="-1"></a>        <span class="co"># Convert attributes</span></span>
<span id="cb16-13"><a href="#cb16-13" aria-hidden="true" tabindex="-1"></a>        attrs <span class="op">=</span> {}</span>
<span id="cb16-14"><a href="#cb16-14" aria-hidden="true" tabindex="-1"></a>        <span class="cf">for</span> k, v <span class="kw">in</span> var.attrs.items():</span>
<span id="cb16-15"><a href="#cb16-15" aria-hidden="true" tabindex="-1"></a>            <span class="cf">if</span> k <span class="op">!=</span> <span class="st">'DIMENSION_LIST'</span>:</span>
<span id="cb16-16"><a href="#cb16-16" aria-hidden="true" tabindex="-1"></a>                <span class="cf">if</span> <span class="bu">isinstance</span>(v, <span class="bu">bytes</span>):</span>
<span id="cb16-17"><a href="#cb16-17" aria-hidden="true" tabindex="-1"></a>                    attrs[k] <span class="op">=</span> v.decode(<span class="st">'utf-8'</span>)</span>
<span id="cb16-18"><a href="#cb16-18" aria-hidden="true" tabindex="-1"></a>                <span class="cf">else</span>:</span>
<span id="cb16-19"><a href="#cb16-19" aria-hidden="true" tabindex="-1"></a>                    attrs[k] <span class="op">=</span> v</span>
<span id="cb16-20"><a href="#cb16-20" aria-hidden="true" tabindex="-1"></a>        data <span class="op">=</span> var[:]</span>
<span id="cb16-21"><a href="#cb16-21" aria-hidden="true" tabindex="-1"></a>        <span class="cf">if</span> <span class="st">'_FillValue'</span> <span class="kw">in</span> attrs:</span>
<span id="cb16-22"><a href="#cb16-22" aria-hidden="true" tabindex="-1"></a>            data <span class="op">=</span> np.where(data <span class="op">&lt;</span> attrs[<span class="st">'_FillValue'</span>], data, np.nan)</span>
<span id="cb16-23"><a href="#cb16-23" aria-hidden="true" tabindex="-1"></a>        data_vars[name] <span class="op">=</span> ([<span class="st">'segment'</span>], data, attrs)</span>
<span id="cb16-24"><a href="#cb16-24" aria-hidden="true" tabindex="-1"></a>    is2_ds <span class="op">=</span> xr.Dataset(data_vars)</span>
<span id="cb16-25"><a href="#cb16-25" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb16-26"><a href="#cb16-26" aria-hidden="true" tabindex="-1"></a>is2_ds</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="13">

<div><svg style="position: absolute; width: 0; height: 0; overflow: hidden">
<defs>
<symbol id="icon-database" viewbox="0 0 32 32">
<path d="M16 0c-8.837 0-16 2.239-16 5v4c0 2.761 7.163 5 16 5s16-2.239 16-5v-4c0-2.761-7.163-5-16-5z"></path>
<path d="M16 17c-8.837 0-16-2.239-16-5v6c0 2.761 7.163 5 16 5s16-2.239 16-5v-6c0 2.761-7.163 5-16 5z"></path>
<path d="M16 26c-8.837 0-16-2.239-16-5v6c0 2.761 7.163 5 16 5s16-2.239 16-5v-6c0 2.761-7.163 5-16 5z"></path>
</symbol>
<symbol id="icon-file-text2" viewbox="0 0 32 32">
<path d="M28.681 7.159c-0.694-0.947-1.662-2.053-2.724-3.116s-2.169-2.030-3.116-2.724c-1.612-1.182-2.393-1.319-2.841-1.319h-15.5c-1.378 0-2.5 1.121-2.5 2.5v27c0 1.378 1.122 2.5 2.5 2.5h23c1.378 0 2.5-1.122 2.5-2.5v-19.5c0-0.448-0.137-1.23-1.319-2.841zM24.543 5.457c0.959 0.959 1.712 1.825 2.268 2.543h-4.811v-4.811c0.718 0.556 1.584 1.309 2.543 2.268zM28 29.5c0 0.271-0.229 0.5-0.5 0.5h-23c-0.271 0-0.5-0.229-0.5-0.5v-27c0-0.271 0.229-0.5 0.5-0.5 0 0 15.499-0 15.5 0v7c0 0.552 0.448 1 1 1h7v19.5z"></path>
<path d="M23 26h-14c-0.552 0-1-0.448-1-1s0.448-1 1-1h14c0.552 0 1 0.448 1 1s-0.448 1-1 1z"></path>
<path d="M23 22h-14c-0.552 0-1-0.448-1-1s0.448-1 1-1h14c0.552 0 1 0.448 1 1s-0.448 1-1 1z"></path>
<path d="M23 18h-14c-0.552 0-1-0.448-1-1s0.448-1 1-1h14c0.552 0 1 0.448 1 1s-0.448 1-1 1z"></path>
</symbol>
</defs>
</svg>
<style>/* CSS stylesheet for displaying xarray objects in jupyterlab.
 *
 */

:root {
  --xr-font-color0: var(--jp-content-font-color0, rgba(0, 0, 0, 1));
  --xr-font-color2: var(--jp-content-font-color2, rgba(0, 0, 0, 0.54));
  --xr-font-color3: var(--jp-content-font-color3, rgba(0, 0, 0, 0.38));
  --xr-border-color: var(--jp-border-color2, #e0e0e0);
  --xr-disabled-color: var(--jp-layout-color3, #bdbdbd);
  --xr-background-color: var(--jp-layout-color0, white);
  --xr-background-color-row-even: var(--jp-layout-color1, white);
  --xr-background-color-row-odd: var(--jp-layout-color2, #eeeeee);
}

html[theme=dark],
body.vscode-dark {
  --xr-font-color0: rgba(255, 255, 255, 1);
  --xr-font-color2: rgba(255, 255, 255, 0.54);
  --xr-font-color3: rgba(255, 255, 255, 0.38);
  --xr-border-color: #1F1F1F;
  --xr-disabled-color: #515151;
  --xr-background-color: #111111;
  --xr-background-color-row-even: #111111;
  --xr-background-color-row-odd: #313131;
}

.xr-wrap {
  display: block;
  min-width: 300px;
  max-width: 700px;
}

.xr-text-repr-fallback {
  /* fallback to plain text repr when CSS is not injected (untrusted notebook) */
  display: none;
}

.xr-header {
  padding-top: 6px;
  padding-bottom: 6px;
  margin-bottom: 4px;
  border-bottom: solid 1px var(--xr-border-color);
}

.xr-header > div,
.xr-header > ul {
  display: inline;
  margin-top: 0;
  margin-bottom: 0;
}

.xr-obj-type,
.xr-array-name {
  margin-left: 2px;
  margin-right: 10px;
}

.xr-obj-type {
  color: var(--xr-font-color2);
}

.xr-sections {
  padding-left: 0 !important;
  display: grid;
  grid-template-columns: 150px auto auto 1fr 20px 20px;
}

.xr-section-item {
  display: contents;
}

.xr-section-item input {
  display: none;
}

.xr-section-item input + label {
  color: var(--xr-disabled-color);
}

.xr-section-item input:enabled + label {
  cursor: pointer;
  color: var(--xr-font-color2);
}

.xr-section-item input:enabled + label:hover {
  color: var(--xr-font-color0);
}

.xr-section-summary {
  grid-column: 1;
  color: var(--xr-font-color2);
  font-weight: 500;
}

.xr-section-summary > span {
  display: inline-block;
  padding-left: 0.5em;
}

.xr-section-summary-in:disabled + label {
  color: var(--xr-font-color2);
}

.xr-section-summary-in + label:before {
  display: inline-block;
  content: '►';
  font-size: 11px;
  width: 15px;
  text-align: center;
}

.xr-section-summary-in:disabled + label:before {
  color: var(--xr-disabled-color);
}

.xr-section-summary-in:checked + label:before {
  content: '▼';
}

.xr-section-summary-in:checked + label > span {
  display: none;
}

.xr-section-summary,
.xr-section-inline-details {
  padding-top: 4px;
  padding-bottom: 4px;
}

.xr-section-inline-details {
  grid-column: 2 / -1;
}

.xr-section-details {
  display: none;
  grid-column: 1 / -1;
  margin-bottom: 5px;
}

.xr-section-summary-in:checked ~ .xr-section-details {
  display: contents;
}

.xr-array-wrap {
  grid-column: 1 / -1;
  display: grid;
  grid-template-columns: 20px auto;
}

.xr-array-wrap > label {
  grid-column: 1;
  vertical-align: top;
}

.xr-preview {
  color: var(--xr-font-color3);
}

.xr-array-preview,
.xr-array-data {
  padding: 0 5px !important;
  grid-column: 2;
}

.xr-array-data,
.xr-array-in:checked ~ .xr-array-preview {
  display: none;
}

.xr-array-in:checked ~ .xr-array-data,
.xr-array-preview {
  display: inline-block;
}

.xr-dim-list {
  display: inline-block !important;
  list-style: none;
  padding: 0 !important;
  margin: 0;
}

.xr-dim-list li {
  display: inline-block;
  padding: 0;
  margin: 0;
}

.xr-dim-list:before {
  content: '(';
}

.xr-dim-list:after {
  content: ')';
}

.xr-dim-list li:not(:last-child):after {
  content: ',';
  padding-right: 5px;
}

.xr-has-index {
  font-weight: bold;
}

.xr-var-list,
.xr-var-item {
  display: contents;
}

.xr-var-item > div,
.xr-var-item label,
.xr-var-item > .xr-var-name span {
  background-color: var(--xr-background-color-row-even);
  margin-bottom: 0;
}

.xr-var-item > .xr-var-name:hover span {
  padding-right: 5px;
}

.xr-var-list > li:nth-child(odd) > div,
.xr-var-list > li:nth-child(odd) > label,
.xr-var-list > li:nth-child(odd) > .xr-var-name span {
  background-color: var(--xr-background-color-row-odd);
}

.xr-var-name {
  grid-column: 1;
}

.xr-var-dims {
  grid-column: 2;
}

.xr-var-dtype {
  grid-column: 3;
  text-align: right;
  color: var(--xr-font-color2);
}

.xr-var-preview {
  grid-column: 4;
}

.xr-var-name,
.xr-var-dims,
.xr-var-dtype,
.xr-preview,
.xr-attrs dt {
  white-space: nowrap;
  overflow: hidden;
  text-overflow: ellipsis;
  padding-right: 10px;
}

.xr-var-name:hover,
.xr-var-dims:hover,
.xr-var-dtype:hover,
.xr-attrs dt:hover {
  overflow: visible;
  width: auto;
  z-index: 1;
}

.xr-var-attrs,
.xr-var-data {
  display: none;
  background-color: var(--xr-background-color) !important;
  padding-bottom: 5px !important;
}

.xr-var-attrs-in:checked ~ .xr-var-attrs,
.xr-var-data-in:checked ~ .xr-var-data {
  display: block;
}

.xr-var-data > table {
  float: right;
}

.xr-var-name span,
.xr-var-data,
.xr-attrs {
  padding-left: 25px !important;
}

.xr-attrs,
.xr-var-attrs,
.xr-var-data {
  grid-column: 1 / -1;
}

dl.xr-attrs {
  padding: 0;
  margin: 0;
  display: grid;
  grid-template-columns: 125px auto;
}

.xr-attrs dt,
.xr-attrs dd {
  padding: 0;
  margin: 0;
  float: left;
  padding-right: 10px;
  width: auto;
}

.xr-attrs dt {
  font-weight: normal;
  grid-column: 1;
}

.xr-attrs dt:hover span {
  display: inline-block;
  background: var(--xr-background-color);
  padding-right: 10px;
}

.xr-attrs dd {
  grid-column: 2;
  white-space: pre-wrap;
  word-break: break-all;
}

.xr-icon-database,
.xr-icon-file-text2 {
  display: inline-block;
  vertical-align: middle;
  width: 1em;
  height: 1.5em !important;
  stroke-width: 0;
  stroke: currentColor;
  fill: currentColor;
}
</style><pre class="xr-text-repr-fallback">&lt;xarray.Dataset&gt;
Dimensions:                (segment: 235584)
Dimensions without coordinates: segment
Data variables:
    latitude               (segment) float64 82.38 82.38 82.38 ... 72.61 72.61
    longitude              (segment) float64 -55.11 -55.11 ... 145.1 145.1
    delta_time             (segment) float64 4.642e+07 4.642e+07 ... 4.642e+07
    height_segment_height  (segment) float32 nan nan nan ... -0.4335 -0.4463</pre><div class="xr-wrap" hidden=""><div class="xr-header"><div class="xr-obj-type">xarray.Dataset</div></div><ul class="xr-sections"><li class="xr-section-item"><input id="section-dec7d581-d0a1-41bb-b815-85401133972e" class="xr-section-summary-in" type="checkbox" disabled=""><label for="section-dec7d581-d0a1-41bb-b815-85401133972e" class="xr-section-summary" title="Expand/collapse section">Dimensions:</label><div class="xr-section-inline-details"><ul class="xr-dim-list"><li><span>segment</span>: 235584</li></ul></div><div class="xr-section-details"></div></li><li class="xr-section-item"><input id="section-6acf333d-17ac-4c00-be54-8c856da5c8aa" class="xr-section-summary-in" type="checkbox" disabled=""><label for="section-6acf333d-17ac-4c00-be54-8c856da5c8aa" class="xr-section-summary" title="Expand/collapse section">Coordinates: <span>(0)</span></label><div class="xr-section-inline-details"></div><div class="xr-section-details"><ul class="xr-var-list"></ul></div></li><li class="xr-section-item"><input id="section-5bd03019-a376-43e3-b0ff-5a5bd3d1544b" class="xr-section-summary-in" type="checkbox" checked=""><label for="section-5bd03019-a376-43e3-b0ff-5a5bd3d1544b" class="xr-section-summary">Data variables: <span>(4)</span></label><div class="xr-section-inline-details"></div><div class="xr-section-details"><ul class="xr-var-list"><li class="xr-var-item"><div class="xr-var-name"><span>latitude</span></div><div class="xr-var-dims">(segment)</div><div class="xr-var-dtype">float64</div><div class="xr-var-preview xr-preview">82.38 82.38 82.38 ... 72.61 72.61</div><input id="attrs-435f9890-ec6c-4abc-9998-88e2d34f77b7" class="xr-var-attrs-in" type="checkbox"><label for="attrs-435f9890-ec6c-4abc-9998-88e2d34f77b7" title="Show/Hide attributes"><svg class="icon xr-icon-file-text2"><use href="#icon-file-text2"></use></svg></label><input id="data-804fb402-dd71-47d2-a815-a5bd10c1a6d5" class="xr-var-data-in" type="checkbox"><label for="data-804fb402-dd71-47d2-a815-a5bd10c1a6d5" title="Show/Hide data repr"><svg class="icon xr-icon-database"><use href="#icon-database"></use></svg></label><div class="xr-var-attrs"><dl class="xr-attrs"><dt><span>contentType :</span></dt><dd>referenceInformation</dd><dt><span>coordinates :</span></dt><dd>delta_time longitude</dd><dt><span>description :</span></dt><dd>Latitude, WGS84, North=+, Lat of segment center</dd><dt><span>long_name :</span></dt><dd>Latitude</dd><dt><span>source :</span></dt><dd>ATBD, section 4.4</dd><dt><span>standard_name :</span></dt><dd>latitude</dd><dt><span>units :</span></dt><dd>degrees_north</dd><dt><span>valid_max :</span></dt><dd>90.0</dd><dt><span>valid_min :</span></dt><dd>-90.0</dd></dl></div><div class="xr-var-data"><pre>array([82.38431982, 82.38431982, 82.38431982, ..., 72.60984638,
       72.60977493, 72.60970985])</pre></div></li><li class="xr-var-item"><div class="xr-var-name"><span>longitude</span></div><div class="xr-var-dims">(segment)</div><div class="xr-var-dtype">float64</div><div class="xr-var-preview xr-preview">-55.11 -55.11 ... 145.1 145.1</div><input id="attrs-1e1280e6-0885-4acd-879d-aab2e466b902" class="xr-var-attrs-in" type="checkbox"><label for="attrs-1e1280e6-0885-4acd-879d-aab2e466b902" title="Show/Hide attributes"><svg class="icon xr-icon-file-text2"><use href="#icon-file-text2"></use></svg></label><input id="data-fe83c840-4be7-4213-adb6-5df291f01f9c" class="xr-var-data-in" type="checkbox"><label for="data-fe83c840-4be7-4213-adb6-5df291f01f9c" title="Show/Hide data repr"><svg class="icon xr-icon-database"><use href="#icon-database"></use></svg></label><div class="xr-var-attrs"><dl class="xr-attrs"><dt><span>contentType :</span></dt><dd>referenceInformation</dd><dt><span>coordinates :</span></dt><dd>delta_time latitude</dd><dt><span>description :</span></dt><dd>Longitude, WGS84, East=+,Lon of segment center</dd><dt><span>long_name :</span></dt><dd>Longitude</dd><dt><span>source :</span></dt><dd>ATBD, section 4.4</dd><dt><span>standard_name :</span></dt><dd>longitude</dd><dt><span>units :</span></dt><dd>degrees_east</dd><dt><span>valid_max :</span></dt><dd>180.0</dd><dt><span>valid_min :</span></dt><dd>-180.0</dd></dl></div><div class="xr-var-data"><pre>array([-55.10896068, -55.10896068, -55.10896068, ..., 145.05396164,
       145.05392851, 145.05389832])</pre></div></li><li class="xr-var-item"><div class="xr-var-name"><span>delta_time</span></div><div class="xr-var-dims">(segment)</div><div class="xr-var-dtype">float64</div><div class="xr-var-preview xr-preview">4.642e+07 4.642e+07 ... 4.642e+07</div><input id="attrs-af57142a-1fdc-481f-a59d-c40618c5aef9" class="xr-var-attrs-in" type="checkbox"><label for="attrs-af57142a-1fdc-481f-a59d-c40618c5aef9" title="Show/Hide attributes"><svg class="icon xr-icon-file-text2"><use href="#icon-file-text2"></use></svg></label><input id="data-680306d7-3be6-4d71-8bee-e5838b45f5e3" class="xr-var-data-in" type="checkbox"><label for="data-680306d7-3be6-4d71-8bee-e5838b45f5e3" title="Show/Hide data repr"><svg class="icon xr-icon-database"><use href="#icon-database"></use></svg></label><div class="xr-var-attrs"><dl class="xr-attrs"><dt><span>CLASS :</span></dt><dd>DIMENSION_SCALE</dd><dt><span>NAME :</span></dt><dd>gt1l/sea_ice_segments/delta_time</dd><dt><span>REFERENCE_LIST :</span></dt><dd>[(&lt;HDF5 object reference&gt;, 0) (&lt;HDF5 object reference&gt;, 0)
 (&lt;HDF5 object reference&gt;, 0) (&lt;HDF5 object reference&gt;, 0)
 (&lt;HDF5 object reference&gt;, 0) (&lt;HDF5 object reference&gt;, 0)
 (&lt;HDF5 object reference&gt;, 0) (&lt;HDF5 object reference&gt;, 0)
 (&lt;HDF5 object reference&gt;, 0) (&lt;HDF5 object reference&gt;, 0)
 (&lt;HDF5 object reference&gt;, 0) (&lt;HDF5 object reference&gt;, 0)
 (&lt;HDF5 object reference&gt;, 0) (&lt;HDF5 object reference&gt;, 0)
 (&lt;HDF5 object reference&gt;, 0) (&lt;HDF5 object reference&gt;, 0)
 (&lt;HDF5 object reference&gt;, 0) (&lt;HDF5 object reference&gt;, 0)
 (&lt;HDF5 object reference&gt;, 0) (&lt;HDF5 object reference&gt;, 0)
 (&lt;HDF5 object reference&gt;, 0) (&lt;HDF5 object reference&gt;, 0)
 (&lt;HDF5 object reference&gt;, 0) (&lt;HDF5 object reference&gt;, 0)
 (&lt;HDF5 object reference&gt;, 0) (&lt;HDF5 object reference&gt;, 0)
 (&lt;HDF5 object reference&gt;, 0) (&lt;HDF5 object reference&gt;, 0)
 (&lt;HDF5 object reference&gt;, 0) (&lt;HDF5 object reference&gt;, 0)
 (&lt;HDF5 object reference&gt;, 0) (&lt;HDF5 object reference&gt;, 0)
 (&lt;HDF5 object reference&gt;, 0) (&lt;HDF5 object reference&gt;, 0)
 (&lt;HDF5 object reference&gt;, 0) (&lt;HDF5 object reference&gt;, 0)
 (&lt;HDF5 object reference&gt;, 0) (&lt;HDF5 object reference&gt;, 0)
 (&lt;HDF5 object reference&gt;, 0) (&lt;HDF5 object reference&gt;, 0)
 (&lt;HDF5 object reference&gt;, 0) (&lt;HDF5 object reference&gt;, 0)
 (&lt;HDF5 object reference&gt;, 0) (&lt;HDF5 object reference&gt;, 0)
 (&lt;HDF5 object reference&gt;, 0) (&lt;HDF5 object reference&gt;, 0)
 (&lt;HDF5 object reference&gt;, 0) (&lt;HDF5 object reference&gt;, 0)
 (&lt;HDF5 object reference&gt;, 0) (&lt;HDF5 object reference&gt;, 0)
 (&lt;HDF5 object reference&gt;, 0) (&lt;HDF5 object reference&gt;, 0)
 (&lt;HDF5 object reference&gt;, 0) (&lt;HDF5 object reference&gt;, 0)
 (&lt;HDF5 object reference&gt;, 0) (&lt;HDF5 object reference&gt;, 0)
 (&lt;HDF5 object reference&gt;, 0) (&lt;HDF5 object reference&gt;, 0)
 (&lt;HDF5 object reference&gt;, 0) (&lt;HDF5 object reference&gt;, 0)
 (&lt;HDF5 object reference&gt;, 0) (&lt;HDF5 object reference&gt;, 0)
 (&lt;HDF5 object reference&gt;, 0) (&lt;HDF5 object reference&gt;, 0)
 (&lt;HDF5 object reference&gt;, 0) (&lt;HDF5 object reference&gt;, 0)
 (&lt;HDF5 object reference&gt;, 0) (&lt;HDF5 object reference&gt;, 0)
 (&lt;HDF5 object reference&gt;, 0) (&lt;HDF5 object reference&gt;, 0)
 (&lt;HDF5 object reference&gt;, 0) (&lt;HDF5 object reference&gt;, 0)
 (&lt;HDF5 object reference&gt;, 0) (&lt;HDF5 object reference&gt;, 0)
 (&lt;HDF5 object reference&gt;, 0) (&lt;HDF5 object reference&gt;, 0)
 (&lt;HDF5 object reference&gt;, 0) (&lt;HDF5 object reference&gt;, 0)
 (&lt;HDF5 object reference&gt;, 0) (&lt;HDF5 object reference&gt;, 0)
 (&lt;HDF5 object reference&gt;, 0) (&lt;HDF5 object reference&gt;, 0)
 (&lt;HDF5 object reference&gt;, 0) (&lt;HDF5 object reference&gt;, 0)]</dd><dt><span>contentType :</span></dt><dd>physicalMeasurement</dd><dt><span>coordinates :</span></dt><dd>latitude longitude</dd><dt><span>description :</span></dt><dd>Number of GPS seconds since the ATLAS SDP epoch. The ATLAS Standard Data Products (SDP) epoch offset is defined within /ancillary_data/atlas_sdp_gps_epoch as the number of GPS seconds between the GPS epoch (1980-01-06T00:00:00.000000Z UTC) and the ATLAS SDP epoch. By adding the offset contained within atlas_sdp_gps_epoch to delta time parameters, the time in gps_seconds relative to the GPS epoch can be computed.</dd><dt><span>long_name :</span></dt><dd>Elapsed GPS seconds</dd><dt><span>source :</span></dt><dd>telemetry</dd><dt><span>standard_name :</span></dt><dd>time</dd><dt><span>units :</span></dt><dd>seconds since 2018-01-01</dd></dl></div><div class="xr-var-data"><pre>array([46419293.64266939, 46419293.64266939, 46419293.64266939, ...,
       46419681.87646231, 46419681.87759533, 46419681.87862704])</pre></div></li><li class="xr-var-item"><div class="xr-var-name"><span>height_segment_height</span></div><div class="xr-var-dims">(segment)</div><div class="xr-var-dtype">float32</div><div class="xr-var-preview xr-preview">nan nan nan ... -0.4335 -0.4463</div><input id="attrs-ca84d809-c180-48cf-a3be-be33f173ab6b" class="xr-var-attrs-in" type="checkbox"><label for="attrs-ca84d809-c180-48cf-a3be-be33f173ab6b" title="Show/Hide attributes"><svg class="icon xr-icon-file-text2"><use href="#icon-file-text2"></use></svg></label><input id="data-4d8bf861-8b9b-4d97-af54-8d9195553513" class="xr-var-data-in" type="checkbox"><label for="data-4d8bf861-8b9b-4d97-af54-8d9195553513" title="Show/Hide data repr"><svg class="icon xr-icon-database"><use href="#icon-database"></use></svg></label><div class="xr-var-attrs"><dl class="xr-attrs"><dt><span>_FillValue :</span></dt><dd>3.4028235e+38</dd><dt><span>contentType :</span></dt><dd>referenceInformation</dd><dt><span>coordinates :</span></dt><dd>../delta_time ../latitude ../longitude</dd><dt><span>description :</span></dt><dd>Mean height from along-track segment fit detremined by the sea ice algorithm. The sea ice height is relative to the tide-free MSS.</dd><dt><span>long_name :</span></dt><dd>height of segment surface</dd><dt><span>source :</span></dt><dd>ATBD, section 4.2.2.4</dd><dt><span>units :</span></dt><dd>meters</dd></dl></div><div class="xr-var-data"><pre>array([        nan,         nan,         nan, ..., -0.46550068,
       -0.43347716, -0.4462675 ], dtype=float32)</pre></div></li></ul></div></li><li class="xr-section-item"><input id="section-0289a675-9517-4e8e-96be-d84ef992250b" class="xr-section-summary-in" type="checkbox" disabled=""><label for="section-0289a675-9517-4e8e-96be-d84ef992250b" class="xr-section-summary" title="Expand/collapse section">Attributes: <span>(0)</span></label><div class="xr-section-inline-details"></div><div class="xr-section-details"><dl class="xr-attrs"></dl></div></li></ul></div></div>
</div>
</div>
<div class="cell" data-execution_count="14">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a>is2_ds.height_segment_height.plot() <span class="op">;</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<p><img src="04_On-Prem_Cloud_files/figure-html/cell-15-output-1.png" class="img-fluid"></p>
</div>
</div>
</section>
</section>
<section id="determine-the-ghrsst-modis-l2-granules-returned-from-our-time-and-area-of-interest" class="level2">
<h2 class="anchored" data-anchor-id="determine-the-ghrsst-modis-l2-granules-returned-from-our-time-and-area-of-interest">Determine the GHRSST MODIS L2 granules returned from our time and area of interest</h2>
<div class="cell" data-execution_count="15">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a>response <span class="op">=</span> requests.get(granule_url, </span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a>                        params<span class="op">=</span>{</span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a>                            <span class="st">'concept_id'</span>: modis_concept_id,</span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a>                            <span class="st">'temporal'</span>: temporal,</span>
<span id="cb18-5"><a href="#cb18-5" aria-hidden="true" tabindex="-1"></a>                            <span class="st">'bounding_box'</span>: bounding_box,</span>
<span id="cb18-6"><a href="#cb18-6" aria-hidden="true" tabindex="-1"></a>                            <span class="st">'page_size'</span>: <span class="dv">200</span>,</span>
<span id="cb18-7"><a href="#cb18-7" aria-hidden="true" tabindex="-1"></a>                            },</span>
<span id="cb18-8"><a href="#cb18-8" aria-hidden="true" tabindex="-1"></a>                        headers<span class="op">=</span>{</span>
<span id="cb18-9"><a href="#cb18-9" aria-hidden="true" tabindex="-1"></a>                            <span class="st">'Accept'</span>: <span class="st">'application/json'</span></span>
<span id="cb18-10"><a href="#cb18-10" aria-hidden="true" tabindex="-1"></a>                            }</span>
<span id="cb18-11"><a href="#cb18-11" aria-hidden="true" tabindex="-1"></a>                       )</span>
<span id="cb18-12"><a href="#cb18-12" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(response.headers[<span class="st">'CMR-Hits'</span>])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>14</code></pre>
</div>
</div>
<div class="cell" data-execution_count="16">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a>granules <span class="op">=</span> response.json()[<span class="st">'feed'</span>][<span class="st">'entry'</span>]</span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> granule <span class="kw">in</span> granules:</span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="ss">f'</span><span class="sc">{</span>granule[<span class="st">"title"</span>]<span class="sc">}</span><span class="ss"> </span><span class="sc">{</span>granule[<span class="st">"granule_size"</span>]<span class="sc">}</span><span class="ss"> </span><span class="sc">{</span>granule[<span class="st">"links"</span>][<span class="dv">0</span>][<span class="st">"href"</span>]<span class="sc">}</span><span class="ss">'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>20190622000501-JPL-L2P_GHRSST-SSTskin-MODIS_A-D-v02.0-fv01.0 20.71552562713623 s3://podaac-ops-cumulus-protected/MODIS_A-JPL-L2P-v2019.0/20190622000501-JPL-L2P_GHRSST-SSTskin-MODIS_A-D-v02.0-fv01.0.nc
20190622014501-JPL-L2P_GHRSST-SSTskin-MODIS_A-D-v02.0-fv01.0 9.34600830078125E-5 s3://podaac-ops-cumulus-protected/MODIS_A-JPL-L2P-v2019.0/20190622014501-JPL-L2P_GHRSST-SSTskin-MODIS_A-D-v02.0-fv01.0.nc
20190622032501-JPL-L2P_GHRSST-SSTskin-MODIS_A-D-v02.0-fv01.0 21.307741165161133 s3://podaac-ops-cumulus-protected/MODIS_A-JPL-L2P-v2019.0/20190622032501-JPL-L2P_GHRSST-SSTskin-MODIS_A-D-v02.0-fv01.0.nc
20190622050001-JPL-L2P_GHRSST-SSTskin-MODIS_A-D-v02.0-fv01.0 9.34600830078125E-5 s3://podaac-ops-cumulus-protected/MODIS_A-JPL-L2P-v2019.0/20190622050001-JPL-L2P_GHRSST-SSTskin-MODIS_A-D-v02.0-fv01.0.nc
20190622050501-JPL-L2P_GHRSST-SSTskin-MODIS_A-D-v02.0-fv01.0 20.065649032592773 s3://podaac-ops-cumulus-protected/MODIS_A-JPL-L2P-v2019.0/20190622050501-JPL-L2P_GHRSST-SSTskin-MODIS_A-D-v02.0-fv01.0.nc
20190622064001-JPL-L2P_GHRSST-SSTskin-MODIS_A-D-v02.0-fv01.0 9.34600830078125E-5 s3://podaac-ops-cumulus-protected/MODIS_A-JPL-L2P-v2019.0/20190622064001-JPL-L2P_GHRSST-SSTskin-MODIS_A-D-v02.0-fv01.0.nc
20190622064501-JPL-L2P_GHRSST-SSTskin-MODIS_A-N-v02.0-fv01.0 18.602201461791992 s3://podaac-ops-cumulus-protected/MODIS_A-JPL-L2P-v2019.0/20190622064501-JPL-L2P_GHRSST-SSTskin-MODIS_A-N-v02.0-fv01.0.nc
20190622064501-JPL-L2P_GHRSST-SSTskin-MODIS_A-D-v02.0-fv01.0 18.665077209472656 s3://podaac-ops-cumulus-protected/MODIS_A-JPL-L2P-v2019.0/20190622064501-JPL-L2P_GHRSST-SSTskin-MODIS_A-D-v02.0-fv01.0.nc
20190622082001-JPL-L2P_GHRSST-SSTskin-MODIS_A-D-v02.0-fv01.0 19.782299995422363 s3://podaac-ops-cumulus-protected/MODIS_A-JPL-L2P-v2019.0/20190622082001-JPL-L2P_GHRSST-SSTskin-MODIS_A-D-v02.0-fv01.0.nc
20190622100001-JPL-L2P_GHRSST-SSTskin-MODIS_A-D-v02.0-fv01.0 19.13440227508545 s3://podaac-ops-cumulus-protected/MODIS_A-JPL-L2P-v2019.0/20190622100001-JPL-L2P_GHRSST-SSTskin-MODIS_A-D-v02.0-fv01.0.nc
20190622113501-JPL-L2P_GHRSST-SSTskin-MODIS_A-D-v02.0-fv01.0 20.3239164352417 s3://podaac-ops-cumulus-protected/MODIS_A-JPL-L2P-v2019.0/20190622113501-JPL-L2P_GHRSST-SSTskin-MODIS_A-D-v02.0-fv01.0.nc
20190622114001-JPL-L2P_GHRSST-SSTskin-MODIS_A-D-v02.0-fv01.0 9.34600830078125E-5 s3://podaac-ops-cumulus-protected/MODIS_A-JPL-L2P-v2019.0/20190622114001-JPL-L2P_GHRSST-SSTskin-MODIS_A-D-v02.0-fv01.0.nc
20190622163001-JPL-L2P_GHRSST-SSTskin-MODIS_A-D-v02.0-fv01.0 19.257243156433105 s3://podaac-ops-cumulus-protected/MODIS_A-JPL-L2P-v2019.0/20190622163001-JPL-L2P_GHRSST-SSTskin-MODIS_A-D-v02.0-fv01.0.nc
20190622181001-JPL-L2P_GHRSST-SSTskin-MODIS_A-D-v02.0-fv01.0 19.93498420715332 s3://podaac-ops-cumulus-protected/MODIS_A-JPL-L2P-v2019.0/20190622181001-JPL-L2P_GHRSST-SSTskin-MODIS_A-D-v02.0-fv01.0.nc</code></pre>
</div>
</div>
</section>
<section id="load-data-into-xarray-via-s3-direct-access" class="level2">
<h2 class="anchored" data-anchor-id="load-data-into-xarray-via-s3-direct-access">Load data into xarray via S3 direct access</h2>
<p>Our CMR granule search returned 14 files for our time and area of interest. However, not all granules will be suitable for analysis.</p>
<p>I’ve identified the image with granule id G1956158784-POCLOUD as a good candidate, this is the 9th granule. In this image, our area of interest is close to nadir. This means that the instantaneous field of view over the area of interest cover a smaller area than at the edge of the image.</p>
<p>We are looking for the link for <em>direct download access via s3</em>. This is a url but with a prefix <code>s3://</code>. This happens to be the first href link in the metadata.</p>
<p>For a single granule we can cut and paste the s3 link. If we have several granules, the s3 links can be extracted with some simple code.</p>
<div class="cell" data-execution_count="17">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a>granule <span class="op">=</span> granules[<span class="dv">9</span>]</span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> link <span class="kw">in</span> granule[<span class="st">'links'</span>]:</span>
<span id="cb22-4"><a href="#cb22-4" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> link[<span class="st">'href'</span>].startswith(<span class="st">'s3://'</span>):</span>
<span id="cb22-5"><a href="#cb22-5" aria-hidden="true" tabindex="-1"></a>        s3_link <span class="op">=</span> link[<span class="st">'href'</span>]</span>
<span id="cb22-6"><a href="#cb22-6" aria-hidden="true" tabindex="-1"></a>        </span>
<span id="cb22-7"><a href="#cb22-7" aria-hidden="true" tabindex="-1"></a>s3_link</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="17">
<pre><code>'s3://podaac-ops-cumulus-protected/MODIS_A-JPL-L2P-v2019.0/20190622100001-JPL-L2P_GHRSST-SSTskin-MODIS_A-D-v02.0-fv01.0.nc'</code></pre>
</div>
</div>
<section id="get-s3-credentials" class="level3">
<h3 class="anchored" data-anchor-id="get-s3-credentials">Get S3 credentials</h3>
<p>As with the previous S3 download tutorials we need credentials to access data from s3: access keys and tokens.</p>
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a>s3_credentials <span class="op">=</span> requests.get(<span class="st">'https://archive.podaac.earthdata.nasa.gov/s3credentials'</span>).json()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>Essentially, what we are doing in this step is to “mount” the s3 bucket as a file system. This allows us to treat the S3 bucket in a similar way to a local file system.</p>
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a>s3_fs <span class="op">=</span> s3fs.S3FileSystem(</span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a>    key<span class="op">=</span>s3_credentials[<span class="st">"accessKeyId"</span>],</span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a>    secret<span class="op">=</span>s3_credentials[<span class="st">"secretAccessKey"</span>],</span>
<span id="cb25-4"><a href="#cb25-4" aria-hidden="true" tabindex="-1"></a>    token<span class="op">=</span>s3_credentials[<span class="st">"sessionToken"</span>],</span>
<span id="cb25-5"><a href="#cb25-5" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</section>
<section id="open-a-s3-file" class="level3">
<h3 class="anchored" data-anchor-id="open-a-s3-file">Open a s3 file</h3>
<p>Now we have the <code>S3FileSystem</code> set up, we can access the granule. <code>xarray</code> cannot open a <code>S3File</code> directly, so we use the <code>open</code> method for the <code>S3FileSystem</code> to open the granule using the endpoint url we extracted from the metadata. We also have to set the <code>mode='rb'</code>. This opens the granule in read-only mode and in byte-mode. Byte-mode is important. By default, <code>open</code> opens a file as text - in this case it would just be a string of characters - and <code>xarray</code> doesn’t know what to do with that.</p>
<p>We then pass the <code>S3File</code> object <code>f</code> to <code>xarray.open_dataset</code>. For this dataset, we also have to set <code>decode_cf=False</code>. This switch tells <code>xarray</code> not to use information contained in variable attributes to generate human readable coordinate variables. Normally, this should work for netcdf files but for this particular cloud-hosted dataset, variable attribute data is not in the form expected by <code>xarray</code>. We’ll fix this.</p>
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a>f <span class="op">=</span> s3_fs.<span class="bu">open</span>(s3_link, mode<span class="op">=</span><span class="st">'rb'</span>)</span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a>modis_ds <span class="op">=</span> xr.open_dataset(f, decode_cf<span class="op">=</span><span class="va">False</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>If you click on the <code>Show/Hide Attributes</code> icon (the first document-like icon to the right of coordinate variable metadata) you can see that attributes are one-element arrays containing bytestrings.</p>
<div class="cell" data-execution_count="21">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a>modis_ds</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="21">

<div><svg style="position: absolute; width: 0; height: 0; overflow: hidden">
<defs>
<symbol id="icon-database" viewbox="0 0 32 32">
<path d="M16 0c-8.837 0-16 2.239-16 5v4c0 2.761 7.163 5 16 5s16-2.239 16-5v-4c0-2.761-7.163-5-16-5z"></path>
<path d="M16 17c-8.837 0-16-2.239-16-5v6c0 2.761 7.163 5 16 5s16-2.239 16-5v-6c0 2.761-7.163 5-16 5z"></path>
<path d="M16 26c-8.837 0-16-2.239-16-5v6c0 2.761 7.163 5 16 5s16-2.239 16-5v-6c0 2.761-7.163 5-16 5z"></path>
</symbol>
<symbol id="icon-file-text2" viewbox="0 0 32 32">
<path d="M28.681 7.159c-0.694-0.947-1.662-2.053-2.724-3.116s-2.169-2.030-3.116-2.724c-1.612-1.182-2.393-1.319-2.841-1.319h-15.5c-1.378 0-2.5 1.121-2.5 2.5v27c0 1.378 1.122 2.5 2.5 2.5h23c1.378 0 2.5-1.122 2.5-2.5v-19.5c0-0.448-0.137-1.23-1.319-2.841zM24.543 5.457c0.959 0.959 1.712 1.825 2.268 2.543h-4.811v-4.811c0.718 0.556 1.584 1.309 2.543 2.268zM28 29.5c0 0.271-0.229 0.5-0.5 0.5h-23c-0.271 0-0.5-0.229-0.5-0.5v-27c0-0.271 0.229-0.5 0.5-0.5 0 0 15.499-0 15.5 0v7c0 0.552 0.448 1 1 1h7v19.5z"></path>
<path d="M23 26h-14c-0.552 0-1-0.448-1-1s0.448-1 1-1h14c0.552 0 1 0.448 1 1s-0.448 1-1 1z"></path>
<path d="M23 22h-14c-0.552 0-1-0.448-1-1s0.448-1 1-1h14c0.552 0 1 0.448 1 1s-0.448 1-1 1z"></path>
<path d="M23 18h-14c-0.552 0-1-0.448-1-1s0.448-1 1-1h14c0.552 0 1 0.448 1 1s-0.448 1-1 1z"></path>
</symbol>
</defs>
</svg>
<style>/* CSS stylesheet for displaying xarray objects in jupyterlab.
 *
 */

:root {
  --xr-font-color0: var(--jp-content-font-color0, rgba(0, 0, 0, 1));
  --xr-font-color2: var(--jp-content-font-color2, rgba(0, 0, 0, 0.54));
  --xr-font-color3: var(--jp-content-font-color3, rgba(0, 0, 0, 0.38));
  --xr-border-color: var(--jp-border-color2, #e0e0e0);
  --xr-disabled-color: var(--jp-layout-color3, #bdbdbd);
  --xr-background-color: var(--jp-layout-color0, white);
  --xr-background-color-row-even: var(--jp-layout-color1, white);
  --xr-background-color-row-odd: var(--jp-layout-color2, #eeeeee);
}

html[theme=dark],
body.vscode-dark {
  --xr-font-color0: rgba(255, 255, 255, 1);
  --xr-font-color2: rgba(255, 255, 255, 0.54);
  --xr-font-color3: rgba(255, 255, 255, 0.38);
  --xr-border-color: #1F1F1F;
  --xr-disabled-color: #515151;
  --xr-background-color: #111111;
  --xr-background-color-row-even: #111111;
  --xr-background-color-row-odd: #313131;
}

.xr-wrap {
  display: block;
  min-width: 300px;
  max-width: 700px;
}

.xr-text-repr-fallback {
  /* fallback to plain text repr when CSS is not injected (untrusted notebook) */
  display: none;
}

.xr-header {
  padding-top: 6px;
  padding-bottom: 6px;
  margin-bottom: 4px;
  border-bottom: solid 1px var(--xr-border-color);
}

.xr-header > div,
.xr-header > ul {
  display: inline;
  margin-top: 0;
  margin-bottom: 0;
}

.xr-obj-type,
.xr-array-name {
  margin-left: 2px;
  margin-right: 10px;
}

.xr-obj-type {
  color: var(--xr-font-color2);
}

.xr-sections {
  padding-left: 0 !important;
  display: grid;
  grid-template-columns: 150px auto auto 1fr 20px 20px;
}

.xr-section-item {
  display: contents;
}

.xr-section-item input {
  display: none;
}

.xr-section-item input + label {
  color: var(--xr-disabled-color);
}

.xr-section-item input:enabled + label {
  cursor: pointer;
  color: var(--xr-font-color2);
}

.xr-section-item input:enabled + label:hover {
  color: var(--xr-font-color0);
}

.xr-section-summary {
  grid-column: 1;
  color: var(--xr-font-color2);
  font-weight: 500;
}

.xr-section-summary > span {
  display: inline-block;
  padding-left: 0.5em;
}

.xr-section-summary-in:disabled + label {
  color: var(--xr-font-color2);
}

.xr-section-summary-in + label:before {
  display: inline-block;
  content: '►';
  font-size: 11px;
  width: 15px;
  text-align: center;
}

.xr-section-summary-in:disabled + label:before {
  color: var(--xr-disabled-color);
}

.xr-section-summary-in:checked + label:before {
  content: '▼';
}

.xr-section-summary-in:checked + label > span {
  display: none;
}

.xr-section-summary,
.xr-section-inline-details {
  padding-top: 4px;
  padding-bottom: 4px;
}

.xr-section-inline-details {
  grid-column: 2 / -1;
}

.xr-section-details {
  display: none;
  grid-column: 1 / -1;
  margin-bottom: 5px;
}

.xr-section-summary-in:checked ~ .xr-section-details {
  display: contents;
}

.xr-array-wrap {
  grid-column: 1 / -1;
  display: grid;
  grid-template-columns: 20px auto;
}

.xr-array-wrap > label {
  grid-column: 1;
  vertical-align: top;
}

.xr-preview {
  color: var(--xr-font-color3);
}

.xr-array-preview,
.xr-array-data {
  padding: 0 5px !important;
  grid-column: 2;
}

.xr-array-data,
.xr-array-in:checked ~ .xr-array-preview {
  display: none;
}

.xr-array-in:checked ~ .xr-array-data,
.xr-array-preview {
  display: inline-block;
}

.xr-dim-list {
  display: inline-block !important;
  list-style: none;
  padding: 0 !important;
  margin: 0;
}

.xr-dim-list li {
  display: inline-block;
  padding: 0;
  margin: 0;
}

.xr-dim-list:before {
  content: '(';
}

.xr-dim-list:after {
  content: ')';
}

.xr-dim-list li:not(:last-child):after {
  content: ',';
  padding-right: 5px;
}

.xr-has-index {
  font-weight: bold;
}

.xr-var-list,
.xr-var-item {
  display: contents;
}

.xr-var-item > div,
.xr-var-item label,
.xr-var-item > .xr-var-name span {
  background-color: var(--xr-background-color-row-even);
  margin-bottom: 0;
}

.xr-var-item > .xr-var-name:hover span {
  padding-right: 5px;
}

.xr-var-list > li:nth-child(odd) > div,
.xr-var-list > li:nth-child(odd) > label,
.xr-var-list > li:nth-child(odd) > .xr-var-name span {
  background-color: var(--xr-background-color-row-odd);
}

.xr-var-name {
  grid-column: 1;
}

.xr-var-dims {
  grid-column: 2;
}

.xr-var-dtype {
  grid-column: 3;
  text-align: right;
  color: var(--xr-font-color2);
}

.xr-var-preview {
  grid-column: 4;
}

.xr-var-name,
.xr-var-dims,
.xr-var-dtype,
.xr-preview,
.xr-attrs dt {
  white-space: nowrap;
  overflow: hidden;
  text-overflow: ellipsis;
  padding-right: 10px;
}

.xr-var-name:hover,
.xr-var-dims:hover,
.xr-var-dtype:hover,
.xr-attrs dt:hover {
  overflow: visible;
  width: auto;
  z-index: 1;
}

.xr-var-attrs,
.xr-var-data {
  display: none;
  background-color: var(--xr-background-color) !important;
  padding-bottom: 5px !important;
}

.xr-var-attrs-in:checked ~ .xr-var-attrs,
.xr-var-data-in:checked ~ .xr-var-data {
  display: block;
}

.xr-var-data > table {
  float: right;
}

.xr-var-name span,
.xr-var-data,
.xr-attrs {
  padding-left: 25px !important;
}

.xr-attrs,
.xr-var-attrs,
.xr-var-data {
  grid-column: 1 / -1;
}

dl.xr-attrs {
  padding: 0;
  margin: 0;
  display: grid;
  grid-template-columns: 125px auto;
}

.xr-attrs dt,
.xr-attrs dd {
  padding: 0;
  margin: 0;
  float: left;
  padding-right: 10px;
  width: auto;
}

.xr-attrs dt {
  font-weight: normal;
  grid-column: 1;
}

.xr-attrs dt:hover span {
  display: inline-block;
  background: var(--xr-background-color);
  padding-right: 10px;
}

.xr-attrs dd {
  grid-column: 2;
  white-space: pre-wrap;
  word-break: break-all;
}

.xr-icon-database,
.xr-icon-file-text2 {
  display: inline-block;
  vertical-align: middle;
  width: 1em;
  height: 1.5em !important;
  stroke-width: 0;
  stroke: currentColor;
  fill: currentColor;
}
</style><pre class="xr-text-repr-fallback">&lt;xarray.Dataset&gt;
Dimensions:                  (nj: 2030, ni: 1354, time: 1)
Coordinates:
  * time                     (time) int32 1214042401
Dimensions without coordinates: nj, ni
Data variables:
    lat                      (nj, ni) float32 ...
    lon                      (nj, ni) float32 ...
    sea_surface_temperature  (time, nj, ni) int16 ...
    sst_dtime                (time, nj, ni) int16 ...
    quality_level            (time, nj, ni) int8 ...
    sses_bias                (time, nj, ni) int8 ...
    sses_standard_deviation  (time, nj, ni) int8 ...
    l2p_flags                (time, nj, ni) int16 ...
    chlorophyll_a            (time, nj, ni) float32 ...
    K_490                    (time, nj, ni) int16 ...
    wind_speed               (time, nj, ni) int8 ...
    dt_analysis              (time, nj, ni) int8 ...
Attributes: (12/49)
    Conventions:                [b'CF-1.7, ACDD-1.3']
    title:                      [b'MODIS Aqua L2P SST']
    summary:                    [b'Sea surface temperature retrievals produce...
    references:                 [b'GHRSST Data Processing Specification v2r5']
    institution:                [b'NASA/JPL/OBPG/RSMAS']
    history:                    [b'MODIS L2P created at JPL PO.DAAC']
    ...                         ...
    publisher_email:            [b'ghrsst-po@nceo.ac.uk']
    processing_level:           [b'L2P']
    cdm_data_type:              [b'swath']
    startDirection:             [b'Ascending']
    endDirection:               [b'Descending']
    day_night_flag:             [b'Day']</pre><div class="xr-wrap" hidden=""><div class="xr-header"><div class="xr-obj-type">xarray.Dataset</div></div><ul class="xr-sections"><li class="xr-section-item"><input id="section-9e40d245-86ff-42f6-947f-cda565e9a56d" class="xr-section-summary-in" type="checkbox" disabled=""><label for="section-9e40d245-86ff-42f6-947f-cda565e9a56d" class="xr-section-summary" title="Expand/collapse section">Dimensions:</label><div class="xr-section-inline-details"><ul class="xr-dim-list"><li><span>nj</span>: 2030</li><li><span>ni</span>: 1354</li><li><span class="xr-has-index">time</span>: 1</li></ul></div><div class="xr-section-details"></div></li><li class="xr-section-item"><input id="section-53b1ba44-207a-41b9-9ff9-21b203546442" class="xr-section-summary-in" type="checkbox" checked=""><label for="section-53b1ba44-207a-41b9-9ff9-21b203546442" class="xr-section-summary">Coordinates: <span>(1)</span></label><div class="xr-section-inline-details"></div><div class="xr-section-details"><ul class="xr-var-list"><li class="xr-var-item"><div class="xr-var-name"><span class="xr-has-index">time</span></div><div class="xr-var-dims">(time)</div><div class="xr-var-dtype">int32</div><div class="xr-var-preview xr-preview">1214042401</div><input id="attrs-32246dd8-fa6e-477e-99b6-04f644e11341" class="xr-var-attrs-in" type="checkbox"><label for="attrs-32246dd8-fa6e-477e-99b6-04f644e11341" title="Show/Hide attributes"><svg class="icon xr-icon-file-text2"><use href="#icon-file-text2"></use></svg></label><input id="data-58d6c25b-1b75-4d86-a933-5a7026cec86b" class="xr-var-data-in" type="checkbox"><label for="data-58d6c25b-1b75-4d86-a933-5a7026cec86b" title="Show/Hide data repr"><svg class="icon xr-icon-database"><use href="#icon-database"></use></svg></label><div class="xr-var-attrs"><dl class="xr-attrs"><dt><span>long_name :</span></dt><dd>[b'reference time of sst file']</dd><dt><span>standard_name :</span></dt><dd>[b'time']</dd><dt><span>units :</span></dt><dd>[b'seconds since 1981-01-01 00:00:00']</dd><dt><span>comment :</span></dt><dd>[b'time of first sensor observation']</dd><dt><span>coverage_content_type :</span></dt><dd>[b'coordinate']</dd></dl></div><div class="xr-var-data"><pre>array([1214042401], dtype=int32)</pre></div></li></ul></div></li><li class="xr-section-item"><input id="section-bfb3fa95-c364-4547-a73e-41759029bd37" class="xr-section-summary-in" type="checkbox" checked=""><label for="section-bfb3fa95-c364-4547-a73e-41759029bd37" class="xr-section-summary">Data variables: <span>(12)</span></label><div class="xr-section-inline-details"></div><div class="xr-section-details"><ul class="xr-var-list"><li class="xr-var-item"><div class="xr-var-name"><span>lat</span></div><div class="xr-var-dims">(nj, ni)</div><div class="xr-var-dtype">float32</div><div class="xr-var-preview xr-preview">...</div><input id="attrs-15498efb-f602-4d70-911e-08e58d878d13" class="xr-var-attrs-in" type="checkbox"><label for="attrs-15498efb-f602-4d70-911e-08e58d878d13" title="Show/Hide attributes"><svg class="icon xr-icon-file-text2"><use href="#icon-file-text2"></use></svg></label><input id="data-c98d4c3a-f0c4-4d6d-b05b-788064e9ec83" class="xr-var-data-in" type="checkbox"><label for="data-c98d4c3a-f0c4-4d6d-b05b-788064e9ec83" title="Show/Hide data repr"><svg class="icon xr-icon-database"><use href="#icon-database"></use></svg></label><div class="xr-var-attrs"><dl class="xr-attrs"><dt><span>long_name :</span></dt><dd>[b'latitude']</dd><dt><span>standard_name :</span></dt><dd>[b'latitude']</dd><dt><span>units :</span></dt><dd>[b'degrees_north']</dd><dt><span>_FillValue :</span></dt><dd>[-999.]</dd><dt><span>valid_min :</span></dt><dd>[-90.]</dd><dt><span>valid_max :</span></dt><dd>[90.]</dd><dt><span>comment :</span></dt><dd>[b'geographical coordinates, WGS84 projection']</dd><dt><span>coverage_content_type :</span></dt><dd>[b'coordinate']</dd></dl></div><div class="xr-var-data"><pre>[2748620 values with dtype=float32]</pre></div></li><li class="xr-var-item"><div class="xr-var-name"><span>lon</span></div><div class="xr-var-dims">(nj, ni)</div><div class="xr-var-dtype">float32</div><div class="xr-var-preview xr-preview">...</div><input id="attrs-2684d654-de4b-41a7-916a-214095418c82" class="xr-var-attrs-in" type="checkbox"><label for="attrs-2684d654-de4b-41a7-916a-214095418c82" title="Show/Hide attributes"><svg class="icon xr-icon-file-text2"><use href="#icon-file-text2"></use></svg></label><input id="data-a9d40bd6-ec9c-4b1c-b948-f4e8545dfc4e" class="xr-var-data-in" type="checkbox"><label for="data-a9d40bd6-ec9c-4b1c-b948-f4e8545dfc4e" title="Show/Hide data repr"><svg class="icon xr-icon-database"><use href="#icon-database"></use></svg></label><div class="xr-var-attrs"><dl class="xr-attrs"><dt><span>long_name :</span></dt><dd>[b'longitude']</dd><dt><span>standard_name :</span></dt><dd>[b'longitude']</dd><dt><span>units :</span></dt><dd>[b'degrees_east']</dd><dt><span>_FillValue :</span></dt><dd>[-999.]</dd><dt><span>valid_min :</span></dt><dd>[-180.]</dd><dt><span>valid_max :</span></dt><dd>[180.]</dd><dt><span>comment :</span></dt><dd>[b'geographical coordinates, WGS84 projection']</dd><dt><span>coverage_content_type :</span></dt><dd>[b'coordinate']</dd></dl></div><div class="xr-var-data"><pre>[2748620 values with dtype=float32]</pre></div></li><li class="xr-var-item"><div class="xr-var-name"><span>sea_surface_temperature</span></div><div class="xr-var-dims">(time, nj, ni)</div><div class="xr-var-dtype">int16</div><div class="xr-var-preview xr-preview">...</div><input id="attrs-cbd518d1-96e3-4a6c-b902-3dc7ac841f50" class="xr-var-attrs-in" type="checkbox"><label for="attrs-cbd518d1-96e3-4a6c-b902-3dc7ac841f50" title="Show/Hide attributes"><svg class="icon xr-icon-file-text2"><use href="#icon-file-text2"></use></svg></label><input id="data-4f3c4376-5593-4f85-974c-be57b82196e9" class="xr-var-data-in" type="checkbox"><label for="data-4f3c4376-5593-4f85-974c-be57b82196e9" title="Show/Hide data repr"><svg class="icon xr-icon-database"><use href="#icon-database"></use></svg></label><div class="xr-var-attrs"><dl class="xr-attrs"><dt><span>long_name :</span></dt><dd>[b'sea surface temperature']</dd><dt><span>standard_name :</span></dt><dd>[b'sea_surface_skin_temperature']</dd><dt><span>units :</span></dt><dd>[b'kelvin']</dd><dt><span>_FillValue :</span></dt><dd>[-32767]</dd><dt><span>valid_min :</span></dt><dd>[-1000]</dd><dt><span>valid_max :</span></dt><dd>[10000]</dd><dt><span>comment :</span></dt><dd>[b'sea surface temperature from thermal IR (11 um) channels']</dd><dt><span>scale_factor :</span></dt><dd>[0.005]</dd><dt><span>add_offset :</span></dt><dd>[273.15]</dd><dt><span>source :</span></dt><dd>[b'NASA and University of Miami']</dd><dt><span>coordinates :</span></dt><dd>[b'lon lat']</dd><dt><span>coverage_content_type :</span></dt><dd>[b'physicalMeasurement']</dd></dl></div><div class="xr-var-data"><pre>[2748620 values with dtype=int16]</pre></div></li><li class="xr-var-item"><div class="xr-var-name"><span>sst_dtime</span></div><div class="xr-var-dims">(time, nj, ni)</div><div class="xr-var-dtype">int16</div><div class="xr-var-preview xr-preview">...</div><input id="attrs-4644d924-8334-4738-833c-3c7a5107c7f5" class="xr-var-attrs-in" type="checkbox"><label for="attrs-4644d924-8334-4738-833c-3c7a5107c7f5" title="Show/Hide attributes"><svg class="icon xr-icon-file-text2"><use href="#icon-file-text2"></use></svg></label><input id="data-6bdf9478-98d6-478d-8aaf-1312fe3a6357" class="xr-var-data-in" type="checkbox"><label for="data-6bdf9478-98d6-478d-8aaf-1312fe3a6357" title="Show/Hide data repr"><svg class="icon xr-icon-database"><use href="#icon-database"></use></svg></label><div class="xr-var-attrs"><dl class="xr-attrs"><dt><span>long_name :</span></dt><dd>[b'time difference from reference time']</dd><dt><span>units :</span></dt><dd>[b'seconds']</dd><dt><span>_FillValue :</span></dt><dd>[-32768]</dd><dt><span>valid_min :</span></dt><dd>[-32767]</dd><dt><span>valid_max :</span></dt><dd>[32767]</dd><dt><span>comment :</span></dt><dd>[b'time plus sst_dtime gives seconds after 00:00:00 UTC January 1, 1981']</dd><dt><span>coordinates :</span></dt><dd>[b'lon lat']</dd><dt><span>coverage_content_type :</span></dt><dd>[b'referenceInformation']</dd></dl></div><div class="xr-var-data"><pre>[2748620 values with dtype=int16]</pre></div></li><li class="xr-var-item"><div class="xr-var-name"><span>quality_level</span></div><div class="xr-var-dims">(time, nj, ni)</div><div class="xr-var-dtype">int8</div><div class="xr-var-preview xr-preview">...</div><input id="attrs-812dff36-8e88-494b-9536-054544443f39" class="xr-var-attrs-in" type="checkbox"><label for="attrs-812dff36-8e88-494b-9536-054544443f39" title="Show/Hide attributes"><svg class="icon xr-icon-file-text2"><use href="#icon-file-text2"></use></svg></label><input id="data-1cf34218-b372-4710-9fbf-a95ca67526f1" class="xr-var-data-in" type="checkbox"><label for="data-1cf34218-b372-4710-9fbf-a95ca67526f1" title="Show/Hide data repr"><svg class="icon xr-icon-database"><use href="#icon-database"></use></svg></label><div class="xr-var-attrs"><dl class="xr-attrs"><dt><span>long_name :</span></dt><dd>[b'quality level of SST pixel']</dd><dt><span>_FillValue :</span></dt><dd>[-128]</dd><dt><span>valid_min :</span></dt><dd>[0]</dd><dt><span>valid_max :</span></dt><dd>[5]</dd><dt><span>comment :</span></dt><dd>[b'thermal IR SST proximity confidence value; signed byte array: WARNING Some applications are unable to properly handle signed byte values. If values are encountered &gt; 127, please subtract 256 from this reported value']</dd><dt><span>coordinates :</span></dt><dd>[b'lon lat']</dd><dt><span>flag_values :</span></dt><dd>[0 1 2 3 4 5]</dd><dt><span>flag_meanings :</span></dt><dd>[b'no_data bad_data worst_quality low_quality acceptable_quality best_quality']</dd><dt><span>coverage_content_type :</span></dt><dd>[b'qualityInformation']</dd></dl></div><div class="xr-var-data"><pre>[2748620 values with dtype=int8]</pre></div></li><li class="xr-var-item"><div class="xr-var-name"><span>sses_bias</span></div><div class="xr-var-dims">(time, nj, ni)</div><div class="xr-var-dtype">int8</div><div class="xr-var-preview xr-preview">...</div><input id="attrs-df129cc5-59d8-4621-9dad-9999411d3c68" class="xr-var-attrs-in" type="checkbox"><label for="attrs-df129cc5-59d8-4621-9dad-9999411d3c68" title="Show/Hide attributes"><svg class="icon xr-icon-file-text2"><use href="#icon-file-text2"></use></svg></label><input id="data-84cad695-d9d6-4292-bac2-06cd5d29f48f" class="xr-var-data-in" type="checkbox"><label for="data-84cad695-d9d6-4292-bac2-06cd5d29f48f" title="Show/Hide data repr"><svg class="icon xr-icon-database"><use href="#icon-database"></use></svg></label><div class="xr-var-attrs"><dl class="xr-attrs"><dt><span>long_name :</span></dt><dd>[b'SSES bias error based on proximity confidence flags']</dd><dt><span>units :</span></dt><dd>[b'kelvin']</dd><dt><span>_FillValue :</span></dt><dd>[-128]</dd><dt><span>valid_min :</span></dt><dd>[-127]</dd><dt><span>valid_max :</span></dt><dd>[127]</dd><dt><span>comment :</span></dt><dd>[b'thermal IR SST bias error; signed byte array: WARNING Some applications are unable to properly handle signed byte values. If values are encountered &gt; 127, please subtract 256 from this reported value']</dd><dt><span>scale_factor :</span></dt><dd>[0.15748031]</dd><dt><span>add_offset :</span></dt><dd>[0.]</dd><dt><span>coordinates :</span></dt><dd>[b'lon lat']</dd><dt><span>coverage_content_type :</span></dt><dd>[b'auxiliaryInformation']</dd></dl></div><div class="xr-var-data"><pre>[2748620 values with dtype=int8]</pre></div></li><li class="xr-var-item"><div class="xr-var-name"><span>sses_standard_deviation</span></div><div class="xr-var-dims">(time, nj, ni)</div><div class="xr-var-dtype">int8</div><div class="xr-var-preview xr-preview">...</div><input id="attrs-f41bf12a-d2e3-4b1b-89f6-85f557649932" class="xr-var-attrs-in" type="checkbox"><label for="attrs-f41bf12a-d2e3-4b1b-89f6-85f557649932" title="Show/Hide attributes"><svg class="icon xr-icon-file-text2"><use href="#icon-file-text2"></use></svg></label><input id="data-8cbe66de-b3df-42c4-996e-7a1d57ea1864" class="xr-var-data-in" type="checkbox"><label for="data-8cbe66de-b3df-42c4-996e-7a1d57ea1864" title="Show/Hide data repr"><svg class="icon xr-icon-database"><use href="#icon-database"></use></svg></label><div class="xr-var-attrs"><dl class="xr-attrs"><dt><span>long_name :</span></dt><dd>[b'SSES standard deviation error based on proximity confidence flags']</dd><dt><span>units :</span></dt><dd>[b'kelvin']</dd><dt><span>_FillValue :</span></dt><dd>[-128]</dd><dt><span>valid_min :</span></dt><dd>[-127]</dd><dt><span>valid_max :</span></dt><dd>[127]</dd><dt><span>comment :</span></dt><dd>[b'thermal IR SST standard deviation error; signed byte array: WARNING Some applications are unable to properly handle signed byte values. If values are encountered &gt; 127, please subtract 256 from this reported value']</dd><dt><span>scale_factor :</span></dt><dd>[0.07874016]</dd><dt><span>add_offset :</span></dt><dd>[10.]</dd><dt><span>coordinates :</span></dt><dd>[b'lon lat']</dd><dt><span>coverage_content_type :</span></dt><dd>[b'auxiliaryInformation']</dd></dl></div><div class="xr-var-data"><pre>[2748620 values with dtype=int8]</pre></div></li><li class="xr-var-item"><div class="xr-var-name"><span>l2p_flags</span></div><div class="xr-var-dims">(time, nj, ni)</div><div class="xr-var-dtype">int16</div><div class="xr-var-preview xr-preview">...</div><input id="attrs-6e3742cc-ee26-41a1-b242-3ea61484c7b5" class="xr-var-attrs-in" type="checkbox"><label for="attrs-6e3742cc-ee26-41a1-b242-3ea61484c7b5" title="Show/Hide attributes"><svg class="icon xr-icon-file-text2"><use href="#icon-file-text2"></use></svg></label><input id="data-ef271e45-0eb0-4cc1-a428-26b3ca37f6c6" class="xr-var-data-in" type="checkbox"><label for="data-ef271e45-0eb0-4cc1-a428-26b3ca37f6c6" title="Show/Hide data repr"><svg class="icon xr-icon-database"><use href="#icon-database"></use></svg></label><div class="xr-var-attrs"><dl class="xr-attrs"><dt><span>long_name :</span></dt><dd>[b'L2P flags']</dd><dt><span>valid_min :</span></dt><dd>[0]</dd><dt><span>valid_max :</span></dt><dd>[16]</dd><dt><span>comment :</span></dt><dd>[b'These flags can be used to further filter data variables']</dd><dt><span>coordinates :</span></dt><dd>[b'lon lat']</dd><dt><span>flag_meanings :</span></dt><dd>[b'microwave land ice lake river']</dd><dt><span>flag_masks :</span></dt><dd>[ 1  2  4  8 16]</dd><dt><span>coverage_content_type :</span></dt><dd>[b'qualityInformation']</dd></dl></div><div class="xr-var-data"><pre>[2748620 values with dtype=int16]</pre></div></li><li class="xr-var-item"><div class="xr-var-name"><span>chlorophyll_a</span></div><div class="xr-var-dims">(time, nj, ni)</div><div class="xr-var-dtype">float32</div><div class="xr-var-preview xr-preview">...</div><input id="attrs-1282f416-9317-474c-947d-0a7b01e6d7ed" class="xr-var-attrs-in" type="checkbox"><label for="attrs-1282f416-9317-474c-947d-0a7b01e6d7ed" title="Show/Hide attributes"><svg class="icon xr-icon-file-text2"><use href="#icon-file-text2"></use></svg></label><input id="data-900c440c-7f14-49f0-8483-63130d1237b6" class="xr-var-data-in" type="checkbox"><label for="data-900c440c-7f14-49f0-8483-63130d1237b6" title="Show/Hide data repr"><svg class="icon xr-icon-database"><use href="#icon-database"></use></svg></label><div class="xr-var-attrs"><dl class="xr-attrs"><dt><span>long_name :</span></dt><dd>[b'Chlorophyll Concentration, OC3 Algorithm']</dd><dt><span>units :</span></dt><dd>[b'mg m^-3']</dd><dt><span>_FillValue :</span></dt><dd>[-32767.]</dd><dt><span>valid_min :</span></dt><dd>[0.001]</dd><dt><span>valid_max :</span></dt><dd>[100.]</dd><dt><span>comment :</span></dt><dd>[b'non L2P core field']</dd><dt><span>coordinates :</span></dt><dd>[b'lon lat']</dd><dt><span>coverage_content_type :</span></dt><dd>[b'auxiliaryInformation']</dd></dl></div><div class="xr-var-data"><pre>[2748620 values with dtype=float32]</pre></div></li><li class="xr-var-item"><div class="xr-var-name"><span>K_490</span></div><div class="xr-var-dims">(time, nj, ni)</div><div class="xr-var-dtype">int16</div><div class="xr-var-preview xr-preview">...</div><input id="attrs-6bc97a4c-0c18-47e2-acb7-e26cf7f513ab" class="xr-var-attrs-in" type="checkbox"><label for="attrs-6bc97a4c-0c18-47e2-acb7-e26cf7f513ab" title="Show/Hide attributes"><svg class="icon xr-icon-file-text2"><use href="#icon-file-text2"></use></svg></label><input id="data-d419179f-27c0-4447-b2ed-59015c8ce296" class="xr-var-data-in" type="checkbox"><label for="data-d419179f-27c0-4447-b2ed-59015c8ce296" title="Show/Hide data repr"><svg class="icon xr-icon-database"><use href="#icon-database"></use></svg></label><div class="xr-var-attrs"><dl class="xr-attrs"><dt><span>long_name :</span></dt><dd>[b'Diffuse attenuation coefficient at 490 nm (OBPG)']</dd><dt><span>units :</span></dt><dd>[b'm^-1']</dd><dt><span>_FillValue :</span></dt><dd>[-32767]</dd><dt><span>valid_min :</span></dt><dd>[50]</dd><dt><span>valid_max :</span></dt><dd>[30000]</dd><dt><span>comment :</span></dt><dd>[b'non L2P core field']</dd><dt><span>scale_factor :</span></dt><dd>[0.0002]</dd><dt><span>add_offset :</span></dt><dd>[0.]</dd><dt><span>coordinates :</span></dt><dd>[b'lon lat']</dd><dt><span>coverage_content_type :</span></dt><dd>[b'auxiliaryInformation']</dd></dl></div><div class="xr-var-data"><pre>[2748620 values with dtype=int16]</pre></div></li><li class="xr-var-item"><div class="xr-var-name"><span>wind_speed</span></div><div class="xr-var-dims">(time, nj, ni)</div><div class="xr-var-dtype">int8</div><div class="xr-var-preview xr-preview">...</div><input id="attrs-a727a463-2b1b-457e-bc10-2b6b7ffbda5f" class="xr-var-attrs-in" type="checkbox"><label for="attrs-a727a463-2b1b-457e-bc10-2b6b7ffbda5f" title="Show/Hide attributes"><svg class="icon xr-icon-file-text2"><use href="#icon-file-text2"></use></svg></label><input id="data-5125e926-4d11-48f1-a650-519cf9d759b0" class="xr-var-data-in" type="checkbox"><label for="data-5125e926-4d11-48f1-a650-519cf9d759b0" title="Show/Hide data repr"><svg class="icon xr-icon-database"><use href="#icon-database"></use></svg></label><div class="xr-var-attrs"><dl class="xr-attrs"><dt><span>long_name :</span></dt><dd>[b'10m wind speed']</dd><dt><span>standard_name :</span></dt><dd>[b'wind_speed']</dd><dt><span>units :</span></dt><dd>[b'm s-1']</dd><dt><span>_FillValue :</span></dt><dd>[-128]</dd><dt><span>valid_min :</span></dt><dd>[-127]</dd><dt><span>valid_max :</span></dt><dd>[127]</dd><dt><span>comment :</span></dt><dd>[b'Wind at 10 meters above the sea surface']</dd><dt><span>scale_factor :</span></dt><dd>[0.2]</dd><dt><span>add_offset :</span></dt><dd>[25.]</dd><dt><span>source :</span></dt><dd>[b'TBD.  Placeholder.  Currently empty']</dd><dt><span>coordinates :</span></dt><dd>[b'lon lat']</dd><dt><span>grid_mapping :</span></dt><dd>[b'TBD']</dd><dt><span>time_offset :</span></dt><dd>[2.]</dd><dt><span>height :</span></dt><dd>[b'10 m']</dd><dt><span>coverage_content_type :</span></dt><dd>[b'auxiliaryInformation']</dd></dl></div><div class="xr-var-data"><pre>[2748620 values with dtype=int8]</pre></div></li><li class="xr-var-item"><div class="xr-var-name"><span>dt_analysis</span></div><div class="xr-var-dims">(time, nj, ni)</div><div class="xr-var-dtype">int8</div><div class="xr-var-preview xr-preview">...</div><input id="attrs-95a5761b-dfb8-4f64-9aa2-079d0ce0081b" class="xr-var-attrs-in" type="checkbox"><label for="attrs-95a5761b-dfb8-4f64-9aa2-079d0ce0081b" title="Show/Hide attributes"><svg class="icon xr-icon-file-text2"><use href="#icon-file-text2"></use></svg></label><input id="data-b0d5fedb-711a-47e9-b9fa-92fe1cb95fb3" class="xr-var-data-in" type="checkbox"><label for="data-b0d5fedb-711a-47e9-b9fa-92fe1cb95fb3" title="Show/Hide data repr"><svg class="icon xr-icon-database"><use href="#icon-database"></use></svg></label><div class="xr-var-attrs"><dl class="xr-attrs"><dt><span>long_name :</span></dt><dd>[b'deviation from SST reference climatology']</dd><dt><span>units :</span></dt><dd>[b'kelvin']</dd><dt><span>_FillValue :</span></dt><dd>[-128]</dd><dt><span>valid_min :</span></dt><dd>[-127]</dd><dt><span>valid_max :</span></dt><dd>[127]</dd><dt><span>comment :</span></dt><dd>[b'TBD']</dd><dt><span>scale_factor :</span></dt><dd>[0.1]</dd><dt><span>add_offset :</span></dt><dd>[0.]</dd><dt><span>source :</span></dt><dd>[b'TBD. Placeholder.  Currently empty']</dd><dt><span>coordinates :</span></dt><dd>[b'lon lat']</dd><dt><span>coverage_content_type :</span></dt><dd>[b'auxiliaryInformation']</dd></dl></div><div class="xr-var-data"><pre>[2748620 values with dtype=int8]</pre></div></li></ul></div></li><li class="xr-section-item"><input id="section-850d89dd-fa50-4efc-8a6a-361ab2956784" class="xr-section-summary-in" type="checkbox"><label for="section-850d89dd-fa50-4efc-8a6a-361ab2956784" class="xr-section-summary">Attributes: <span>(49)</span></label><div class="xr-section-inline-details"></div><div class="xr-section-details"><dl class="xr-attrs"><dt><span>Conventions :</span></dt><dd>[b'CF-1.7, ACDD-1.3']</dd><dt><span>title :</span></dt><dd>[b'MODIS Aqua L2P SST']</dd><dt><span>summary :</span></dt><dd>[b'Sea surface temperature retrievals produced at the NASA OBPG for the MODIS Aqua sensor.  These have been reformatted to GHRSST GDS specifications by the JPL PO.DAAC']</dd><dt><span>references :</span></dt><dd>[b'GHRSST Data Processing Specification v2r5']</dd><dt><span>institution :</span></dt><dd>[b'NASA/JPL/OBPG/RSMAS']</dd><dt><span>history :</span></dt><dd>[b'MODIS L2P created at JPL PO.DAAC']</dd><dt><span>comment :</span></dt><dd>[b'L2P Core without DT analysis or other ancillary fields; Day, Start Node:Ascending, End Node:Descending; WARNING Some applications are unable to properly handle signed byte values. If values are encountered &gt; 127, please subtract 256 from this reported value; Refined']</dd><dt><span>license :</span></dt><dd>[b'GHRSST and PO.DAAC protocol allow data use as free and open.']</dd><dt><span>id :</span></dt><dd>[b'MODIS_A-JPL-L2P-v2019.0']</dd><dt><span>naming_authority :</span></dt><dd>[b'org.ghrsst']</dd><dt><span>product_version :</span></dt><dd>[b'2019.0']</dd><dt><span>uuid :</span></dt><dd>[b'f6e1f61d-c4a4-4c17-8354-0c15e12d688b']</dd><dt><span>gds_version_id :</span></dt><dd>[b'2.0']</dd><dt><span>netcdf_version_id :</span></dt><dd>[b'4.1']</dd><dt><span>date_created :</span></dt><dd>[b'20200221T085224Z']</dd><dt><span>file_quality_level :</span></dt><dd>[3]</dd><dt><span>spatial_resolution :</span></dt><dd>[b'1km']</dd><dt><span>start_time :</span></dt><dd>[b'20190622T100001Z']</dd><dt><span>time_coverage_start :</span></dt><dd>[b'20190622T100001Z']</dd><dt><span>stop_time :</span></dt><dd>[b'20190622T100459Z']</dd><dt><span>time_coverage_end :</span></dt><dd>[b'20190622T100459Z']</dd><dt><span>northernmost_latitude :</span></dt><dd>[89.9862]</dd><dt><span>southernmost_latitude :</span></dt><dd>[66.2723]</dd><dt><span>easternmost_longitude :</span></dt><dd>[-45.9467]</dd><dt><span>westernmost_longitude :</span></dt><dd>[152.489]</dd><dt><span>source :</span></dt><dd>[b'MODIS sea surface temperature observations for the OBPG']</dd><dt><span>platform :</span></dt><dd>[b'Aqua']</dd><dt><span>sensor :</span></dt><dd>[b'MODIS']</dd><dt><span>metadata_link :</span></dt><dd>[b'http://podaac.jpl.nasa.gov/ws/metadata/dataset/?format=iso&amp;shortName=MODIS_A-JPL-L2P-v2019.0']</dd><dt><span>keywords :</span></dt><dd>[b'Oceans &gt; Ocean Temperature &gt; Sea Surface Temperature']</dd><dt><span>keywords_vocabulary :</span></dt><dd>[b'NASA Global Change Master Directory (GCMD) Science Keywords']</dd><dt><span>standard_name_vocabulary :</span></dt><dd>[b'NetCDF Climate and Forecast (CF) Metadata Convention']</dd><dt><span>geospatial_lat_units :</span></dt><dd>[b'degrees_north']</dd><dt><span>geospatial_lat_resolution :</span></dt><dd>[0.01]</dd><dt><span>geospatial_lon_units :</span></dt><dd>[b'degrees_east']</dd><dt><span>geospatial_lon_resolution :</span></dt><dd>[0.01]</dd><dt><span>acknowledgment :</span></dt><dd>[b'The MODIS L2P sea surface temperature data are sponsored by NASA']</dd><dt><span>creator_name :</span></dt><dd>[b'Ed Armstrong, JPL PO.DAAC']</dd><dt><span>creator_email :</span></dt><dd>[b'edward.m.armstrong@jpl.nasa.gov']</dd><dt><span>creator_url :</span></dt><dd>[b'http://podaac.jpl.nasa.gov']</dd><dt><span>project :</span></dt><dd>[b'Group for High Resolution Sea Surface Temperature']</dd><dt><span>publisher_name :</span></dt><dd>[b'The GHRSST Project Office']</dd><dt><span>publisher_url :</span></dt><dd>[b'http://www.ghrsst.org']</dd><dt><span>publisher_email :</span></dt><dd>[b'ghrsst-po@nceo.ac.uk']</dd><dt><span>processing_level :</span></dt><dd>[b'L2P']</dd><dt><span>cdm_data_type :</span></dt><dd>[b'swath']</dd><dt><span>startDirection :</span></dt><dd>[b'Ascending']</dd><dt><span>endDirection :</span></dt><dd>[b'Descending']</dd><dt><span>day_night_flag :</span></dt><dd>[b'Day']</dd></dl></div></li></ul></div></div>
</div>
</div>
<p>To fix this, we need to extract array elements as scalars, and convert those scalars from bytestrings to strings. We use the <code>decode</code> method to do this. The bytestrings are encoded as utf-8, which is a unicode character format. This is the default encoding for <code>decode</code> but we’ve included it as an argument to be explicit.</p>
<p>Not all attributes are bytestrings. Some are <code>floats</code>. Take a look at <code>_FillValue</code>, and <code>valid_min</code> and <code>valid_max</code>. To avoid an error, we use the <code>isinstance</code> function to check if the value of an attributes is type <code>bytes</code> - a bytestring. If it is, then we decode it. If not, we just extract the scalar and do nothing else.</p>
<p>We also fix the global attributes.</p>
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> fix_attributes(da):</span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a>    <span class="co">'''Decodes bytestring attributes to strings'''</span></span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> attr, value <span class="kw">in</span> da.attrs.items():</span>
<span id="cb28-4"><a href="#cb28-4" aria-hidden="true" tabindex="-1"></a>        <span class="cf">if</span> <span class="bu">isinstance</span>(value[<span class="dv">0</span>], <span class="bu">bytes</span>):</span>
<span id="cb28-5"><a href="#cb28-5" aria-hidden="true" tabindex="-1"></a>            da.attrs[attr] <span class="op">=</span> value[<span class="dv">0</span>].decode(<span class="st">'utf-8'</span>)</span>
<span id="cb28-6"><a href="#cb28-6" aria-hidden="true" tabindex="-1"></a>        <span class="cf">else</span>:</span>
<span id="cb28-7"><a href="#cb28-7" aria-hidden="true" tabindex="-1"></a>            da.attrs[attr] <span class="op">=</span> value[<span class="dv">0</span>]</span>
<span id="cb28-8"><a href="#cb28-8" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span></span>
<span id="cb28-9"><a href="#cb28-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-10"><a href="#cb28-10" aria-hidden="true" tabindex="-1"></a><span class="co"># Fix variable attributes</span></span>
<span id="cb28-11"><a href="#cb28-11" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> var <span class="kw">in</span> modis_ds.variables:</span>
<span id="cb28-12"><a href="#cb28-12" aria-hidden="true" tabindex="-1"></a>    da <span class="op">=</span> modis_ds[var]</span>
<span id="cb28-13"><a href="#cb28-13" aria-hidden="true" tabindex="-1"></a>    fix_attributes(da)</span>
<span id="cb28-14"><a href="#cb28-14" aria-hidden="true" tabindex="-1"></a>            </span>
<span id="cb28-15"><a href="#cb28-15" aria-hidden="true" tabindex="-1"></a><span class="co"># Fix global attributes</span></span>
<span id="cb28-16"><a href="#cb28-16" aria-hidden="true" tabindex="-1"></a>fix_attributes(modis_ds)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>With this done, we can use the <code>xarray</code> function <code>decode_cf</code> to convert the attributes.</p>
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a>modis_ds <span class="op">=</span> xr.decode_cf(modis_ds)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell" data-execution_count="24">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a>modis_ds</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="24">

<div><svg style="position: absolute; width: 0; height: 0; overflow: hidden">
<defs>
<symbol id="icon-database" viewbox="0 0 32 32">
<path d="M16 0c-8.837 0-16 2.239-16 5v4c0 2.761 7.163 5 16 5s16-2.239 16-5v-4c0-2.761-7.163-5-16-5z"></path>
<path d="M16 17c-8.837 0-16-2.239-16-5v6c0 2.761 7.163 5 16 5s16-2.239 16-5v-6c0 2.761-7.163 5-16 5z"></path>
<path d="M16 26c-8.837 0-16-2.239-16-5v6c0 2.761 7.163 5 16 5s16-2.239 16-5v-6c0 2.761-7.163 5-16 5z"></path>
</symbol>
<symbol id="icon-file-text2" viewbox="0 0 32 32">
<path d="M28.681 7.159c-0.694-0.947-1.662-2.053-2.724-3.116s-2.169-2.030-3.116-2.724c-1.612-1.182-2.393-1.319-2.841-1.319h-15.5c-1.378 0-2.5 1.121-2.5 2.5v27c0 1.378 1.122 2.5 2.5 2.5h23c1.378 0 2.5-1.122 2.5-2.5v-19.5c0-0.448-0.137-1.23-1.319-2.841zM24.543 5.457c0.959 0.959 1.712 1.825 2.268 2.543h-4.811v-4.811c0.718 0.556 1.584 1.309 2.543 2.268zM28 29.5c0 0.271-0.229 0.5-0.5 0.5h-23c-0.271 0-0.5-0.229-0.5-0.5v-27c0-0.271 0.229-0.5 0.5-0.5 0 0 15.499-0 15.5 0v7c0 0.552 0.448 1 1 1h7v19.5z"></path>
<path d="M23 26h-14c-0.552 0-1-0.448-1-1s0.448-1 1-1h14c0.552 0 1 0.448 1 1s-0.448 1-1 1z"></path>
<path d="M23 22h-14c-0.552 0-1-0.448-1-1s0.448-1 1-1h14c0.552 0 1 0.448 1 1s-0.448 1-1 1z"></path>
<path d="M23 18h-14c-0.552 0-1-0.448-1-1s0.448-1 1-1h14c0.552 0 1 0.448 1 1s-0.448 1-1 1z"></path>
</symbol>
</defs>
</svg>
<style>/* CSS stylesheet for displaying xarray objects in jupyterlab.
 *
 */

:root {
  --xr-font-color0: var(--jp-content-font-color0, rgba(0, 0, 0, 1));
  --xr-font-color2: var(--jp-content-font-color2, rgba(0, 0, 0, 0.54));
  --xr-font-color3: var(--jp-content-font-color3, rgba(0, 0, 0, 0.38));
  --xr-border-color: var(--jp-border-color2, #e0e0e0);
  --xr-disabled-color: var(--jp-layout-color3, #bdbdbd);
  --xr-background-color: var(--jp-layout-color0, white);
  --xr-background-color-row-even: var(--jp-layout-color1, white);
  --xr-background-color-row-odd: var(--jp-layout-color2, #eeeeee);
}

html[theme=dark],
body.vscode-dark {
  --xr-font-color0: rgba(255, 255, 255, 1);
  --xr-font-color2: rgba(255, 255, 255, 0.54);
  --xr-font-color3: rgba(255, 255, 255, 0.38);
  --xr-border-color: #1F1F1F;
  --xr-disabled-color: #515151;
  --xr-background-color: #111111;
  --xr-background-color-row-even: #111111;
  --xr-background-color-row-odd: #313131;
}

.xr-wrap {
  display: block;
  min-width: 300px;
  max-width: 700px;
}

.xr-text-repr-fallback {
  /* fallback to plain text repr when CSS is not injected (untrusted notebook) */
  display: none;
}

.xr-header {
  padding-top: 6px;
  padding-bottom: 6px;
  margin-bottom: 4px;
  border-bottom: solid 1px var(--xr-border-color);
}

.xr-header > div,
.xr-header > ul {
  display: inline;
  margin-top: 0;
  margin-bottom: 0;
}

.xr-obj-type,
.xr-array-name {
  margin-left: 2px;
  margin-right: 10px;
}

.xr-obj-type {
  color: var(--xr-font-color2);
}

.xr-sections {
  padding-left: 0 !important;
  display: grid;
  grid-template-columns: 150px auto auto 1fr 20px 20px;
}

.xr-section-item {
  display: contents;
}

.xr-section-item input {
  display: none;
}

.xr-section-item input + label {
  color: var(--xr-disabled-color);
}

.xr-section-item input:enabled + label {
  cursor: pointer;
  color: var(--xr-font-color2);
}

.xr-section-item input:enabled + label:hover {
  color: var(--xr-font-color0);
}

.xr-section-summary {
  grid-column: 1;
  color: var(--xr-font-color2);
  font-weight: 500;
}

.xr-section-summary > span {
  display: inline-block;
  padding-left: 0.5em;
}

.xr-section-summary-in:disabled + label {
  color: var(--xr-font-color2);
}

.xr-section-summary-in + label:before {
  display: inline-block;
  content: '►';
  font-size: 11px;
  width: 15px;
  text-align: center;
}

.xr-section-summary-in:disabled + label:before {
  color: var(--xr-disabled-color);
}

.xr-section-summary-in:checked + label:before {
  content: '▼';
}

.xr-section-summary-in:checked + label > span {
  display: none;
}

.xr-section-summary,
.xr-section-inline-details {
  padding-top: 4px;
  padding-bottom: 4px;
}

.xr-section-inline-details {
  grid-column: 2 / -1;
}

.xr-section-details {
  display: none;
  grid-column: 1 / -1;
  margin-bottom: 5px;
}

.xr-section-summary-in:checked ~ .xr-section-details {
  display: contents;
}

.xr-array-wrap {
  grid-column: 1 / -1;
  display: grid;
  grid-template-columns: 20px auto;
}

.xr-array-wrap > label {
  grid-column: 1;
  vertical-align: top;
}

.xr-preview {
  color: var(--xr-font-color3);
}

.xr-array-preview,
.xr-array-data {
  padding: 0 5px !important;
  grid-column: 2;
}

.xr-array-data,
.xr-array-in:checked ~ .xr-array-preview {
  display: none;
}

.xr-array-in:checked ~ .xr-array-data,
.xr-array-preview {
  display: inline-block;
}

.xr-dim-list {
  display: inline-block !important;
  list-style: none;
  padding: 0 !important;
  margin: 0;
}

.xr-dim-list li {
  display: inline-block;
  padding: 0;
  margin: 0;
}

.xr-dim-list:before {
  content: '(';
}

.xr-dim-list:after {
  content: ')';
}

.xr-dim-list li:not(:last-child):after {
  content: ',';
  padding-right: 5px;
}

.xr-has-index {
  font-weight: bold;
}

.xr-var-list,
.xr-var-item {
  display: contents;
}

.xr-var-item > div,
.xr-var-item label,
.xr-var-item > .xr-var-name span {
  background-color: var(--xr-background-color-row-even);
  margin-bottom: 0;
}

.xr-var-item > .xr-var-name:hover span {
  padding-right: 5px;
}

.xr-var-list > li:nth-child(odd) > div,
.xr-var-list > li:nth-child(odd) > label,
.xr-var-list > li:nth-child(odd) > .xr-var-name span {
  background-color: var(--xr-background-color-row-odd);
}

.xr-var-name {
  grid-column: 1;
}

.xr-var-dims {
  grid-column: 2;
}

.xr-var-dtype {
  grid-column: 3;
  text-align: right;
  color: var(--xr-font-color2);
}

.xr-var-preview {
  grid-column: 4;
}

.xr-var-name,
.xr-var-dims,
.xr-var-dtype,
.xr-preview,
.xr-attrs dt {
  white-space: nowrap;
  overflow: hidden;
  text-overflow: ellipsis;
  padding-right: 10px;
}

.xr-var-name:hover,
.xr-var-dims:hover,
.xr-var-dtype:hover,
.xr-attrs dt:hover {
  overflow: visible;
  width: auto;
  z-index: 1;
}

.xr-var-attrs,
.xr-var-data {
  display: none;
  background-color: var(--xr-background-color) !important;
  padding-bottom: 5px !important;
}

.xr-var-attrs-in:checked ~ .xr-var-attrs,
.xr-var-data-in:checked ~ .xr-var-data {
  display: block;
}

.xr-var-data > table {
  float: right;
}

.xr-var-name span,
.xr-var-data,
.xr-attrs {
  padding-left: 25px !important;
}

.xr-attrs,
.xr-var-attrs,
.xr-var-data {
  grid-column: 1 / -1;
}

dl.xr-attrs {
  padding: 0;
  margin: 0;
  display: grid;
  grid-template-columns: 125px auto;
}

.xr-attrs dt,
.xr-attrs dd {
  padding: 0;
  margin: 0;
  float: left;
  padding-right: 10px;
  width: auto;
}

.xr-attrs dt {
  font-weight: normal;
  grid-column: 1;
}

.xr-attrs dt:hover span {
  display: inline-block;
  background: var(--xr-background-color);
  padding-right: 10px;
}

.xr-attrs dd {
  grid-column: 2;
  white-space: pre-wrap;
  word-break: break-all;
}

.xr-icon-database,
.xr-icon-file-text2 {
  display: inline-block;
  vertical-align: middle;
  width: 1em;
  height: 1.5em !important;
  stroke-width: 0;
  stroke: currentColor;
  fill: currentColor;
}
</style><pre class="xr-text-repr-fallback">&lt;xarray.Dataset&gt;
Dimensions:                  (nj: 2030, ni: 1354, time: 1)
Coordinates:
    lat                      (nj, ni) float32 ...
    lon                      (nj, ni) float32 ...
  * time                     (time) datetime64[ns] 2019-06-22T10:00:01
Dimensions without coordinates: nj, ni
Data variables:
    sea_surface_temperature  (time, nj, ni) float32 ...
    sst_dtime                (time, nj, ni) timedelta64[ns] ...
    quality_level            (time, nj, ni) float32 ...
    sses_bias                (time, nj, ni) float32 ...
    sses_standard_deviation  (time, nj, ni) float32 ...
    l2p_flags                (time, nj, ni) int16 ...
    chlorophyll_a            (time, nj, ni) float32 ...
    K_490                    (time, nj, ni) float32 ...
    wind_speed               (time, nj, ni) float32 ...
    dt_analysis              (time, nj, ni) float32 ...
Attributes: (12/49)
    Conventions:                CF-1.7, ACDD-1.3
    title:                      MODIS Aqua L2P SST
    summary:                    Sea surface temperature retrievals produced a...
    references:                 GHRSST Data Processing Specification v2r5
    institution:                NASA/JPL/OBPG/RSMAS
    history:                    MODIS L2P created at JPL PO.DAAC
    ...                         ...
    publisher_email:            ghrsst-po@nceo.ac.uk
    processing_level:           L2P
    cdm_data_type:              swath
    startDirection:             Ascending
    endDirection:               Descending
    day_night_flag:             Day</pre><div class="xr-wrap" hidden=""><div class="xr-header"><div class="xr-obj-type">xarray.Dataset</div></div><ul class="xr-sections"><li class="xr-section-item"><input id="section-496e66bb-6e30-4d32-94fe-e1e69a3aa00e" class="xr-section-summary-in" type="checkbox" disabled=""><label for="section-496e66bb-6e30-4d32-94fe-e1e69a3aa00e" class="xr-section-summary" title="Expand/collapse section">Dimensions:</label><div class="xr-section-inline-details"><ul class="xr-dim-list"><li><span>nj</span>: 2030</li><li><span>ni</span>: 1354</li><li><span class="xr-has-index">time</span>: 1</li></ul></div><div class="xr-section-details"></div></li><li class="xr-section-item"><input id="section-4e228a93-bc22-4829-b4d5-38eb43e96dea" class="xr-section-summary-in" type="checkbox" checked=""><label for="section-4e228a93-bc22-4829-b4d5-38eb43e96dea" class="xr-section-summary">Coordinates: <span>(3)</span></label><div class="xr-section-inline-details"></div><div class="xr-section-details"><ul class="xr-var-list"><li class="xr-var-item"><div class="xr-var-name"><span>lat</span></div><div class="xr-var-dims">(nj, ni)</div><div class="xr-var-dtype">float32</div><div class="xr-var-preview xr-preview">...</div><input id="attrs-3961e71d-f410-4b62-a309-b53e5fa35c0f" class="xr-var-attrs-in" type="checkbox"><label for="attrs-3961e71d-f410-4b62-a309-b53e5fa35c0f" title="Show/Hide attributes"><svg class="icon xr-icon-file-text2"><use href="#icon-file-text2"></use></svg></label><input id="data-7b2709b4-3e56-4bd9-a4c1-05364cec3db6" class="xr-var-data-in" type="checkbox"><label for="data-7b2709b4-3e56-4bd9-a4c1-05364cec3db6" title="Show/Hide data repr"><svg class="icon xr-icon-database"><use href="#icon-database"></use></svg></label><div class="xr-var-attrs"><dl class="xr-attrs"><dt><span>long_name :</span></dt><dd>latitude</dd><dt><span>standard_name :</span></dt><dd>latitude</dd><dt><span>units :</span></dt><dd>degrees_north</dd><dt><span>valid_min :</span></dt><dd>-90.0</dd><dt><span>valid_max :</span></dt><dd>90.0</dd><dt><span>comment :</span></dt><dd>geographical coordinates, WGS84 projection</dd><dt><span>coverage_content_type :</span></dt><dd>coordinate</dd></dl></div><div class="xr-var-data"><pre>[2748620 values with dtype=float32]</pre></div></li><li class="xr-var-item"><div class="xr-var-name"><span>lon</span></div><div class="xr-var-dims">(nj, ni)</div><div class="xr-var-dtype">float32</div><div class="xr-var-preview xr-preview">...</div><input id="attrs-52fca852-dc81-4870-8f46-2e26048cd701" class="xr-var-attrs-in" type="checkbox"><label for="attrs-52fca852-dc81-4870-8f46-2e26048cd701" title="Show/Hide attributes"><svg class="icon xr-icon-file-text2"><use href="#icon-file-text2"></use></svg></label><input id="data-37bf6c11-0ee0-4bab-9223-19dcb09cf3a8" class="xr-var-data-in" type="checkbox"><label for="data-37bf6c11-0ee0-4bab-9223-19dcb09cf3a8" title="Show/Hide data repr"><svg class="icon xr-icon-database"><use href="#icon-database"></use></svg></label><div class="xr-var-attrs"><dl class="xr-attrs"><dt><span>long_name :</span></dt><dd>longitude</dd><dt><span>standard_name :</span></dt><dd>longitude</dd><dt><span>units :</span></dt><dd>degrees_east</dd><dt><span>valid_min :</span></dt><dd>-180.0</dd><dt><span>valid_max :</span></dt><dd>180.0</dd><dt><span>comment :</span></dt><dd>geographical coordinates, WGS84 projection</dd><dt><span>coverage_content_type :</span></dt><dd>coordinate</dd></dl></div><div class="xr-var-data"><pre>[2748620 values with dtype=float32]</pre></div></li><li class="xr-var-item"><div class="xr-var-name"><span class="xr-has-index">time</span></div><div class="xr-var-dims">(time)</div><div class="xr-var-dtype">datetime64[ns]</div><div class="xr-var-preview xr-preview">2019-06-22T10:00:01</div><input id="attrs-94999d9e-bab0-4075-b203-49f39e602097" class="xr-var-attrs-in" type="checkbox"><label for="attrs-94999d9e-bab0-4075-b203-49f39e602097" title="Show/Hide attributes"><svg class="icon xr-icon-file-text2"><use href="#icon-file-text2"></use></svg></label><input id="data-0beae798-1e53-466a-9781-665363d3bed2" class="xr-var-data-in" type="checkbox"><label for="data-0beae798-1e53-466a-9781-665363d3bed2" title="Show/Hide data repr"><svg class="icon xr-icon-database"><use href="#icon-database"></use></svg></label><div class="xr-var-attrs"><dl class="xr-attrs"><dt><span>long_name :</span></dt><dd>reference time of sst file</dd><dt><span>standard_name :</span></dt><dd>time</dd><dt><span>comment :</span></dt><dd>time of first sensor observation</dd><dt><span>coverage_content_type :</span></dt><dd>coordinate</dd></dl></div><div class="xr-var-data"><pre>array(['2019-06-22T10:00:01.000000000'], dtype='datetime64[ns]')</pre></div></li></ul></div></li><li class="xr-section-item"><input id="section-7ddb0abe-df46-43d8-b214-b24d0baf918a" class="xr-section-summary-in" type="checkbox" checked=""><label for="section-7ddb0abe-df46-43d8-b214-b24d0baf918a" class="xr-section-summary">Data variables: <span>(10)</span></label><div class="xr-section-inline-details"></div><div class="xr-section-details"><ul class="xr-var-list"><li class="xr-var-item"><div class="xr-var-name"><span>sea_surface_temperature</span></div><div class="xr-var-dims">(time, nj, ni)</div><div class="xr-var-dtype">float32</div><div class="xr-var-preview xr-preview">...</div><input id="attrs-c040bf00-9e53-445d-a09b-ddfff6ede44f" class="xr-var-attrs-in" type="checkbox"><label for="attrs-c040bf00-9e53-445d-a09b-ddfff6ede44f" title="Show/Hide attributes"><svg class="icon xr-icon-file-text2"><use href="#icon-file-text2"></use></svg></label><input id="data-c9b75b04-6ae1-4cef-a383-b357d7c79f17" class="xr-var-data-in" type="checkbox"><label for="data-c9b75b04-6ae1-4cef-a383-b357d7c79f17" title="Show/Hide data repr"><svg class="icon xr-icon-database"><use href="#icon-database"></use></svg></label><div class="xr-var-attrs"><dl class="xr-attrs"><dt><span>long_name :</span></dt><dd>sea surface temperature</dd><dt><span>standard_name :</span></dt><dd>sea_surface_skin_temperature</dd><dt><span>units :</span></dt><dd>kelvin</dd><dt><span>valid_min :</span></dt><dd>-1000</dd><dt><span>valid_max :</span></dt><dd>10000</dd><dt><span>comment :</span></dt><dd>sea surface temperature from thermal IR (11 um) channels</dd><dt><span>source :</span></dt><dd>NASA and University of Miami</dd><dt><span>coverage_content_type :</span></dt><dd>physicalMeasurement</dd></dl></div><div class="xr-var-data"><pre>[2748620 values with dtype=float32]</pre></div></li><li class="xr-var-item"><div class="xr-var-name"><span>sst_dtime</span></div><div class="xr-var-dims">(time, nj, ni)</div><div class="xr-var-dtype">timedelta64[ns]</div><div class="xr-var-preview xr-preview">...</div><input id="attrs-ce800cfd-5ebe-4f2a-999f-703789456570" class="xr-var-attrs-in" type="checkbox"><label for="attrs-ce800cfd-5ebe-4f2a-999f-703789456570" title="Show/Hide attributes"><svg class="icon xr-icon-file-text2"><use href="#icon-file-text2"></use></svg></label><input id="data-09386c5c-6505-49a6-bcf7-d760ebc36ab9" class="xr-var-data-in" type="checkbox"><label for="data-09386c5c-6505-49a6-bcf7-d760ebc36ab9" title="Show/Hide data repr"><svg class="icon xr-icon-database"><use href="#icon-database"></use></svg></label><div class="xr-var-attrs"><dl class="xr-attrs"><dt><span>long_name :</span></dt><dd>time difference from reference time</dd><dt><span>valid_min :</span></dt><dd>-32767</dd><dt><span>valid_max :</span></dt><dd>32767</dd><dt><span>comment :</span></dt><dd>time plus sst_dtime gives seconds after 00:00:00 UTC January 1, 1981</dd><dt><span>coverage_content_type :</span></dt><dd>referenceInformation</dd></dl></div><div class="xr-var-data"><pre>[2748620 values with dtype=timedelta64[ns]]</pre></div></li><li class="xr-var-item"><div class="xr-var-name"><span>quality_level</span></div><div class="xr-var-dims">(time, nj, ni)</div><div class="xr-var-dtype">float32</div><div class="xr-var-preview xr-preview">...</div><input id="attrs-222d6ac8-011d-41ee-9dae-2046ee674543" class="xr-var-attrs-in" type="checkbox"><label for="attrs-222d6ac8-011d-41ee-9dae-2046ee674543" title="Show/Hide attributes"><svg class="icon xr-icon-file-text2"><use href="#icon-file-text2"></use></svg></label><input id="data-1d170579-76fe-4980-bf7a-651339de53e9" class="xr-var-data-in" type="checkbox"><label for="data-1d170579-76fe-4980-bf7a-651339de53e9" title="Show/Hide data repr"><svg class="icon xr-icon-database"><use href="#icon-database"></use></svg></label><div class="xr-var-attrs"><dl class="xr-attrs"><dt><span>long_name :</span></dt><dd>quality level of SST pixel</dd><dt><span>valid_min :</span></dt><dd>0</dd><dt><span>valid_max :</span></dt><dd>5</dd><dt><span>comment :</span></dt><dd>thermal IR SST proximity confidence value; signed byte array: WARNING Some applications are unable to properly handle signed byte values. If values are encountered &gt; 127, please subtract 256 from this reported value</dd><dt><span>flag_values :</span></dt><dd>0</dd><dt><span>flag_meanings :</span></dt><dd>no_data bad_data worst_quality low_quality acceptable_quality best_quality</dd><dt><span>coverage_content_type :</span></dt><dd>qualityInformation</dd></dl></div><div class="xr-var-data"><pre>[2748620 values with dtype=float32]</pre></div></li><li class="xr-var-item"><div class="xr-var-name"><span>sses_bias</span></div><div class="xr-var-dims">(time, nj, ni)</div><div class="xr-var-dtype">float32</div><div class="xr-var-preview xr-preview">...</div><input id="attrs-e3091925-49b4-4245-9ea2-b03ba4a22950" class="xr-var-attrs-in" type="checkbox"><label for="attrs-e3091925-49b4-4245-9ea2-b03ba4a22950" title="Show/Hide attributes"><svg class="icon xr-icon-file-text2"><use href="#icon-file-text2"></use></svg></label><input id="data-49b5259c-8a54-4108-b43d-3d299cf8fd5e" class="xr-var-data-in" type="checkbox"><label for="data-49b5259c-8a54-4108-b43d-3d299cf8fd5e" title="Show/Hide data repr"><svg class="icon xr-icon-database"><use href="#icon-database"></use></svg></label><div class="xr-var-attrs"><dl class="xr-attrs"><dt><span>long_name :</span></dt><dd>SSES bias error based on proximity confidence flags</dd><dt><span>units :</span></dt><dd>kelvin</dd><dt><span>valid_min :</span></dt><dd>-127</dd><dt><span>valid_max :</span></dt><dd>127</dd><dt><span>comment :</span></dt><dd>thermal IR SST bias error; signed byte array: WARNING Some applications are unable to properly handle signed byte values. If values are encountered &gt; 127, please subtract 256 from this reported value</dd><dt><span>coverage_content_type :</span></dt><dd>auxiliaryInformation</dd></dl></div><div class="xr-var-data"><pre>[2748620 values with dtype=float32]</pre></div></li><li class="xr-var-item"><div class="xr-var-name"><span>sses_standard_deviation</span></div><div class="xr-var-dims">(time, nj, ni)</div><div class="xr-var-dtype">float32</div><div class="xr-var-preview xr-preview">...</div><input id="attrs-ea1e47e5-36a2-46fd-b58c-737ad6142994" class="xr-var-attrs-in" type="checkbox"><label for="attrs-ea1e47e5-36a2-46fd-b58c-737ad6142994" title="Show/Hide attributes"><svg class="icon xr-icon-file-text2"><use href="#icon-file-text2"></use></svg></label><input id="data-adbef059-f946-4157-a17a-489a0b08557e" class="xr-var-data-in" type="checkbox"><label for="data-adbef059-f946-4157-a17a-489a0b08557e" title="Show/Hide data repr"><svg class="icon xr-icon-database"><use href="#icon-database"></use></svg></label><div class="xr-var-attrs"><dl class="xr-attrs"><dt><span>long_name :</span></dt><dd>SSES standard deviation error based on proximity confidence flags</dd><dt><span>units :</span></dt><dd>kelvin</dd><dt><span>valid_min :</span></dt><dd>-127</dd><dt><span>valid_max :</span></dt><dd>127</dd><dt><span>comment :</span></dt><dd>thermal IR SST standard deviation error; signed byte array: WARNING Some applications are unable to properly handle signed byte values. If values are encountered &gt; 127, please subtract 256 from this reported value</dd><dt><span>coverage_content_type :</span></dt><dd>auxiliaryInformation</dd></dl></div><div class="xr-var-data"><pre>[2748620 values with dtype=float32]</pre></div></li><li class="xr-var-item"><div class="xr-var-name"><span>l2p_flags</span></div><div class="xr-var-dims">(time, nj, ni)</div><div class="xr-var-dtype">int16</div><div class="xr-var-preview xr-preview">...</div><input id="attrs-cda0c7e4-9974-4c92-b749-7dd8cca0b794" class="xr-var-attrs-in" type="checkbox"><label for="attrs-cda0c7e4-9974-4c92-b749-7dd8cca0b794" title="Show/Hide attributes"><svg class="icon xr-icon-file-text2"><use href="#icon-file-text2"></use></svg></label><input id="data-507d5b33-4aa3-498b-819d-9b70c693b749" class="xr-var-data-in" type="checkbox"><label for="data-507d5b33-4aa3-498b-819d-9b70c693b749" title="Show/Hide data repr"><svg class="icon xr-icon-database"><use href="#icon-database"></use></svg></label><div class="xr-var-attrs"><dl class="xr-attrs"><dt><span>long_name :</span></dt><dd>L2P flags</dd><dt><span>valid_min :</span></dt><dd>0</dd><dt><span>valid_max :</span></dt><dd>16</dd><dt><span>comment :</span></dt><dd>These flags can be used to further filter data variables</dd><dt><span>flag_meanings :</span></dt><dd>microwave land ice lake river</dd><dt><span>flag_masks :</span></dt><dd>1</dd><dt><span>coverage_content_type :</span></dt><dd>qualityInformation</dd></dl></div><div class="xr-var-data"><pre>[2748620 values with dtype=int16]</pre></div></li><li class="xr-var-item"><div class="xr-var-name"><span>chlorophyll_a</span></div><div class="xr-var-dims">(time, nj, ni)</div><div class="xr-var-dtype">float32</div><div class="xr-var-preview xr-preview">...</div><input id="attrs-ae858591-0722-4e32-ad5e-297192905453" class="xr-var-attrs-in" type="checkbox"><label for="attrs-ae858591-0722-4e32-ad5e-297192905453" title="Show/Hide attributes"><svg class="icon xr-icon-file-text2"><use href="#icon-file-text2"></use></svg></label><input id="data-f2b89dd3-7e34-4143-b305-80cba3c2e165" class="xr-var-data-in" type="checkbox"><label for="data-f2b89dd3-7e34-4143-b305-80cba3c2e165" title="Show/Hide data repr"><svg class="icon xr-icon-database"><use href="#icon-database"></use></svg></label><div class="xr-var-attrs"><dl class="xr-attrs"><dt><span>long_name :</span></dt><dd>Chlorophyll Concentration, OC3 Algorithm</dd><dt><span>units :</span></dt><dd>mg m^-3</dd><dt><span>valid_min :</span></dt><dd>0.001</dd><dt><span>valid_max :</span></dt><dd>100.0</dd><dt><span>comment :</span></dt><dd>non L2P core field</dd><dt><span>coverage_content_type :</span></dt><dd>auxiliaryInformation</dd></dl></div><div class="xr-var-data"><pre>[2748620 values with dtype=float32]</pre></div></li><li class="xr-var-item"><div class="xr-var-name"><span>K_490</span></div><div class="xr-var-dims">(time, nj, ni)</div><div class="xr-var-dtype">float32</div><div class="xr-var-preview xr-preview">...</div><input id="attrs-e39a722d-2bc9-4132-abcc-693bb5d74f88" class="xr-var-attrs-in" type="checkbox"><label for="attrs-e39a722d-2bc9-4132-abcc-693bb5d74f88" title="Show/Hide attributes"><svg class="icon xr-icon-file-text2"><use href="#icon-file-text2"></use></svg></label><input id="data-885bc47c-0792-4ce8-a79a-876aef7730a2" class="xr-var-data-in" type="checkbox"><label for="data-885bc47c-0792-4ce8-a79a-876aef7730a2" title="Show/Hide data repr"><svg class="icon xr-icon-database"><use href="#icon-database"></use></svg></label><div class="xr-var-attrs"><dl class="xr-attrs"><dt><span>long_name :</span></dt><dd>Diffuse attenuation coefficient at 490 nm (OBPG)</dd><dt><span>units :</span></dt><dd>m^-1</dd><dt><span>valid_min :</span></dt><dd>50</dd><dt><span>valid_max :</span></dt><dd>30000</dd><dt><span>comment :</span></dt><dd>non L2P core field</dd><dt><span>coverage_content_type :</span></dt><dd>auxiliaryInformation</dd></dl></div><div class="xr-var-data"><pre>[2748620 values with dtype=float32]</pre></div></li><li class="xr-var-item"><div class="xr-var-name"><span>wind_speed</span></div><div class="xr-var-dims">(time, nj, ni)</div><div class="xr-var-dtype">float32</div><div class="xr-var-preview xr-preview">...</div><input id="attrs-371c0689-11ab-4d6d-a524-37f31eeee85a" class="xr-var-attrs-in" type="checkbox"><label for="attrs-371c0689-11ab-4d6d-a524-37f31eeee85a" title="Show/Hide attributes"><svg class="icon xr-icon-file-text2"><use href="#icon-file-text2"></use></svg></label><input id="data-426117b4-d0e6-4296-b8ea-1eec7fe92e21" class="xr-var-data-in" type="checkbox"><label for="data-426117b4-d0e6-4296-b8ea-1eec7fe92e21" title="Show/Hide data repr"><svg class="icon xr-icon-database"><use href="#icon-database"></use></svg></label><div class="xr-var-attrs"><dl class="xr-attrs"><dt><span>long_name :</span></dt><dd>10m wind speed</dd><dt><span>standard_name :</span></dt><dd>wind_speed</dd><dt><span>units :</span></dt><dd>m s-1</dd><dt><span>valid_min :</span></dt><dd>-127</dd><dt><span>valid_max :</span></dt><dd>127</dd><dt><span>comment :</span></dt><dd>Wind at 10 meters above the sea surface</dd><dt><span>source :</span></dt><dd>TBD.  Placeholder.  Currently empty</dd><dt><span>grid_mapping :</span></dt><dd>TBD</dd><dt><span>time_offset :</span></dt><dd>2.0</dd><dt><span>height :</span></dt><dd>10 m</dd><dt><span>coverage_content_type :</span></dt><dd>auxiliaryInformation</dd></dl></div><div class="xr-var-data"><pre>[2748620 values with dtype=float32]</pre></div></li><li class="xr-var-item"><div class="xr-var-name"><span>dt_analysis</span></div><div class="xr-var-dims">(time, nj, ni)</div><div class="xr-var-dtype">float32</div><div class="xr-var-preview xr-preview">...</div><input id="attrs-ad46fc85-fba9-40b3-a569-c1c0a14d2302" class="xr-var-attrs-in" type="checkbox"><label for="attrs-ad46fc85-fba9-40b3-a569-c1c0a14d2302" title="Show/Hide attributes"><svg class="icon xr-icon-file-text2"><use href="#icon-file-text2"></use></svg></label><input id="data-8b265196-17d8-4c24-9045-460362d84bb9" class="xr-var-data-in" type="checkbox"><label for="data-8b265196-17d8-4c24-9045-460362d84bb9" title="Show/Hide data repr"><svg class="icon xr-icon-database"><use href="#icon-database"></use></svg></label><div class="xr-var-attrs"><dl class="xr-attrs"><dt><span>long_name :</span></dt><dd>deviation from SST reference climatology</dd><dt><span>units :</span></dt><dd>kelvin</dd><dt><span>valid_min :</span></dt><dd>-127</dd><dt><span>valid_max :</span></dt><dd>127</dd><dt><span>comment :</span></dt><dd>TBD</dd><dt><span>source :</span></dt><dd>TBD. Placeholder.  Currently empty</dd><dt><span>coverage_content_type :</span></dt><dd>auxiliaryInformation</dd></dl></div><div class="xr-var-data"><pre>[2748620 values with dtype=float32]</pre></div></li></ul></div></li><li class="xr-section-item"><input id="section-16d5140f-6659-4c80-ae09-90fcbe047a16" class="xr-section-summary-in" type="checkbox"><label for="section-16d5140f-6659-4c80-ae09-90fcbe047a16" class="xr-section-summary">Attributes: <span>(49)</span></label><div class="xr-section-inline-details"></div><div class="xr-section-details"><dl class="xr-attrs"><dt><span>Conventions :</span></dt><dd>CF-1.7, ACDD-1.3</dd><dt><span>title :</span></dt><dd>MODIS Aqua L2P SST</dd><dt><span>summary :</span></dt><dd>Sea surface temperature retrievals produced at the NASA OBPG for the MODIS Aqua sensor.  These have been reformatted to GHRSST GDS specifications by the JPL PO.DAAC</dd><dt><span>references :</span></dt><dd>GHRSST Data Processing Specification v2r5</dd><dt><span>institution :</span></dt><dd>NASA/JPL/OBPG/RSMAS</dd><dt><span>history :</span></dt><dd>MODIS L2P created at JPL PO.DAAC</dd><dt><span>comment :</span></dt><dd>L2P Core without DT analysis or other ancillary fields; Day, Start Node:Ascending, End Node:Descending; WARNING Some applications are unable to properly handle signed byte values. If values are encountered &gt; 127, please subtract 256 from this reported value; Refined</dd><dt><span>license :</span></dt><dd>GHRSST and PO.DAAC protocol allow data use as free and open.</dd><dt><span>id :</span></dt><dd>MODIS_A-JPL-L2P-v2019.0</dd><dt><span>naming_authority :</span></dt><dd>org.ghrsst</dd><dt><span>product_version :</span></dt><dd>2019.0</dd><dt><span>uuid :</span></dt><dd>f6e1f61d-c4a4-4c17-8354-0c15e12d688b</dd><dt><span>gds_version_id :</span></dt><dd>2.0</dd><dt><span>netcdf_version_id :</span></dt><dd>4.1</dd><dt><span>date_created :</span></dt><dd>20200221T085224Z</dd><dt><span>file_quality_level :</span></dt><dd>3</dd><dt><span>spatial_resolution :</span></dt><dd>1km</dd><dt><span>start_time :</span></dt><dd>20190622T100001Z</dd><dt><span>time_coverage_start :</span></dt><dd>20190622T100001Z</dd><dt><span>stop_time :</span></dt><dd>20190622T100459Z</dd><dt><span>time_coverage_end :</span></dt><dd>20190622T100459Z</dd><dt><span>northernmost_latitude :</span></dt><dd>89.9862</dd><dt><span>southernmost_latitude :</span></dt><dd>66.2723</dd><dt><span>easternmost_longitude :</span></dt><dd>-45.9467</dd><dt><span>westernmost_longitude :</span></dt><dd>152.489</dd><dt><span>source :</span></dt><dd>MODIS sea surface temperature observations for the OBPG</dd><dt><span>platform :</span></dt><dd>Aqua</dd><dt><span>sensor :</span></dt><dd>MODIS</dd><dt><span>metadata_link :</span></dt><dd>http://podaac.jpl.nasa.gov/ws/metadata/dataset/?format=iso&amp;shortName=MODIS_A-JPL-L2P-v2019.0</dd><dt><span>keywords :</span></dt><dd>Oceans &gt; Ocean Temperature &gt; Sea Surface Temperature</dd><dt><span>keywords_vocabulary :</span></dt><dd>NASA Global Change Master Directory (GCMD) Science Keywords</dd><dt><span>standard_name_vocabulary :</span></dt><dd>NetCDF Climate and Forecast (CF) Metadata Convention</dd><dt><span>geospatial_lat_units :</span></dt><dd>degrees_north</dd><dt><span>geospatial_lat_resolution :</span></dt><dd>0.01</dd><dt><span>geospatial_lon_units :</span></dt><dd>degrees_east</dd><dt><span>geospatial_lon_resolution :</span></dt><dd>0.01</dd><dt><span>acknowledgment :</span></dt><dd>The MODIS L2P sea surface temperature data are sponsored by NASA</dd><dt><span>creator_name :</span></dt><dd>Ed Armstrong, JPL PO.DAAC</dd><dt><span>creator_email :</span></dt><dd>edward.m.armstrong@jpl.nasa.gov</dd><dt><span>creator_url :</span></dt><dd>http://podaac.jpl.nasa.gov</dd><dt><span>project :</span></dt><dd>Group for High Resolution Sea Surface Temperature</dd><dt><span>publisher_name :</span></dt><dd>The GHRSST Project Office</dd><dt><span>publisher_url :</span></dt><dd>http://www.ghrsst.org</dd><dt><span>publisher_email :</span></dt><dd>ghrsst-po@nceo.ac.uk</dd><dt><span>processing_level :</span></dt><dd>L2P</dd><dt><span>cdm_data_type :</span></dt><dd>swath</dd><dt><span>startDirection :</span></dt><dd>Ascending</dd><dt><span>endDirection :</span></dt><dd>Descending</dd><dt><span>day_night_flag :</span></dt><dd>Day</dd></dl></div></li></ul></div></div>
</div>
</div>
<p>Let’s make a quick plot to take a look at the <code>sea_surface_temperature</code> variable.</p>
<div class="cell" data-execution_count="25">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a>modis_ds.sea_surface_temperature.plot() <span class="op">;</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<p><img src="04_On-Prem_Cloud_files/figure-html/cell-26-output-1.png" class="img-fluid"></p>
</div>
</div>
</section>
<section id="plot-modis-and-icesat-2-data-on-a-map" class="level3">
<h3 class="anchored" data-anchor-id="plot-modis-and-icesat-2-data-on-a-map">Plot MODIS and ICESat-2 data on a map</h3>
<div class="cell" data-execution_count="26">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a>map_proj <span class="op">=</span> ccrs.NorthPolarStereo()</span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-3"><a href="#cb32-3" aria-hidden="true" tabindex="-1"></a>fig <span class="op">=</span> plt.figure(figsize<span class="op">=</span>(<span class="dv">10</span>,<span class="dv">5</span>))</span>
<span id="cb32-4"><a href="#cb32-4" aria-hidden="true" tabindex="-1"></a>ax <span class="op">=</span> fig.add_subplot(projection<span class="op">=</span>map_proj)</span>
<span id="cb32-5"><a href="#cb32-5" aria-hidden="true" tabindex="-1"></a>ax.coastlines()</span>
<span id="cb32-6"><a href="#cb32-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-7"><a href="#cb32-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Plot MODIS sst, save object as sst_img, so we can add colorbar</span></span>
<span id="cb32-8"><a href="#cb32-8" aria-hidden="true" tabindex="-1"></a>sst_img <span class="op">=</span> ax.pcolormesh(modis_ds.lon, modis_ds.lat, modis_ds.sea_surface_temperature[<span class="dv">0</span>,:,:], </span>
<span id="cb32-9"><a href="#cb32-9" aria-hidden="true" tabindex="-1"></a>                        vmin<span class="op">=</span><span class="dv">240</span>, vmax<span class="op">=</span><span class="dv">270</span>,  <span class="co"># Set max and min values for plotting</span></span>
<span id="cb32-10"><a href="#cb32-10" aria-hidden="true" tabindex="-1"></a>                        cmap<span class="op">=</span><span class="st">'viridis'</span>, shading<span class="op">=</span><span class="st">'auto'</span>,   <span class="co"># shading='auto' to avoid warning</span></span>
<span id="cb32-11"><a href="#cb32-11" aria-hidden="true" tabindex="-1"></a>                        transform<span class="op">=</span>ccrs.PlateCarree())  <span class="co"># coords are lat,lon but map if NPS </span></span>
<span id="cb32-12"><a href="#cb32-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-13"><a href="#cb32-13" aria-hidden="true" tabindex="-1"></a><span class="co"># Plot IS2 surface height </span></span>
<span id="cb32-14"><a href="#cb32-14" aria-hidden="true" tabindex="-1"></a>is2_img <span class="op">=</span> ax.scatter(is2_ds.longitude, is2_ds.latitude,</span>
<span id="cb32-15"><a href="#cb32-15" aria-hidden="true" tabindex="-1"></a>                     c<span class="op">=</span>is2_ds.height_segment_height, </span>
<span id="cb32-16"><a href="#cb32-16" aria-hidden="true" tabindex="-1"></a>                     vmax<span class="op">=</span><span class="fl">1.5</span>,  <span class="co"># Set max height to plot</span></span>
<span id="cb32-17"><a href="#cb32-17" aria-hidden="true" tabindex="-1"></a>                     cmap<span class="op">=</span><span class="st">'Reds'</span>, alpha<span class="op">=</span><span class="fl">0.6</span>, s<span class="op">=</span><span class="dv">2</span>,</span>
<span id="cb32-18"><a href="#cb32-18" aria-hidden="true" tabindex="-1"></a>                     transform<span class="op">=</span>ccrs.PlateCarree())</span>
<span id="cb32-19"><a href="#cb32-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-20"><a href="#cb32-20" aria-hidden="true" tabindex="-1"></a><span class="co"># Add colorbars</span></span>
<span id="cb32-21"><a href="#cb32-21" aria-hidden="true" tabindex="-1"></a>fig.colorbar(sst_img, label<span class="op">=</span><span class="st">'MODIS SST (K)'</span>)</span>
<span id="cb32-22"><a href="#cb32-22" aria-hidden="true" tabindex="-1"></a>fig.colorbar(is2_img, label<span class="op">=</span><span class="st">'ATL07 Height (m)'</span>)</span>
<span id="cb32-23"><a href="#cb32-23" aria-hidden="true" tabindex="-1"></a></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="26">
<pre><code>&lt;matplotlib.colorbar.Colorbar at 0x7fb3944adb50&gt;</code></pre>
</div>
<div class="cell-output cell-output-display">
<p><img src="04_On-Prem_Cloud_files/figure-html/cell-27-output-2.png" class="img-fluid"></p>
</div>
</div>
</section>
<section id="extract-sst-coincident-with-icesat-2-track" class="level3">
<h3 class="anchored" data-anchor-id="extract-sst-coincident-with-icesat-2-track">Extract SST coincident with ICESat-2 track</h3>
<p>The MODIS SST is swath data, not a regularly-spaced grid of sea surface temperatures. ICESat-2 sea surface heights are irregularly spaced segments along one ground-track traced by the ATLAS instrument on-board ICESat-2. Fortunately, <code>pyresample</code> allows us to resample swath data.</p>
<p><code>pyresample</code> has many resampling methods. We’re going to use the nearest neighbour resampling method, which is implemented using a k-dimensional tree algorithm or <a href="https://en.wikipedia.org/wiki/K-d_tree#Nearest_neighbour_search">K-d tree</a>. K-d trees are data structures that improve search efficiency for large data sets.</p>
<p>The first step is to define the <em>geometry</em> of the ICESat-2 and MODIS data. To do this we use the latitudes and longitudes of the datasets.</p>
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a>is2_geometry <span class="op">=</span> pyresample.SwathDefinition(lons<span class="op">=</span>is2_ds.longitude,</span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a>                                          lats<span class="op">=</span>is2_ds.latitude)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a>modis_geometry <span class="op">=</span> pyresample.SwathDefinition(lons<span class="op">=</span>modis_ds.lon, lats<span class="op">=</span>modis_ds.lat)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>We then implement the resampling method, passing the two geometries we have defined, the data array we want to resample - in this case sea surface temperature, and a search radius. The resampling method expects a <code>numpy.Array</code> rather than an <code>xarray.DataArray</code>, so we use <code>values</code> to get the data as a <code>numpy.Array</code>.</p>
<p>We set the search radius to 1000 m. The MODIS data is nominally 1km spacing.</p>
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a>search_radius<span class="op">=</span><span class="fl">1000.</span></span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a>fill_value <span class="op">=</span> np.nan</span>
<span id="cb36-3"><a href="#cb36-3" aria-hidden="true" tabindex="-1"></a>is2_sst <span class="op">=</span> pyresample.kd_tree.resample_nearest(</span>
<span id="cb36-4"><a href="#cb36-4" aria-hidden="true" tabindex="-1"></a>    modis_geometry,</span>
<span id="cb36-5"><a href="#cb36-5" aria-hidden="true" tabindex="-1"></a>    modis_ds.sea_surface_temperature.values,</span>
<span id="cb36-6"><a href="#cb36-6" aria-hidden="true" tabindex="-1"></a>    is2_geometry,</span>
<span id="cb36-7"><a href="#cb36-7" aria-hidden="true" tabindex="-1"></a>    search_radius,</span>
<span id="cb36-8"><a href="#cb36-8" aria-hidden="true" tabindex="-1"></a>    fill_value<span class="op">=</span>fill_value</span>
<span id="cb36-9"><a href="#cb36-9" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell" data-execution_count="30">
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a>is2_sst</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="30">
<pre><code>array([263.375, 263.375, 263.375, ...,     nan,     nan,     nan],
      dtype=float32)</code></pre>
</div>
</div>
<div class="cell" data-execution_count="31">
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a>is2_ds[<span class="st">'sea_surface_temperature'</span>] <span class="op">=</span> xr.DataArray(is2_sst, dims<span class="op">=</span><span class="st">'segment'</span>)</span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a>is2_ds</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="31">

<div><svg style="position: absolute; width: 0; height: 0; overflow: hidden">
<defs>
<symbol id="icon-database" viewbox="0 0 32 32">
<path d="M16 0c-8.837 0-16 2.239-16 5v4c0 2.761 7.163 5 16 5s16-2.239 16-5v-4c0-2.761-7.163-5-16-5z"></path>
<path d="M16 17c-8.837 0-16-2.239-16-5v6c0 2.761 7.163 5 16 5s16-2.239 16-5v-6c0 2.761-7.163 5-16 5z"></path>
<path d="M16 26c-8.837 0-16-2.239-16-5v6c0 2.761 7.163 5 16 5s16-2.239 16-5v-6c0 2.761-7.163 5-16 5z"></path>
</symbol>
<symbol id="icon-file-text2" viewbox="0 0 32 32">
<path d="M28.681 7.159c-0.694-0.947-1.662-2.053-2.724-3.116s-2.169-2.030-3.116-2.724c-1.612-1.182-2.393-1.319-2.841-1.319h-15.5c-1.378 0-2.5 1.121-2.5 2.5v27c0 1.378 1.122 2.5 2.5 2.5h23c1.378 0 2.5-1.122 2.5-2.5v-19.5c0-0.448-0.137-1.23-1.319-2.841zM24.543 5.457c0.959 0.959 1.712 1.825 2.268 2.543h-4.811v-4.811c0.718 0.556 1.584 1.309 2.543 2.268zM28 29.5c0 0.271-0.229 0.5-0.5 0.5h-23c-0.271 0-0.5-0.229-0.5-0.5v-27c0-0.271 0.229-0.5 0.5-0.5 0 0 15.499-0 15.5 0v7c0 0.552 0.448 1 1 1h7v19.5z"></path>
<path d="M23 26h-14c-0.552 0-1-0.448-1-1s0.448-1 1-1h14c0.552 0 1 0.448 1 1s-0.448 1-1 1z"></path>
<path d="M23 22h-14c-0.552 0-1-0.448-1-1s0.448-1 1-1h14c0.552 0 1 0.448 1 1s-0.448 1-1 1z"></path>
<path d="M23 18h-14c-0.552 0-1-0.448-1-1s0.448-1 1-1h14c0.552 0 1 0.448 1 1s-0.448 1-1 1z"></path>
</symbol>
</defs>
</svg>
<style>/* CSS stylesheet for displaying xarray objects in jupyterlab.
 *
 */

:root {
  --xr-font-color0: var(--jp-content-font-color0, rgba(0, 0, 0, 1));
  --xr-font-color2: var(--jp-content-font-color2, rgba(0, 0, 0, 0.54));
  --xr-font-color3: var(--jp-content-font-color3, rgba(0, 0, 0, 0.38));
  --xr-border-color: var(--jp-border-color2, #e0e0e0);
  --xr-disabled-color: var(--jp-layout-color3, #bdbdbd);
  --xr-background-color: var(--jp-layout-color0, white);
  --xr-background-color-row-even: var(--jp-layout-color1, white);
  --xr-background-color-row-odd: var(--jp-layout-color2, #eeeeee);
}

html[theme=dark],
body.vscode-dark {
  --xr-font-color0: rgba(255, 255, 255, 1);
  --xr-font-color2: rgba(255, 255, 255, 0.54);
  --xr-font-color3: rgba(255, 255, 255, 0.38);
  --xr-border-color: #1F1F1F;
  --xr-disabled-color: #515151;
  --xr-background-color: #111111;
  --xr-background-color-row-even: #111111;
  --xr-background-color-row-odd: #313131;
}

.xr-wrap {
  display: block;
  min-width: 300px;
  max-width: 700px;
}

.xr-text-repr-fallback {
  /* fallback to plain text repr when CSS is not injected (untrusted notebook) */
  display: none;
}

.xr-header {
  padding-top: 6px;
  padding-bottom: 6px;
  margin-bottom: 4px;
  border-bottom: solid 1px var(--xr-border-color);
}

.xr-header > div,
.xr-header > ul {
  display: inline;
  margin-top: 0;
  margin-bottom: 0;
}

.xr-obj-type,
.xr-array-name {
  margin-left: 2px;
  margin-right: 10px;
}

.xr-obj-type {
  color: var(--xr-font-color2);
}

.xr-sections {
  padding-left: 0 !important;
  display: grid;
  grid-template-columns: 150px auto auto 1fr 20px 20px;
}

.xr-section-item {
  display: contents;
}

.xr-section-item input {
  display: none;
}

.xr-section-item input + label {
  color: var(--xr-disabled-color);
}

.xr-section-item input:enabled + label {
  cursor: pointer;
  color: var(--xr-font-color2);
}

.xr-section-item input:enabled + label:hover {
  color: var(--xr-font-color0);
}

.xr-section-summary {
  grid-column: 1;
  color: var(--xr-font-color2);
  font-weight: 500;
}

.xr-section-summary > span {
  display: inline-block;
  padding-left: 0.5em;
}

.xr-section-summary-in:disabled + label {
  color: var(--xr-font-color2);
}

.xr-section-summary-in + label:before {
  display: inline-block;
  content: '►';
  font-size: 11px;
  width: 15px;
  text-align: center;
}

.xr-section-summary-in:disabled + label:before {
  color: var(--xr-disabled-color);
}

.xr-section-summary-in:checked + label:before {
  content: '▼';
}

.xr-section-summary-in:checked + label > span {
  display: none;
}

.xr-section-summary,
.xr-section-inline-details {
  padding-top: 4px;
  padding-bottom: 4px;
}

.xr-section-inline-details {
  grid-column: 2 / -1;
}

.xr-section-details {
  display: none;
  grid-column: 1 / -1;
  margin-bottom: 5px;
}

.xr-section-summary-in:checked ~ .xr-section-details {
  display: contents;
}

.xr-array-wrap {
  grid-column: 1 / -1;
  display: grid;
  grid-template-columns: 20px auto;
}

.xr-array-wrap > label {
  grid-column: 1;
  vertical-align: top;
}

.xr-preview {
  color: var(--xr-font-color3);
}

.xr-array-preview,
.xr-array-data {
  padding: 0 5px !important;
  grid-column: 2;
}

.xr-array-data,
.xr-array-in:checked ~ .xr-array-preview {
  display: none;
}

.xr-array-in:checked ~ .xr-array-data,
.xr-array-preview {
  display: inline-block;
}

.xr-dim-list {
  display: inline-block !important;
  list-style: none;
  padding: 0 !important;
  margin: 0;
}

.xr-dim-list li {
  display: inline-block;
  padding: 0;
  margin: 0;
}

.xr-dim-list:before {
  content: '(';
}

.xr-dim-list:after {
  content: ')';
}

.xr-dim-list li:not(:last-child):after {
  content: ',';
  padding-right: 5px;
}

.xr-has-index {
  font-weight: bold;
}

.xr-var-list,
.xr-var-item {
  display: contents;
}

.xr-var-item > div,
.xr-var-item label,
.xr-var-item > .xr-var-name span {
  background-color: var(--xr-background-color-row-even);
  margin-bottom: 0;
}

.xr-var-item > .xr-var-name:hover span {
  padding-right: 5px;
}

.xr-var-list > li:nth-child(odd) > div,
.xr-var-list > li:nth-child(odd) > label,
.xr-var-list > li:nth-child(odd) > .xr-var-name span {
  background-color: var(--xr-background-color-row-odd);
}

.xr-var-name {
  grid-column: 1;
}

.xr-var-dims {
  grid-column: 2;
}

.xr-var-dtype {
  grid-column: 3;
  text-align: right;
  color: var(--xr-font-color2);
}

.xr-var-preview {
  grid-column: 4;
}

.xr-var-name,
.xr-var-dims,
.xr-var-dtype,
.xr-preview,
.xr-attrs dt {
  white-space: nowrap;
  overflow: hidden;
  text-overflow: ellipsis;
  padding-right: 10px;
}

.xr-var-name:hover,
.xr-var-dims:hover,
.xr-var-dtype:hover,
.xr-attrs dt:hover {
  overflow: visible;
  width: auto;
  z-index: 1;
}

.xr-var-attrs,
.xr-var-data {
  display: none;
  background-color: var(--xr-background-color) !important;
  padding-bottom: 5px !important;
}

.xr-var-attrs-in:checked ~ .xr-var-attrs,
.xr-var-data-in:checked ~ .xr-var-data {
  display: block;
}

.xr-var-data > table {
  float: right;
}

.xr-var-name span,
.xr-var-data,
.xr-attrs {
  padding-left: 25px !important;
}

.xr-attrs,
.xr-var-attrs,
.xr-var-data {
  grid-column: 1 / -1;
}

dl.xr-attrs {
  padding: 0;
  margin: 0;
  display: grid;
  grid-template-columns: 125px auto;
}

.xr-attrs dt,
.xr-attrs dd {
  padding: 0;
  margin: 0;
  float: left;
  padding-right: 10px;
  width: auto;
}

.xr-attrs dt {
  font-weight: normal;
  grid-column: 1;
}

.xr-attrs dt:hover span {
  display: inline-block;
  background: var(--xr-background-color);
  padding-right: 10px;
}

.xr-attrs dd {
  grid-column: 2;
  white-space: pre-wrap;
  word-break: break-all;
}

.xr-icon-database,
.xr-icon-file-text2 {
  display: inline-block;
  vertical-align: middle;
  width: 1em;
  height: 1.5em !important;
  stroke-width: 0;
  stroke: currentColor;
  fill: currentColor;
}
</style><pre class="xr-text-repr-fallback">&lt;xarray.Dataset&gt;
Dimensions:                  (segment: 235584)
Dimensions without coordinates: segment
Data variables:
    latitude                 (segment) float64 82.38 82.38 82.38 ... 72.61 72.61
    longitude                (segment) float64 -55.11 -55.11 ... 145.1 145.1
    delta_time               (segment) float64 4.642e+07 4.642e+07 ... 4.642e+07
    height_segment_height    (segment) float32 nan nan nan ... -0.4335 -0.4463
    sea_surface_temperature  (segment) float32 263.4 263.4 263.4 ... nan nan nan</pre><div class="xr-wrap" hidden=""><div class="xr-header"><div class="xr-obj-type">xarray.Dataset</div></div><ul class="xr-sections"><li class="xr-section-item"><input id="section-4e300b6c-664a-47a0-bbf8-b280e4a9155e" class="xr-section-summary-in" type="checkbox" disabled=""><label for="section-4e300b6c-664a-47a0-bbf8-b280e4a9155e" class="xr-section-summary" title="Expand/collapse section">Dimensions:</label><div class="xr-section-inline-details"><ul class="xr-dim-list"><li><span>segment</span>: 235584</li></ul></div><div class="xr-section-details"></div></li><li class="xr-section-item"><input id="section-0e7bde29-df88-4e35-a152-17cd43e89b6f" class="xr-section-summary-in" type="checkbox" disabled=""><label for="section-0e7bde29-df88-4e35-a152-17cd43e89b6f" class="xr-section-summary" title="Expand/collapse section">Coordinates: <span>(0)</span></label><div class="xr-section-inline-details"></div><div class="xr-section-details"><ul class="xr-var-list"></ul></div></li><li class="xr-section-item"><input id="section-521517a9-53aa-40fd-a860-d588911bc46c" class="xr-section-summary-in" type="checkbox" checked=""><label for="section-521517a9-53aa-40fd-a860-d588911bc46c" class="xr-section-summary">Data variables: <span>(5)</span></label><div class="xr-section-inline-details"></div><div class="xr-section-details"><ul class="xr-var-list"><li class="xr-var-item"><div class="xr-var-name"><span>latitude</span></div><div class="xr-var-dims">(segment)</div><div class="xr-var-dtype">float64</div><div class="xr-var-preview xr-preview">82.38 82.38 82.38 ... 72.61 72.61</div><input id="attrs-5dc5e00b-5bcb-42a2-9c2c-b3db3ebe1f1a" class="xr-var-attrs-in" type="checkbox"><label for="attrs-5dc5e00b-5bcb-42a2-9c2c-b3db3ebe1f1a" title="Show/Hide attributes"><svg class="icon xr-icon-file-text2"><use href="#icon-file-text2"></use></svg></label><input id="data-ac404419-2081-4aa4-ab1b-3e4652607679" class="xr-var-data-in" type="checkbox"><label for="data-ac404419-2081-4aa4-ab1b-3e4652607679" title="Show/Hide data repr"><svg class="icon xr-icon-database"><use href="#icon-database"></use></svg></label><div class="xr-var-attrs"><dl class="xr-attrs"><dt><span>contentType :</span></dt><dd>referenceInformation</dd><dt><span>coordinates :</span></dt><dd>delta_time longitude</dd><dt><span>description :</span></dt><dd>Latitude, WGS84, North=+, Lat of segment center</dd><dt><span>long_name :</span></dt><dd>Latitude</dd><dt><span>source :</span></dt><dd>ATBD, section 4.4</dd><dt><span>standard_name :</span></dt><dd>latitude</dd><dt><span>units :</span></dt><dd>degrees_north</dd><dt><span>valid_max :</span></dt><dd>90.0</dd><dt><span>valid_min :</span></dt><dd>-90.0</dd></dl></div><div class="xr-var-data"><pre>array([82.38431982, 82.38431982, 82.38431982, ..., 72.60984638,
       72.60977493, 72.60970985])</pre></div></li><li class="xr-var-item"><div class="xr-var-name"><span>longitude</span></div><div class="xr-var-dims">(segment)</div><div class="xr-var-dtype">float64</div><div class="xr-var-preview xr-preview">-55.11 -55.11 ... 145.1 145.1</div><input id="attrs-e106de78-efcf-43bc-a792-5d2e4e014699" class="xr-var-attrs-in" type="checkbox"><label for="attrs-e106de78-efcf-43bc-a792-5d2e4e014699" title="Show/Hide attributes"><svg class="icon xr-icon-file-text2"><use href="#icon-file-text2"></use></svg></label><input id="data-1f8e6d29-dddb-43d6-bfc6-6744ecf6ade6" class="xr-var-data-in" type="checkbox"><label for="data-1f8e6d29-dddb-43d6-bfc6-6744ecf6ade6" title="Show/Hide data repr"><svg class="icon xr-icon-database"><use href="#icon-database"></use></svg></label><div class="xr-var-attrs"><dl class="xr-attrs"><dt><span>contentType :</span></dt><dd>referenceInformation</dd><dt><span>coordinates :</span></dt><dd>delta_time latitude</dd><dt><span>description :</span></dt><dd>Longitude, WGS84, East=+,Lon of segment center</dd><dt><span>long_name :</span></dt><dd>Longitude</dd><dt><span>source :</span></dt><dd>ATBD, section 4.4</dd><dt><span>standard_name :</span></dt><dd>longitude</dd><dt><span>units :</span></dt><dd>degrees_east</dd><dt><span>valid_max :</span></dt><dd>180.0</dd><dt><span>valid_min :</span></dt><dd>-180.0</dd></dl></div><div class="xr-var-data"><pre>array([-55.10896068, -55.10896068, -55.10896068, ..., 145.05396164,
       145.05392851, 145.05389832])</pre></div></li><li class="xr-var-item"><div class="xr-var-name"><span>delta_time</span></div><div class="xr-var-dims">(segment)</div><div class="xr-var-dtype">float64</div><div class="xr-var-preview xr-preview">4.642e+07 4.642e+07 ... 4.642e+07</div><input id="attrs-90a6bd25-3112-4679-9e2b-5b0eb67d9b9c" class="xr-var-attrs-in" type="checkbox"><label for="attrs-90a6bd25-3112-4679-9e2b-5b0eb67d9b9c" title="Show/Hide attributes"><svg class="icon xr-icon-file-text2"><use href="#icon-file-text2"></use></svg></label><input id="data-8cc0d8a2-78eb-46e4-9856-bc013322b88b" class="xr-var-data-in" type="checkbox"><label for="data-8cc0d8a2-78eb-46e4-9856-bc013322b88b" title="Show/Hide data repr"><svg class="icon xr-icon-database"><use href="#icon-database"></use></svg></label><div class="xr-var-attrs"><dl class="xr-attrs"><dt><span>CLASS :</span></dt><dd>DIMENSION_SCALE</dd><dt><span>NAME :</span></dt><dd>gt1l/sea_ice_segments/delta_time</dd><dt><span>REFERENCE_LIST :</span></dt><dd>[(&lt;HDF5 object reference&gt;, 0) (&lt;HDF5 object reference&gt;, 0)
 (&lt;HDF5 object reference&gt;, 0) (&lt;HDF5 object reference&gt;, 0)
 (&lt;HDF5 object reference&gt;, 0) (&lt;HDF5 object reference&gt;, 0)
 (&lt;HDF5 object reference&gt;, 0) (&lt;HDF5 object reference&gt;, 0)
 (&lt;HDF5 object reference&gt;, 0) (&lt;HDF5 object reference&gt;, 0)
 (&lt;HDF5 object reference&gt;, 0) (&lt;HDF5 object reference&gt;, 0)
 (&lt;HDF5 object reference&gt;, 0) (&lt;HDF5 object reference&gt;, 0)
 (&lt;HDF5 object reference&gt;, 0) (&lt;HDF5 object reference&gt;, 0)
 (&lt;HDF5 object reference&gt;, 0) (&lt;HDF5 object reference&gt;, 0)
 (&lt;HDF5 object reference&gt;, 0) (&lt;HDF5 object reference&gt;, 0)
 (&lt;HDF5 object reference&gt;, 0) (&lt;HDF5 object reference&gt;, 0)
 (&lt;HDF5 object reference&gt;, 0) (&lt;HDF5 object reference&gt;, 0)
 (&lt;HDF5 object reference&gt;, 0) (&lt;HDF5 object reference&gt;, 0)
 (&lt;HDF5 object reference&gt;, 0) (&lt;HDF5 object reference&gt;, 0)
 (&lt;HDF5 object reference&gt;, 0) (&lt;HDF5 object reference&gt;, 0)
 (&lt;HDF5 object reference&gt;, 0) (&lt;HDF5 object reference&gt;, 0)
 (&lt;HDF5 object reference&gt;, 0) (&lt;HDF5 object reference&gt;, 0)
 (&lt;HDF5 object reference&gt;, 0) (&lt;HDF5 object reference&gt;, 0)
 (&lt;HDF5 object reference&gt;, 0) (&lt;HDF5 object reference&gt;, 0)
 (&lt;HDF5 object reference&gt;, 0) (&lt;HDF5 object reference&gt;, 0)
 (&lt;HDF5 object reference&gt;, 0) (&lt;HDF5 object reference&gt;, 0)
 (&lt;HDF5 object reference&gt;, 0) (&lt;HDF5 object reference&gt;, 0)
 (&lt;HDF5 object reference&gt;, 0) (&lt;HDF5 object reference&gt;, 0)
 (&lt;HDF5 object reference&gt;, 0) (&lt;HDF5 object reference&gt;, 0)
 (&lt;HDF5 object reference&gt;, 0) (&lt;HDF5 object reference&gt;, 0)
 (&lt;HDF5 object reference&gt;, 0) (&lt;HDF5 object reference&gt;, 0)
 (&lt;HDF5 object reference&gt;, 0) (&lt;HDF5 object reference&gt;, 0)
 (&lt;HDF5 object reference&gt;, 0) (&lt;HDF5 object reference&gt;, 0)
 (&lt;HDF5 object reference&gt;, 0) (&lt;HDF5 object reference&gt;, 0)
 (&lt;HDF5 object reference&gt;, 0) (&lt;HDF5 object reference&gt;, 0)
 (&lt;HDF5 object reference&gt;, 0) (&lt;HDF5 object reference&gt;, 0)
 (&lt;HDF5 object reference&gt;, 0) (&lt;HDF5 object reference&gt;, 0)
 (&lt;HDF5 object reference&gt;, 0) (&lt;HDF5 object reference&gt;, 0)
 (&lt;HDF5 object reference&gt;, 0) (&lt;HDF5 object reference&gt;, 0)
 (&lt;HDF5 object reference&gt;, 0) (&lt;HDF5 object reference&gt;, 0)
 (&lt;HDF5 object reference&gt;, 0) (&lt;HDF5 object reference&gt;, 0)
 (&lt;HDF5 object reference&gt;, 0) (&lt;HDF5 object reference&gt;, 0)
 (&lt;HDF5 object reference&gt;, 0) (&lt;HDF5 object reference&gt;, 0)
 (&lt;HDF5 object reference&gt;, 0) (&lt;HDF5 object reference&gt;, 0)
 (&lt;HDF5 object reference&gt;, 0) (&lt;HDF5 object reference&gt;, 0)
 (&lt;HDF5 object reference&gt;, 0) (&lt;HDF5 object reference&gt;, 0)
 (&lt;HDF5 object reference&gt;, 0) (&lt;HDF5 object reference&gt;, 0)]</dd><dt><span>contentType :</span></dt><dd>physicalMeasurement</dd><dt><span>coordinates :</span></dt><dd>latitude longitude</dd><dt><span>description :</span></dt><dd>Number of GPS seconds since the ATLAS SDP epoch. The ATLAS Standard Data Products (SDP) epoch offset is defined within /ancillary_data/atlas_sdp_gps_epoch as the number of GPS seconds between the GPS epoch (1980-01-06T00:00:00.000000Z UTC) and the ATLAS SDP epoch. By adding the offset contained within atlas_sdp_gps_epoch to delta time parameters, the time in gps_seconds relative to the GPS epoch can be computed.</dd><dt><span>long_name :</span></dt><dd>Elapsed GPS seconds</dd><dt><span>source :</span></dt><dd>telemetry</dd><dt><span>standard_name :</span></dt><dd>time</dd><dt><span>units :</span></dt><dd>seconds since 2018-01-01</dd></dl></div><div class="xr-var-data"><pre>array([46419293.64266939, 46419293.64266939, 46419293.64266939, ...,
       46419681.87646231, 46419681.87759533, 46419681.87862704])</pre></div></li><li class="xr-var-item"><div class="xr-var-name"><span>height_segment_height</span></div><div class="xr-var-dims">(segment)</div><div class="xr-var-dtype">float32</div><div class="xr-var-preview xr-preview">nan nan nan ... -0.4335 -0.4463</div><input id="attrs-317b4fdc-3d06-4b90-9d14-d722d5118103" class="xr-var-attrs-in" type="checkbox"><label for="attrs-317b4fdc-3d06-4b90-9d14-d722d5118103" title="Show/Hide attributes"><svg class="icon xr-icon-file-text2"><use href="#icon-file-text2"></use></svg></label><input id="data-99425a76-e471-4bd5-b833-1a5bc24c9bfb" class="xr-var-data-in" type="checkbox"><label for="data-99425a76-e471-4bd5-b833-1a5bc24c9bfb" title="Show/Hide data repr"><svg class="icon xr-icon-database"><use href="#icon-database"></use></svg></label><div class="xr-var-attrs"><dl class="xr-attrs"><dt><span>_FillValue :</span></dt><dd>3.4028235e+38</dd><dt><span>contentType :</span></dt><dd>referenceInformation</dd><dt><span>coordinates :</span></dt><dd>../delta_time ../latitude ../longitude</dd><dt><span>description :</span></dt><dd>Mean height from along-track segment fit detremined by the sea ice algorithm. The sea ice height is relative to the tide-free MSS.</dd><dt><span>long_name :</span></dt><dd>height of segment surface</dd><dt><span>source :</span></dt><dd>ATBD, section 4.2.2.4</dd><dt><span>units :</span></dt><dd>meters</dd></dl></div><div class="xr-var-data"><pre>array([        nan,         nan,         nan, ..., -0.46550068,
       -0.43347716, -0.4462675 ], dtype=float32)</pre></div></li><li class="xr-var-item"><div class="xr-var-name"><span>sea_surface_temperature</span></div><div class="xr-var-dims">(segment)</div><div class="xr-var-dtype">float32</div><div class="xr-var-preview xr-preview">263.4 263.4 263.4 ... nan nan nan</div><input id="attrs-7a3e958a-cceb-4bb7-a4d8-a21b2815c2ae" class="xr-var-attrs-in" type="checkbox" disabled=""><label for="attrs-7a3e958a-cceb-4bb7-a4d8-a21b2815c2ae" title="Show/Hide attributes"><svg class="icon xr-icon-file-text2"><use href="#icon-file-text2"></use></svg></label><input id="data-e2275027-c3a2-4efa-bfc2-46c957053739" class="xr-var-data-in" type="checkbox"><label for="data-e2275027-c3a2-4efa-bfc2-46c957053739" title="Show/Hide data repr"><svg class="icon xr-icon-database"><use href="#icon-database"></use></svg></label><div class="xr-var-attrs"><dl class="xr-attrs"></dl></div><div class="xr-var-data"><pre>array([263.375, 263.375, 263.375, ...,     nan,     nan,     nan],
      dtype=float32)</pre></div></li></ul></div></li><li class="xr-section-item"><input id="section-b2115630-159f-4d0e-8325-70c07fd17a27" class="xr-section-summary-in" type="checkbox" disabled=""><label for="section-b2115630-159f-4d0e-8325-70c07fd17a27" class="xr-section-summary" title="Expand/collapse section">Attributes: <span>(0)</span></label><div class="xr-section-inline-details"></div><div class="xr-section-details"><dl class="xr-attrs"></dl></div></li></ul></div></div>
</div>
</div>
</section>
<section id="plot-sst-and-height-along-track" class="level3">
<h3 class="anchored" data-anchor-id="plot-sst-and-height-along-track">Plot SST and Height along track</h3>
<p>This is a quick plot of the extracted data. We’re using <code>matplotlib</code> so we can use latitude as the x-value:</p>
<div class="cell" data-execution_count="32">
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a>is2_ds <span class="op">=</span> is2_ds.set_coords([<span class="st">'latitude'</span>])</span>
<span id="cb40-2"><a href="#cb40-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-3"><a href="#cb40-3" aria-hidden="true" tabindex="-1"></a>fig, ax1 <span class="op">=</span> plt.subplots(figsize<span class="op">=</span>(<span class="dv">15</span>, <span class="dv">7</span>))</span>
<span id="cb40-4"><a href="#cb40-4" aria-hidden="true" tabindex="-1"></a>ax1.set_xlim(<span class="fl">82.</span>,<span class="fl">88.</span>)</span>
<span id="cb40-5"><a href="#cb40-5" aria-hidden="true" tabindex="-1"></a>ax1.plot(is2_ds.latitude, is2_ds.sea_surface_temperature, </span>
<span id="cb40-6"><a href="#cb40-6" aria-hidden="true" tabindex="-1"></a>         color<span class="op">=</span><span class="st">'orange'</span>, label<span class="op">=</span><span class="st">'SST'</span>, zorder<span class="op">=</span><span class="dv">3</span>)</span>
<span id="cb40-7"><a href="#cb40-7" aria-hidden="true" tabindex="-1"></a>ax1.set_ylabel(<span class="st">'SST (K)'</span>)</span>
<span id="cb40-8"><a href="#cb40-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-9"><a href="#cb40-9" aria-hidden="true" tabindex="-1"></a>ax2 <span class="op">=</span> ax1.twinx()</span>
<span id="cb40-10"><a href="#cb40-10" aria-hidden="true" tabindex="-1"></a>ax2.plot(is2_ds.latitude, is2_ds.height_segment_height, label<span class="op">=</span><span class="st">'Height'</span>)</span>
<span id="cb40-11"><a href="#cb40-11" aria-hidden="true" tabindex="-1"></a>ax2.set_ylabel(<span class="st">'Height (m)'</span>)</span>
<span id="cb40-12"><a href="#cb40-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-13"><a href="#cb40-13" aria-hidden="true" tabindex="-1"></a>fig.legend()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="32">
<pre><code>&lt;matplotlib.legend.Legend at 0x7fb39fcd8040&gt;</code></pre>
</div>
<div class="cell-output cell-output-display">
<p><img src="04_On-Prem_Cloud_files/figure-html/cell-33-output-2.png" class="img-fluid"></p>
</div>
</div>


</section>
</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    toggleBodyColorMode(window.document.querySelector("link#quarto-bootstrap"));
  }
  toggleBodyColorPrimary();  
  const disableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'prefetch';
    }
  }
  const enableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'stylesheet';
    }
  }
  const manageTransitions = (selector, allowTransitions) => {
    const els = window.document.querySelectorAll(selector);
    for (let i=0; i < els.length; i++) {
      const el = els[i];
      if (allowTransitions) {
        el.classList.remove('notransition');
      } else {
        el.classList.add('notransition');
      }
    }
  }
  const toggleColorMode = (alternate) => {
    // Switch the stylesheets
    const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
    manageTransitions('#quarto-margin-sidebar .nav-link', false);
    if (alternate) {
      enableStylesheet(alternateStylesheets);
      for (const sheetNode of alternateStylesheets) {
        if (sheetNode.id === "quarto-bootstrap") {
          toggleBodyColorMode(sheetNode);
        }
      }
    } else {
      disableStylesheet(alternateStylesheets);
      toggleBodyColorPrimary();
    }
    manageTransitions('#quarto-margin-sidebar .nav-link', true);
    // Switch the toggles
    const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
    for (let i=0; i < toggles.length; i++) {
      const toggle = toggles[i];
      if (toggle) {
        if (alternate) {
          toggle.classList.add("alternate");     
        } else {
          toggle.classList.remove("alternate");
        }
      }
    }
  }
  const isFileUrl = () => { 
    return window.location.protocol === 'file:';
  }
  const hasAlternateSentinel = () => {  
    let styleSentinel = getColorSchemeSentinel();
    if (styleSentinel !== null) {
      return styleSentinel === "alternate";
    } else {
      return false;
    }
  }
  const setStyleSentinel = (alternate) => {
    const value = alternate ? "alternate" : "default";
    if (!isFileUrl()) {
      window.localStorage.setItem("quarto-color-scheme", value);
    } else {
      localAlternateSentinel = value;
    }
  }
  const getColorSchemeSentinel = () => {
    if (!isFileUrl()) {
      const storageValue = window.localStorage.getItem("quarto-color-scheme");
      return storageValue != null ? storageValue : localAlternateSentinel;
    } else {
      return localAlternateSentinel;
    }
  }
  let localAlternateSentinel = 'default';
  // Dark / light mode switch
  window.quartoToggleColorScheme = () => {
    // Read the current dark / light value 
    let toAlternate = !hasAlternateSentinel();
    toggleColorMode(toAlternate);
    setStyleSentinel(toAlternate);
  };
  // Ensure there is a toggle, if there isn't float one in the top right
  if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
    const a = window.document.createElement('a');
    a.classList.add('top-right');
    a.classList.add('quarto-color-scheme-toggle');
    a.href = "";
    a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
    const i = window.document.createElement("i");
    i.classList.add('bi');
    a.appendChild(i);
    window.document.body.appendChild(a);
  }
  // Switch to dark mode if need be
  if (hasAlternateSentinel()) {
    toggleColorMode(true);
  } 
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    setTimeout(function() {
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      let href = ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const cites = ref.parentNode.getAttribute('data-cites').split(' ');
    tippyHover(ref, function() {
      var popup = window.document.createElement('div');
      cites.forEach(function(cite) {
        var citeDiv = window.document.createElement('div');
        citeDiv.classList.add('hanging-indent');
        citeDiv.classList.add('csl-entry');
        var biblioDiv = window.document.getElementById('ref-' + cite);
        if (biblioDiv) {
          citeDiv.innerHTML = biblioDiv.innerHTML;
        }
        popup.appendChild(citeDiv);
      });
      return popup.innerHTML;
    });
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="../tutorials/index.html" class="pagination-link">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text">Tutorials</span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="../in-development/index.html" class="pagination-link">
        <span class="nav-page-text">In Development</span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
      <div class="nav-footer-center">NASA Openscapes Team (2021). Earthdata Cloud Cookbook (Version v0.0.1).</div>
  </div>
</footer>



</body></html>