# How-To Guides Parking Lot

This is a document to capture and organize How-To Guides that do not,
yet, have a place in the Cookbook.  I've pulled examples from the
[Hackday Google Doc](https://docs.google.com/document/d/1fzT-iSFlWZLS38eoPmFseljyMKDQIAc-24qH6QpnRCc/edit#)

Not all of these how-tos may be required.  Some may be redundant.
Some may be too complicated and could be broken into several How-Tos.
Feel free to add comments, links, notes, etc under each suggested
How-To.  Also suggest changes to the wording.  Following the Divio
documentation guide, I've tried to name how-tos with descriptive names
that start "How do I... ?". 

How do I reformat data files?

How do I reproject and regrid?

How do I aggregate data?

How do I plot data?

How do I use Harmony to reproject a data file?

How do I search the USGS Landsat Cloud?

How do I access data in the USGS Landsat Cloud?

How do I find OPeNDAP datasets?  

How do I open an OPeNDAP file in the cloud?  Include Authentication?  

How do I open/access an OPeNDAP file from my local machine?  

How do I open a Zarr file in the cloud?

How do I open a COG (Cloud-Optimized-GeoTIFF) in the cloud?

How do I use Kerchunk to reformat files?  _needs refining_

How do I use CMR STAC to access data in the cloud?

How do I use Matlab in the cloud?

How do I add a python package to a 2i2c environment?

How do I reproduce a shared cloud environment on my local machines
