---
title: How do I access data using APIs?
---

## Using APIs

API stands for Application Programming Interface, and is basically "like a digital mediator that enables different software applications to talk to each other and exchange information. It defines the methods, parameters, and data formats you can use to access certain features or retrieve data from an application or service." ([How to Use An API](https://zapier.com/blog/how-to-use-api/#what))

## How do I know?

How do I know what API services are available for a dataset?

Some but not all datasets have API services that can reproject, resample or reformat files on the server file. These How-To's below show how to find which services are available:

### Finding Services using EarthData Search

After selecting a dataset and the needed files using Earthdata Search ([tutorial here](https://nasa-openscapes.github.io/earthdata-cloud-cookbook/how-tos/find-data/earthdata_search.html)), when the download files button is selected, it will navigate users to a new page on the sidebar. If the dataset is customizable through APIs, different options will pop up under "Select a data access method" or "Configure data customization options"

### Finding Services using CMR

Follow [this link](https://cmr.earthdata.nasa.gov/search/site/docs/search/api.html#c-service-parameters) to see how to programmatically discover what services are associated with what NASA Earthdata.

# NASA API Examples

## Harmony

[Harmony](https://harmony.earthdata.nasa.gov/) allows you to seamlessly analyze Earth observation data from different NASA data centers with services that offer data reduction and common access mechanisms across all NASA data centers. There is a python client library called [harmony-py](https://github.com/nasa/harmony-py) that exists as a wrapper for the Harmony services, and [this notebook](https://github.com/nasa/harmony/blob/main/docs/Harmony%20API%20introduction.ipynb) gives a brief introduction to the Harmony API services.

## OPeNDAP

OPeNDAP, or the [Open-source Project for a Network Data Access Protocol](https://www.earthdata.nasa.gov/engage/open-data-services-and-software/api/opendap), is a data server that allows for accessing scientific datasets through the public internet. OPeNDAP links can be acquired through dataset landing pages or the [common metadata repository](https://cmr.earthdata.nasa.gov/search/site/collections/directory/eosdis). For more information, see the [OPeNDAP Data Access Client Tutorials](https://opendap.github.io/documentation/tutorials/DataAccessTutorials.html).

## `earthaccess`
   
[`earthaccess`](https://earthaccess.readthedocs.io/en/latest/) is a python library to search, download or stream NASA Earth science data with just a few lines of code that also abstracts a lot of other APIs developed by NASA. 

## AppEEARS

The [Application for Extracting and Exploring Analysis Ready Samples (AρρEEARS)](https://appeears.earthdatacloud.nasa.gov/) offers users a simple and efficient way to perform data access and transformation processes. By enabling users to subset data spatially, temporally, and by layer, the volume of data downloaded for analysis is greatly reduced. AppEEARS requests can be submitted in website and via API. In a same way, outputs generated can also be accessed from AppEEARS website and through API. View [AppEEARS documentation](https://appeears.earthdatacloud.nasa.gov/help) and [API documentation](https://appeears.earthdatacloud.nasa.gov/api/) for more information. Additionally, you can work with the data in the cloud using provided S3 links. Visit [AppEEARS Data Resources Repository](https://github.com/nasa/AppEEARS-Data-Resources) for more tutorials on how to work with AppEEARS programaticaly. 
