---
title: Initial Setup
execute:
  eval: false
---

## Overview

Setup is complete when you can answer yes to the following:

- "can you run jupyter" 
- "install quarto and make sure you can render a  hello world doc" 
- "can you restore the venv and render the openscapes site"

The following is written for the command line, and we can update with other scenarios as we go. 


## Jupyter

First, install Jupyter (learn more at [jupyter.org/install](https://jupyter.org/install))

It's recommended that you use conda to install. If you need to first install conda, follow the [conda installation instructions](https://docs.conda.io/projects/conda/en/latest/user-guide/install/download.html). 

```{bash}
conda install jupyterlab
```



## Quarto

https://github.com/quarto-dev/quarto-cli/releases/


## Virtual environment

I also suggest that we pick a recommended virtual environment configuration (probably venv not conda) and suggest that everyone use that. 

## GitHub

need an account, set up locally. [ more] 

## Cookbook

Now clone our book. [more here] 

Then move on to the workflow chapter





