---
title: Onboarding Mentors
---

We expect many contributors are folks who are part of the NASA Openscapes Mentor Community, involved in user support services at the NASA EOSDIS Distributed Active Archive Centers (DAACs). This page is onboarding information for these Mentors. Further chapters describe how to onboard to all the tech and workflows that everyone can use to contribute to the Cookbook.

## Welcome to the mentor community!

As we onboard more folks to grow our cross-DAAC [NASA Mentors community](https://nasa-openscapes.github.io/mentors.html), we will be documenting the onboarding process here. We expect Mentors to have different experiences, expertise, technical skills, and job responsibilities. Goals of onboarding will be:

-   get to know each other, strengthen relationships across DAACs and NASA
-   share previous work by NASA Mentors
-   identify common needs and priorities
-   develop common approaches and solutions
-   strengthen technical skills
-   strengthen teaching skills
-   build habits and confidence contributing to common materials
-   meet Champions and other researchers to better design how we support them

We meet remotely, primarily through Mentor Calls (focus: learning and planning) and Coworking Calls (focus: screensharing and doing). We teach together through events like Hackathons, Workshops, and Openscapes Champions Cohorts.

## Mentor schedule

See our schedule of events at <https://nasa-openscapes.github.io/mentors>

## Tooling checklist

The tooling we use to collaborate include the following. We don't expect everyone to have the same level of skills across all software. We will hold skill-building clinics to help strengthen familiarity and confidence, with the goal that everyone is able to contribute through overlapping and interoperable skills.

When you join, expect to get access to the following. We'll track this in the `OpenscapesParticipantsList [ nasa-mentors ]` spreadsheet, which is in the Google Drive Folder. Note that to add you to GitHub and the 2i2c JupyterHub, we will need you to share your GitHub username see [setup](setup.qmd) instructions.

-   ✅ Google Calendar invitations (for Cohort Calls and Coworking)

-   ✅ Google Drive (for shared notes and presentations; see below)

-   ✅ Slack (for connecting to NASA Mentors and broader Openscapes community; see below)

-   ✅ GitHub (for sharing code and documentation, project management and code review; see [Contibuting Setup](setup.qmd)). We will ask for your GitHub username and add you to the NASA-Openscapes Organization.

-   ✅ 2i2c JupyterHub (for Python, R, and Matlab; see [Contibuting Setup](setup.qmd)). We will add you with your GitHub username.

-   ✅ Carpentries Instructor Training (for a common pedagogy for teaching learners code- and data- intensive science).

### Openscapes Slack

Channels to join:

-   nasa-mentors (private)
-   2023-nasa-champions (private)
-   `#cloud-infrastructure`

Here is deeper documentation about [Openscapes Slack](https://openscapes.github.io/approach-guide/approach/tooling.html#slack).

### Mentors Google Drive

We have a shared Google Drive folder: `NASA-OpenscapesMentors [ nasa-mentors ]`. We'll add you with edit privileges. There is a README file within it that orients you to the folders within. The convention is that within the `[ brackets ]` is who has permission within the folder.

### Mentors GitHub Organization

We'll add you to our [NASA-Openscapes](https://github.com/NASA-Openscapes) GitHub Organization.

### Carpentries Instructor Training

As a professional development opportunity for Mentors, we partner with [The Carpentries](https://carpentries.org/), a nonprofit that teaches introductory coding skills around the world. Their remote [Instructor Training](https://carpentries.org/become-instructor/) is not coding-specific, but it is a pedagogical approach to teaching technical topics. If you would like to sign up, we have an access code that you can use to select the date-times via the [Instructor Training event calendar](https://carpentries.github.io/instructor-training/training_calendar#upcoming-instructor-training).

## Background

NASA Openscapes is a cross-DAAC mentor community creating & teaching resources to help researchers migrate workflows to the cloud. We meet and learn together, working with alignment on common needs for researchers using NASA Earthdata. Mentors receive Carpentries Instructor training and Openscapes mentorship to help you refine teaching strategies for Cloud, while collaborating on cloud tutorials to reuse rather than reinventing separately.

Together, we will teach and support in opportunities of different types: Hackathons, Workshops, and the Openscapes Champions program. We expect a range of technical ability and teaching experience. Through these growth opportunities within a broader community engagement approach, you will also gain visibility for your work as well as for your DAACs. The expected time commitment is 3-4 days/month per year. This accounts for a minimum of 4 hours/month of synchronous calls with the rest of the time being self-directed towards improving support approaches for your specific DAAC.

### Resources 

To get a broader sense of the NASA Openscapes Community's work, please review these recent resources. View the full list of talks and workshops at <https://nasa-openscapes.github.io>.

-   [NASA Openscapes: Supporting NASA EarthData Users Transition to the Cloud](https://docs.google.com/presentation/d/1klEzB3voQZ5_LB9bzuzWRIR7ldcz0gyfbiCcf1XiBE4/edit?usp=sharing) - November 2 2023. Erin Robinson, GHRC User Working Group

-   [NASA Openscapes Mentors' Retreat 2023: Summary and Moving Toward Sustainability](https://docs.google.com/presentation/d/1m515raX2MNCF4evn0qNqTIJT3EfhKIBuS7GGRLayDpM/edit#slide=id.g1b5922f14f8_0_83) - September 18, 2023. Catalina Taglialatela and the NASA Openscapes Mentors, NASA HQ Meeting

-   [Working with NASA Earthdata in the Cloud](https://docs.google.com/presentation/d/1rh6UGUIKp8nNc71jKYQAPPBIoVyikQmQ8CcvwGLn2hI/edit#slide=id.g142ea985af2_0_1)- January 24, 2023 - Amy Steiker, Bri Lind, Julie Lowndes, Luis López, Michele Thornton, and the NASA Openscapes Mentors. \[ESIP Winter Meeting\](https://2023januaryesipmeeting.sched.com/event/1EwXE/enabling-open-science-with-nasas-earthdata-in-the-cloud) "Enabling Open Science with NASA's Earthdata in the Cloud" Session

-   [NASA Openscapes: Movement building with the Flywheel](https://docs.google.com/presentation/d/1BK678MADRg6QkejRQI_5KREGn6DzzQqAS4StsjXmi-k/edit#slide=id.g1b5922f14f8_0_83) - March 31, 2023, Erin Robinson & Julie Lowndes. NASA Open Source Science Working Group

-   [Shifting institutional culture to develop climate solutions with Open Science](https://eartharxiv.org/repository/view/5948/) Lowndes et al 2023 (preprint, EarthArXiv)
